
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.verimatrix.omi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.868+09:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "AdminMgmtService",
                      portName = "AdminMgmt",
                      targetNamespace = "http://www.verimatrix.com/omi",
                      wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                      endpointInterface = "com.verimatrix.omi.AdminMgmt")
                      
public class AdminMgmtImpl implements AdminMgmt {

    private static final Logger LOG = Logger.getLogger(AdminMgmtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.verimatrix.omi.AdminMgmt#signOff(com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result signOff(com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation signOff");
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId687778507");
            _return.setResultCode(536087711);
            _return.setResultText("ResultText-2065154860");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id1666120929");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.AdminMgmt#signOn(com.verimatrix.schemas.omitypes.UserLoginAttributes  userAttributes ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle ,)com.verimatrix.schemas.omitypes.Result  result )*
     */
    public void signOn(com.verimatrix.schemas.omitypes.UserLoginAttributes userAttributes,javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.SessionHandle> sessionHandle,javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.Result> result) { 
        LOG.info("Executing operation signOn");
        System.out.println(userAttributes);
        try {
            com.verimatrix.schemas.omitypes.SessionHandle sessionHandleValue = new com.verimatrix.schemas.omitypes.SessionHandle();
            sessionHandleValue.setHandle("Handle1806586171");
            sessionHandle.value = sessionHandleValue;
            com.verimatrix.schemas.omitypes.Result resultValue = new com.verimatrix.schemas.omitypes.Result();
            resultValue.setResultId("ResultId-2076307741");
            resultValue.setResultCode(1482180169);
            resultValue.setResultText("ResultText-1986568548");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> resultValueResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData resultValueResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            resultValueResultDataVal1.setId("Id451141119");
            byte[] resultValueResultDataVal1Data = new byte[] {};
            resultValueResultDataVal1.setData(resultValueResultDataVal1Data);
            resultValueResultData.add(resultValueResultDataVal1);
            resultValue.getResultData().addAll(resultValueResultData);
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
