
package com.verimatrix.omi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.680+09:00
 * Generated source version: 2.7.13
 * 
 */
public final class AdminMgmt_AdminMgmt_Client {

    private static final QName SERVICE_NAME = new QName("http://www.verimatrix.com/omi", "AdminMgmtService");

    private AdminMgmt_AdminMgmt_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AdminMgmtService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AdminMgmtService ss = new AdminMgmtService(wsdlURL, SERVICE_NAME);
        AdminMgmt port = ss.getAdminMgmt();  
        
        {
        System.out.println("Invoking signOff...");
        com.verimatrix.schemas.omitypes.SessionHandle _signOff_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _signOff_sessionHandle.setHandle("Handle735410260");
        com.verimatrix.schemas.omitypes.Result _signOff__return = port.signOff(_signOff_sessionHandle);
        System.out.println("signOff.result=" + _signOff__return);


        }
        {
        System.out.println("Invoking signOn...");
        com.verimatrix.schemas.omitypes.UserLoginAttributes _signOn_userAttributes = new com.verimatrix.schemas.omitypes.UserLoginAttributes();
        _signOn_userAttributes.setUserName("UserName836254617");
        _signOn_userAttributes.setPassword("Password1490179674");
        javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.SessionHandle> _signOn_sessionHandle = new javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.SessionHandle>();
        javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.Result> _signOn_result = new javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.Result>();
        port.signOn(_signOn_userAttributes, _signOn_sessionHandle, _signOn_result);

        System.out.println("signOn._signOn_sessionHandle=" + _signOn_sessionHandle.value);
        System.out.println("signOn._signOn_result=" + _signOn_result.value);

        }

        System.exit(0);
    }

}
