package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.930+09:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://www.verimatrix.com/omi", name = "AdminMgmt")
@XmlSeeAlso({com.verimatrix.schemas.iptvtypes.ObjectFactory.class, com.verimatrix.schemas.omitypes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AdminMgmt {

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/signOff")
    public com.verimatrix.schemas.omitypes.Result signOff(
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebMethod(action = "http://www.verimatrix.com/omi/signOn")
    public void signOn(
        @WebParam(partName = "userAttributes", name = "userAttributes")
        com.verimatrix.schemas.omitypes.UserLoginAttributes userAttributes,
        @WebParam(partName = "sessionHandle", mode = WebParam.Mode.OUT, name = "sessionHandle")
        javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.SessionHandle> sessionHandle,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result")
        javax.xml.ws.Holder<com.verimatrix.schemas.omitypes.Result> result
    );
}
