package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.899+09:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://www.verimatrix.com/omi", name = "ConfigurationMgmt")
@XmlSeeAlso({com.verimatrix.schemas.iptvtypes.ObjectFactory.class, com.verimatrix.schemas.omitypes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ConfigurationMgmt {

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/modifySite")
    public com.verimatrix.schemas.omitypes.Result modifySite(
        @WebParam(partName = "site", name = "site")
        com.verimatrix.schemas.omitypes.Site site,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getEncryptionApplianceList")
    public com.verimatrix.schemas.omitypes.EncryptionApplianceResult getEncryptionApplianceList(
        @WebParam(partName = "encryptionApplianceQuery", name = "encryptionApplianceQuery")
        com.verimatrix.schemas.omitypes.EncryptionApplianceQuery encryptionApplianceQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getSite")
    public com.verimatrix.schemas.omitypes.SiteListResult getSiteList(
        @WebParam(partName = "siteListQuery", name = "siteListQuery")
        com.verimatrix.schemas.omitypes.SiteListQuery siteListQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getGroupLicenseData")
    public com.verimatrix.schemas.omitypes.GroupLicenseDataResult getGroupLicenseData(
        @WebParam(partName = "groupLicenseDataQuery", name = "groupLicenseDataQuery")
        com.verimatrix.schemas.omitypes.GroupLicenseDataQuery groupLicenseDataQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyNetwork")
    public com.verimatrix.schemas.omitypes.Result modifyNetwork(
        @WebParam(partName = "network", name = "network")
        com.verimatrix.schemas.omitypes.Network network,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getLicenseGroups")
    public com.verimatrix.schemas.omitypes.LicenseGroupsResult getLicenseGroups(
        @WebParam(partName = "licenseGroupsQuery", name = "licenseGroupsQuery")
        com.verimatrix.schemas.omitypes.LicenseGroupsQuery licenseGroupsQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getDeviceTypeLicenseData")
    public com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult getDeviceTypeLicenseData(
        @WebParam(partName = "deviceTypeLicenseDataQuery", name = "deviceTypeLicenseDataQuery")
        com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataQuery deviceTypeLicenseDataQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentList")
    public com.verimatrix.schemas.omitypes.NetworkContentResult getNetworkContentList(
        @WebParam(partName = "networkContentQuery", name = "networkContentQuery")
        com.verimatrix.schemas.omitypes.NetworkContentQuery networkContentQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/addSite")
    public com.verimatrix.schemas.omitypes.Result addSite(
        @WebParam(partName = "site", name = "site")
        com.verimatrix.schemas.omitypes.Site site,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkDeviceList")
    public com.verimatrix.schemas.omitypes.DeviceListResult getNetworkDeviceList(
        @WebParam(partName = "networkDeviceListQuery", name = "networkDeviceListQuery")
        com.verimatrix.schemas.omitypes.NetworkDeviceListQuery networkDeviceListQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getSite")
    public com.verimatrix.schemas.omitypes.SiteResult getSite(
        @WebParam(partName = "siteQuery", name = "siteQuery")
        com.verimatrix.schemas.omitypes.SiteQuery siteQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeNetwork")
    public com.verimatrix.schemas.omitypes.Result removeNetwork(
        @WebParam(partName = "network", name = "network")
        com.verimatrix.schemas.omitypes.Network network,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkList")
    public com.verimatrix.schemas.omitypes.NetworkListResult getNetworkList(
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeSite")
    public com.verimatrix.schemas.omitypes.Result removeSite(
        @WebParam(partName = "site", name = "site")
        com.verimatrix.schemas.omitypes.Site site,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getEncryptionApplianceConfiguration")
    public com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationResult getEncryptionApplianceConfiguration(
        @WebParam(partName = "encryptionApplianceConfigurationQuery", name = "encryptionApplianceConfigurationQuery")
        com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationQuery encryptionApplianceConfigurationQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/addNetwork")
    public com.verimatrix.schemas.omitypes.Result addNetwork(
        @WebParam(partName = "network", name = "network")
        com.verimatrix.schemas.omitypes.Network network,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );
}
