
package com.verimatrix.omi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.243+09:00
 * Generated source version: 2.7.13
 * 
 */
public final class ConfigurationMgmt_ConfigurationMgmt_Client {

    private static final QName SERVICE_NAME = new QName("http://www.verimatrix.com/omi", "ConfigurationMgmtService");

    private ConfigurationMgmt_ConfigurationMgmt_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConfigurationMgmtService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConfigurationMgmtService ss = new ConfigurationMgmtService(wsdlURL, SERVICE_NAME);
        ConfigurationMgmt port = ss.getConfigurationMgmt();  
        
        {
        System.out.println("Invoking modifySite...");
        com.verimatrix.schemas.omitypes.Site _modifySite_site = new com.verimatrix.schemas.omitypes.Site();
        _modifySite_site.setSmsSiteId("SmsSiteId-1643405032");
        com.verimatrix.schemas.omitypes.SiteEntityType _modifySite_siteEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.WHOLESALER;
        _modifySite_site.setEntityType(_modifySite_siteEntityType);
        _modifySite_site.setName("Name-1540431236");
        _modifySite_site.setDescription("Description-908115561");
        _modifySite_site.setSiteId("SiteId718171848");
        _modifySite_site.setAuthPassword("AuthPassword65845983");
        com.verimatrix.schemas.omitypes.SessionHandle _modifySite_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifySite_sessionHandle.setHandle("Handle81715130");
        com.verimatrix.schemas.omitypes.Result _modifySite__return = port.modifySite(_modifySite_site, _modifySite_sessionHandle);
        System.out.println("modifySite.result=" + _modifySite__return);


        }
        {
        System.out.println("Invoking getEncryptionApplianceList...");
        com.verimatrix.schemas.omitypes.EncryptionApplianceQuery _getEncryptionApplianceList_encryptionApplianceQuery = new com.verimatrix.schemas.omitypes.EncryptionApplianceQuery();
        _getEncryptionApplianceList_encryptionApplianceQuery.setSmsNetworkId("SmsNetworkId-432586265");
        com.verimatrix.schemas.omitypes.SessionHandle _getEncryptionApplianceList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getEncryptionApplianceList_sessionHandle.setHandle("Handle563405035");
        com.verimatrix.schemas.omitypes.EncryptionApplianceResult _getEncryptionApplianceList__return = port.getEncryptionApplianceList(_getEncryptionApplianceList_encryptionApplianceQuery, _getEncryptionApplianceList_sessionHandle);
        System.out.println("getEncryptionApplianceList.result=" + _getEncryptionApplianceList__return);


        }
        {
        System.out.println("Invoking getSiteList...");
        com.verimatrix.schemas.omitypes.SiteListQuery _getSiteList_siteListQuery = new com.verimatrix.schemas.omitypes.SiteListQuery();
        _getSiteList_siteListQuery.setSmsSiteId("SmsSiteId-50318411");
        com.verimatrix.schemas.omitypes.SiteEntityType _getSiteList_siteListQueryEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.RETAILER;
        _getSiteList_siteListQuery.setEntityType(_getSiteList_siteListQueryEntityType);
        _getSiteList_siteListQuery.setSiteCount(-1577399437);
        com.verimatrix.schemas.omitypes.SessionHandle _getSiteList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getSiteList_sessionHandle.setHandle("Handle80382569");
        com.verimatrix.schemas.omitypes.SiteListResult _getSiteList__return = port.getSiteList(_getSiteList_siteListQuery, _getSiteList_sessionHandle);
        System.out.println("getSiteList.result=" + _getSiteList__return);


        }
        {
        System.out.println("Invoking getGroupLicenseData...");
        com.verimatrix.schemas.omitypes.GroupLicenseDataQuery _getGroupLicenseData_groupLicenseDataQuery = new com.verimatrix.schemas.omitypes.GroupLicenseDataQuery();
        _getGroupLicenseData_groupLicenseDataQuery.setSmsNetworkId("SmsNetworkId-1687854941");
        com.verimatrix.schemas.omitypes.SessionHandle _getGroupLicenseData_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getGroupLicenseData_sessionHandle.setHandle("Handle427404823");
        com.verimatrix.schemas.omitypes.GroupLicenseDataResult _getGroupLicenseData__return = port.getGroupLicenseData(_getGroupLicenseData_groupLicenseDataQuery, _getGroupLicenseData_sessionHandle);
        System.out.println("getGroupLicenseData.result=" + _getGroupLicenseData__return);


        }
        {
        System.out.println("Invoking modifyNetwork...");
        com.verimatrix.schemas.omitypes.Network _modifyNetwork_network = new com.verimatrix.schemas.omitypes.Network();
        _modifyNetwork_network.setSmsNetworkId("SmsNetworkId-106041711");
        com.verimatrix.schemas.omitypes.NetworkType _modifyNetwork_networkNetworkType = com.verimatrix.schemas.omitypes.NetworkType.IPTV;
        _modifyNetwork_network.setNetworkType(_modifyNetwork_networkNetworkType);
        com.verimatrix.schemas.omitypes.Connection _modifyNetwork_networkConnection = new com.verimatrix.schemas.omitypes.Connection();
        _modifyNetwork_networkConnection.setUri("Uri-1770791398");
        _modifyNetwork_networkConnection.setAuthId("AuthId-879534731");
        _modifyNetwork_networkConnection.setAuthPassword("AuthPassword2143408969");
        _modifyNetwork_networkConnection.setTimeout(Integer.valueOf(1225401348));
        _modifyNetwork_networkConnection.setRetryCount(Integer.valueOf(902226520));
        _modifyNetwork_networkConnection.setRetryInterval(Integer.valueOf(-205141357));
        _modifyNetwork_networkConnection.setKeepAlive(Boolean.valueOf(false));
        _modifyNetwork_network.setConnection(_modifyNetwork_networkConnection);
        com.verimatrix.schemas.omitypes.SessionHandle _modifyNetwork_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifyNetwork_sessionHandle.setHandle("Handle-975560522");
        com.verimatrix.schemas.omitypes.Result _modifyNetwork__return = port.modifyNetwork(_modifyNetwork_network, _modifyNetwork_sessionHandle);
        System.out.println("modifyNetwork.result=" + _modifyNetwork__return);


        }
        {
        System.out.println("Invoking getLicenseGroups...");
        com.verimatrix.schemas.omitypes.LicenseGroupsQuery _getLicenseGroups_licenseGroupsQuery = new com.verimatrix.schemas.omitypes.LicenseGroupsQuery();
        _getLicenseGroups_licenseGroupsQuery.setSmsNetworkId("SmsNetworkId-1643386935");
        com.verimatrix.schemas.omitypes.SessionHandle _getLicenseGroups_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getLicenseGroups_sessionHandle.setHandle("Handle-73219837");
        com.verimatrix.schemas.omitypes.LicenseGroupsResult _getLicenseGroups__return = port.getLicenseGroups(_getLicenseGroups_licenseGroupsQuery, _getLicenseGroups_sessionHandle);
        System.out.println("getLicenseGroups.result=" + _getLicenseGroups__return);


        }
        {
        System.out.println("Invoking getDeviceTypeLicenseData...");
        com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataQuery _getDeviceTypeLicenseData_deviceTypeLicenseDataQuery = new com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataQuery();
        _getDeviceTypeLicenseData_deviceTypeLicenseDataQuery.setSmsNetworkId("SmsNetworkId-1667223312");
        com.verimatrix.schemas.omitypes.SessionHandle _getDeviceTypeLicenseData_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDeviceTypeLicenseData_sessionHandle.setHandle("Handle-1197794281");
        com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult _getDeviceTypeLicenseData__return = port.getDeviceTypeLicenseData(_getDeviceTypeLicenseData_deviceTypeLicenseDataQuery, _getDeviceTypeLicenseData_sessionHandle);
        System.out.println("getDeviceTypeLicenseData.result=" + _getDeviceTypeLicenseData__return);


        }
        {
        System.out.println("Invoking getNetworkContentList...");
        com.verimatrix.schemas.omitypes.NetworkContentQuery _getNetworkContentList_networkContentQuery = new com.verimatrix.schemas.omitypes.NetworkContentQuery();
        _getNetworkContentList_networkContentQuery.setSmsNetworkId("SmsNetworkId1629952425");
        _getNetworkContentList_networkContentQuery.setSmsContentId("SmsContentId-2060108964");
        _getNetworkContentList_networkContentQuery.setContentCount(-1096599934);
        com.verimatrix.schemas.omitypes.SessionHandle _getNetworkContentList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getNetworkContentList_sessionHandle.setHandle("Handle-1959312820");
        com.verimatrix.schemas.omitypes.NetworkContentResult _getNetworkContentList__return = port.getNetworkContentList(_getNetworkContentList_networkContentQuery, _getNetworkContentList_sessionHandle);
        System.out.println("getNetworkContentList.result=" + _getNetworkContentList__return);


        }
        {
        System.out.println("Invoking addSite...");
        com.verimatrix.schemas.omitypes.Site _addSite_site = new com.verimatrix.schemas.omitypes.Site();
        _addSite_site.setSmsSiteId("SmsSiteId2099209965");
        com.verimatrix.schemas.omitypes.SiteEntityType _addSite_siteEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.RETAILER;
        _addSite_site.setEntityType(_addSite_siteEntityType);
        _addSite_site.setName("Name-348670528");
        _addSite_site.setDescription("Description-329045930");
        _addSite_site.setSiteId("SiteId536764259");
        _addSite_site.setAuthPassword("AuthPassword949256438");
        com.verimatrix.schemas.omitypes.SessionHandle _addSite_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addSite_sessionHandle.setHandle("Handle-1031456867");
        com.verimatrix.schemas.omitypes.Result _addSite__return = port.addSite(_addSite_site, _addSite_sessionHandle);
        System.out.println("addSite.result=" + _addSite__return);


        }
        {
        System.out.println("Invoking getNetworkDeviceList...");
        com.verimatrix.schemas.omitypes.NetworkDeviceListQuery _getNetworkDeviceList_networkDeviceListQuery = new com.verimatrix.schemas.omitypes.NetworkDeviceListQuery();
        _getNetworkDeviceList_networkDeviceListQuery.setSmsNetworkId("SmsNetworkId-375605629");
        _getNetworkDeviceList_networkDeviceListQuery.setSmsDeviceId("SmsDeviceId2062434072");
        _getNetworkDeviceList_networkDeviceListQuery.setDeviceCount(-1946497422);
        com.verimatrix.schemas.omitypes.SessionHandle _getNetworkDeviceList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getNetworkDeviceList_sessionHandle.setHandle("Handle-802399978");
        com.verimatrix.schemas.omitypes.DeviceListResult _getNetworkDeviceList__return = port.getNetworkDeviceList(_getNetworkDeviceList_networkDeviceListQuery, _getNetworkDeviceList_sessionHandle);
        System.out.println("getNetworkDeviceList.result=" + _getNetworkDeviceList__return);


        }
        {
        System.out.println("Invoking getSite...");
        com.verimatrix.schemas.omitypes.SiteQuery _getSite_siteQuery = new com.verimatrix.schemas.omitypes.SiteQuery();
        _getSite_siteQuery.setSmsSiteId("SmsSiteId2047460902");
        com.verimatrix.schemas.omitypes.SiteEntityType _getSite_siteQueryEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.RETAILER;
        _getSite_siteQuery.setEntityType(_getSite_siteQueryEntityType);
        com.verimatrix.schemas.omitypes.SessionHandle _getSite_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getSite_sessionHandle.setHandle("Handle695733432");
        com.verimatrix.schemas.omitypes.SiteResult _getSite__return = port.getSite(_getSite_siteQuery, _getSite_sessionHandle);
        System.out.println("getSite.result=" + _getSite__return);


        }
        {
        System.out.println("Invoking removeNetwork...");
        com.verimatrix.schemas.omitypes.Network _removeNetwork_network = new com.verimatrix.schemas.omitypes.Network();
        _removeNetwork_network.setSmsNetworkId("SmsNetworkId947002230");
        com.verimatrix.schemas.omitypes.NetworkType _removeNetwork_networkNetworkType = com.verimatrix.schemas.omitypes.NetworkType.IPTV;
        _removeNetwork_network.setNetworkType(_removeNetwork_networkNetworkType);
        com.verimatrix.schemas.omitypes.Connection _removeNetwork_networkConnection = new com.verimatrix.schemas.omitypes.Connection();
        _removeNetwork_networkConnection.setUri("Uri-591402564");
        _removeNetwork_networkConnection.setAuthId("AuthId249750691");
        _removeNetwork_networkConnection.setAuthPassword("AuthPassword-1298565931");
        _removeNetwork_networkConnection.setTimeout(Integer.valueOf(-1874985693));
        _removeNetwork_networkConnection.setRetryCount(Integer.valueOf(2008745984));
        _removeNetwork_networkConnection.setRetryInterval(Integer.valueOf(-428734642));
        _removeNetwork_networkConnection.setKeepAlive(Boolean.valueOf(true));
        _removeNetwork_network.setConnection(_removeNetwork_networkConnection);
        com.verimatrix.schemas.omitypes.SessionHandle _removeNetwork_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeNetwork_sessionHandle.setHandle("Handle988394758");
        com.verimatrix.schemas.omitypes.Result _removeNetwork__return = port.removeNetwork(_removeNetwork_network, _removeNetwork_sessionHandle);
        System.out.println("removeNetwork.result=" + _removeNetwork__return);


        }
        {
        System.out.println("Invoking getNetworkList...");
        com.verimatrix.schemas.omitypes.SessionHandle _getNetworkList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getNetworkList_sessionHandle.setHandle("Handle-1562194254");
        com.verimatrix.schemas.omitypes.NetworkListResult _getNetworkList__return = port.getNetworkList(_getNetworkList_sessionHandle);
        System.out.println("getNetworkList.result=" + _getNetworkList__return);


        }
        {
        System.out.println("Invoking removeSite...");
        com.verimatrix.schemas.omitypes.Site _removeSite_site = new com.verimatrix.schemas.omitypes.Site();
        _removeSite_site.setSmsSiteId("SmsSiteId319974565");
        com.verimatrix.schemas.omitypes.SiteEntityType _removeSite_siteEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.WHOLESALER;
        _removeSite_site.setEntityType(_removeSite_siteEntityType);
        _removeSite_site.setName("Name201453978");
        _removeSite_site.setDescription("Description957000883");
        _removeSite_site.setSiteId("SiteId281700152");
        _removeSite_site.setAuthPassword("AuthPassword1059434997");
        com.verimatrix.schemas.omitypes.SessionHandle _removeSite_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeSite_sessionHandle.setHandle("Handle1823979663");
        com.verimatrix.schemas.omitypes.Result _removeSite__return = port.removeSite(_removeSite_site, _removeSite_sessionHandle);
        System.out.println("removeSite.result=" + _removeSite__return);


        }
        {
        System.out.println("Invoking getEncryptionApplianceConfiguration...");
        com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationQuery _getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQuery = new com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationQuery();
        _getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQuery.setSmsNetworkId("SmsNetworkId-938595145");
        _getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQuery.setApplianceId("ApplianceId-1810259630");
        com.verimatrix.schemas.omitypes.ContentType _getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQueryContentType = com.verimatrix.schemas.omitypes.ContentType.VOD;
        _getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQuery.setContentType(_getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQueryContentType);
        com.verimatrix.schemas.omitypes.SessionHandle _getEncryptionApplianceConfiguration_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getEncryptionApplianceConfiguration_sessionHandle.setHandle("Handle-739883249");
        com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationResult _getEncryptionApplianceConfiguration__return = port.getEncryptionApplianceConfiguration(_getEncryptionApplianceConfiguration_encryptionApplianceConfigurationQuery, _getEncryptionApplianceConfiguration_sessionHandle);
        System.out.println("getEncryptionApplianceConfiguration.result=" + _getEncryptionApplianceConfiguration__return);


        }
        {
        System.out.println("Invoking addNetwork...");
        com.verimatrix.schemas.omitypes.Network _addNetwork_network = new com.verimatrix.schemas.omitypes.Network();
        _addNetwork_network.setSmsNetworkId("SmsNetworkId-465947536");
        com.verimatrix.schemas.omitypes.NetworkType _addNetwork_networkNetworkType = com.verimatrix.schemas.omitypes.NetworkType.IPTV;
        _addNetwork_network.setNetworkType(_addNetwork_networkNetworkType);
        com.verimatrix.schemas.omitypes.Connection _addNetwork_networkConnection = new com.verimatrix.schemas.omitypes.Connection();
        _addNetwork_networkConnection.setUri("Uri-1038327668");
        _addNetwork_networkConnection.setAuthId("AuthId1597785652");
        _addNetwork_networkConnection.setAuthPassword("AuthPassword1458082282");
        _addNetwork_networkConnection.setTimeout(Integer.valueOf(1072784152));
        _addNetwork_networkConnection.setRetryCount(Integer.valueOf(-72902267));
        _addNetwork_networkConnection.setRetryInterval(Integer.valueOf(962548409));
        _addNetwork_networkConnection.setKeepAlive(Boolean.valueOf(true));
        _addNetwork_network.setConnection(_addNetwork_networkConnection);
        com.verimatrix.schemas.omitypes.SessionHandle _addNetwork_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addNetwork_sessionHandle.setHandle("Handle573828394");
        com.verimatrix.schemas.omitypes.Result _addNetwork__return = port.addNetwork(_addNetwork_network, _addNetwork_sessionHandle);
        System.out.println("addNetwork.result=" + _addNetwork__return);


        }

        System.exit(0);
    }

}
