
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.verimatrix.omi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.759+09:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "ConfigurationMgmtService",
                      portName = "ConfigurationMgmt",
                      targetNamespace = "http://www.verimatrix.com/omi",
                      wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                      endpointInterface = "com.verimatrix.omi.ConfigurationMgmt")
                      
public class ConfigurationMgmtImpl implements ConfigurationMgmt {

    private static final Logger LOG = Logger.getLogger(ConfigurationMgmtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#modifySite(com.verimatrix.schemas.omitypes.Site  site ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result modifySite(com.verimatrix.schemas.omitypes.Site site,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifySite");
        System.out.println(site);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId1440130081");
            _return.setResultCode(-1735550643);
            _return.setResultText("ResultText-1140058648");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1868102169");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getEncryptionApplianceList(com.verimatrix.schemas.omitypes.EncryptionApplianceQuery  encryptionApplianceQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.EncryptionApplianceResult getEncryptionApplianceList(com.verimatrix.schemas.omitypes.EncryptionApplianceQuery encryptionApplianceQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getEncryptionApplianceList");
        System.out.println(encryptionApplianceQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.EncryptionApplianceResult _return = new com.verimatrix.schemas.omitypes.EncryptionApplianceResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId737787592");
            _returnResult.setResultCode(-1474458339);
            _returnResult.setResultText("ResultText-1220419117");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1747228344");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.EncryptionAppliance> _returnAppliances = new java.util.ArrayList<com.verimatrix.schemas.omitypes.EncryptionAppliance>();
            com.verimatrix.schemas.omitypes.EncryptionAppliance _returnAppliancesVal1 = new com.verimatrix.schemas.omitypes.EncryptionAppliance();
            _returnAppliancesVal1.setApplianceId("ApplianceId-1000508520");
            com.verimatrix.schemas.omitypes.ContentType _returnAppliancesVal1NetworkContentType = com.verimatrix.schemas.omitypes.ContentType.VOD;
            _returnAppliancesVal1.setNetworkContentType(_returnAppliancesVal1NetworkContentType);
            _returnAppliancesVal1.setDescription("Description650804660");
            _returnAppliances.add(_returnAppliancesVal1);
            _return.getAppliances().addAll(_returnAppliances);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getSiteList(com.verimatrix.schemas.omitypes.SiteListQuery  siteListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.SiteListResult getSiteList(com.verimatrix.schemas.omitypes.SiteListQuery siteListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getSiteList");
        System.out.println(siteListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.SiteListResult _return = new com.verimatrix.schemas.omitypes.SiteListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-831934590");
            _returnResult.setResultCode(1476575186);
            _returnResult.setResultText("ResultText18823616");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1579563931");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Site> _returnSites = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Site>();
            com.verimatrix.schemas.omitypes.Site _returnSitesVal1 = new com.verimatrix.schemas.omitypes.Site();
            _returnSitesVal1.setSmsSiteId("SmsSiteId-123118632");
            com.verimatrix.schemas.omitypes.SiteEntityType _returnSitesVal1EntityType = com.verimatrix.schemas.omitypes.SiteEntityType.WHOLESALER;
            _returnSitesVal1.setEntityType(_returnSitesVal1EntityType);
            _returnSitesVal1.setName("Name741036226");
            _returnSitesVal1.setDescription("Description1804056138");
            _returnSitesVal1.setSiteId("SiteId654077860");
            _returnSitesVal1.setAuthPassword("AuthPassword1709715467");
            _returnSites.add(_returnSitesVal1);
            _return.getSites().addAll(_returnSites);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getGroupLicenseData(com.verimatrix.schemas.omitypes.GroupLicenseDataQuery  groupLicenseDataQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.GroupLicenseDataResult getGroupLicenseData(com.verimatrix.schemas.omitypes.GroupLicenseDataQuery groupLicenseDataQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getGroupLicenseData");
        System.out.println(groupLicenseDataQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.GroupLicenseDataResult _return = new com.verimatrix.schemas.omitypes.GroupLicenseDataResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId745196729");
            _returnResult.setResultCode(-318832000);
            _returnResult.setResultText("ResultText517246330");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1024697451");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.GroupLicenseData> _returnLicenseData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.GroupLicenseData>();
            com.verimatrix.schemas.omitypes.GroupLicenseData _returnLicenseDataVal1 = new com.verimatrix.schemas.omitypes.GroupLicenseData();
            com.verimatrix.schemas.omitypes.GroupData _returnLicenseDataVal1GroupData = new com.verimatrix.schemas.omitypes.GroupData();
            _returnLicenseDataVal1GroupData.setGroupId("GroupId246457807");
            _returnLicenseDataVal1GroupData.setDescription("Description-663851177");
            _returnLicenseDataVal1.setGroupData(_returnLicenseDataVal1GroupData);
            com.verimatrix.schemas.omitypes.LicenseData _returnLicenseDataVal1LicenseData = new com.verimatrix.schemas.omitypes.LicenseData();
            _returnLicenseDataVal1LicenseData.setLowerBounds(38054541);
            _returnLicenseDataVal1LicenseData.setUpperBounds(1363467138);
            _returnLicenseDataVal1LicenseData.setLimit(1804395927);
            _returnLicenseDataVal1LicenseData.setActiveCount(-255601154);
            _returnLicenseDataVal1.setLicenseData(_returnLicenseDataVal1LicenseData);
            _returnLicenseData.add(_returnLicenseDataVal1);
            _return.getLicenseData().addAll(_returnLicenseData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#modifyNetwork(com.verimatrix.schemas.omitypes.Network  network ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result modifyNetwork(com.verimatrix.schemas.omitypes.Network network,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifyNetwork");
        System.out.println(network);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId2058482257");
            _return.setResultCode(2144283605);
            _return.setResultText("ResultText-2143392432");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1620138628");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getLicenseGroups(com.verimatrix.schemas.omitypes.LicenseGroupsQuery  licenseGroupsQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.LicenseGroupsResult getLicenseGroups(com.verimatrix.schemas.omitypes.LicenseGroupsQuery licenseGroupsQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getLicenseGroups");
        System.out.println(licenseGroupsQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.LicenseGroupsResult _return = new com.verimatrix.schemas.omitypes.LicenseGroupsResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1891843998");
            _returnResult.setResultCode(-1574853031);
            _returnResult.setResultText("ResultText1057250409");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id47390951");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.LicenseGroup> _returnGroups = new java.util.ArrayList<com.verimatrix.schemas.omitypes.LicenseGroup>();
            com.verimatrix.schemas.omitypes.LicenseGroup _returnGroupsVal1 = new com.verimatrix.schemas.omitypes.LicenseGroup();
            com.verimatrix.schemas.omitypes.GroupData _returnGroupsVal1GroupData = new com.verimatrix.schemas.omitypes.GroupData();
            _returnGroupsVal1GroupData.setGroupId("GroupId-979053405");
            _returnGroupsVal1GroupData.setDescription("Description1102974453");
            _returnGroupsVal1.setGroupData(_returnGroupsVal1GroupData);
            java.util.List<com.verimatrix.schemas.omitypes.DeviceTypeData> _returnGroupsVal1DeviceTypeData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DeviceTypeData>();
            _returnGroupsVal1.getDeviceTypeData().addAll(_returnGroupsVal1DeviceTypeData);
            _returnGroups.add(_returnGroupsVal1);
            _return.getGroups().addAll(_returnGroups);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getDeviceTypeLicenseData(com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataQuery  deviceTypeLicenseDataQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult getDeviceTypeLicenseData(com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataQuery deviceTypeLicenseDataQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getDeviceTypeLicenseData");
        System.out.println(deviceTypeLicenseDataQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult _return = new com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1807688888");
            _returnResult.setResultCode(-2064200497);
            _returnResult.setResultText("ResultText-1292229206");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id1116797764");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.DeviceTypeLicenseData> _returnLicenseData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DeviceTypeLicenseData>();
            com.verimatrix.schemas.omitypes.DeviceTypeLicenseData _returnLicenseDataVal1 = new com.verimatrix.schemas.omitypes.DeviceTypeLicenseData();
            com.verimatrix.schemas.omitypes.DeviceTypeData _returnLicenseDataVal1DeviceTypeData = new com.verimatrix.schemas.omitypes.DeviceTypeData();
            com.verimatrix.schemas.omitypes.DeviceType _returnLicenseDataVal1DeviceTypeDataDeviceType = com.verimatrix.schemas.omitypes.DeviceType.WEB_MAC;
            _returnLicenseDataVal1DeviceTypeData.setDeviceType(_returnLicenseDataVal1DeviceTypeDataDeviceType);
            _returnLicenseDataVal1DeviceTypeData.setDescription("Description-1786658822");
            _returnLicenseDataVal1.setDeviceTypeData(_returnLicenseDataVal1DeviceTypeData);
            com.verimatrix.schemas.omitypes.LicenseData _returnLicenseDataVal1LicenseData = new com.verimatrix.schemas.omitypes.LicenseData();
            _returnLicenseDataVal1LicenseData.setLowerBounds(-627182245);
            _returnLicenseDataVal1LicenseData.setUpperBounds(237174373);
            _returnLicenseDataVal1LicenseData.setLimit(1967928574);
            _returnLicenseDataVal1LicenseData.setActiveCount(196594518);
            _returnLicenseDataVal1.setLicenseData(_returnLicenseDataVal1LicenseData);
            _returnLicenseData.add(_returnLicenseDataVal1);
            _return.getLicenseData().addAll(_returnLicenseData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getNetworkContentList(com.verimatrix.schemas.omitypes.NetworkContentQuery  networkContentQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.NetworkContentResult getNetworkContentList(com.verimatrix.schemas.omitypes.NetworkContentQuery networkContentQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getNetworkContentList");
        System.out.println(networkContentQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.NetworkContentResult _return = new com.verimatrix.schemas.omitypes.NetworkContentResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1406268462");
            _returnResult.setResultCode(165251599);
            _returnResult.setResultText("ResultText1984772551");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id1741139243");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.NetworkContent> _returnNetworkContent = new java.util.ArrayList<com.verimatrix.schemas.omitypes.NetworkContent>();
            com.verimatrix.schemas.omitypes.NetworkContent _returnNetworkContentVal1 = new com.verimatrix.schemas.omitypes.NetworkContent();
            _returnNetworkContentVal1.setSmsNetworkId("SmsNetworkId-970048378");
            _returnNetworkContentVal1.setSmsContentId("SmsContentId1005779943");
            _returnNetworkContentVal1.setNetworkContentId("NetworkContentId-408144514");
            com.verimatrix.schemas.omitypes.ContentType _returnNetworkContentVal1NetworkContentType = com.verimatrix.schemas.omitypes.ContentType.VOD;
            _returnNetworkContentVal1.setNetworkContentType(_returnNetworkContentVal1NetworkContentType);
            _returnNetworkContentVal1.setRatingLevel(Integer.valueOf(-371025494));
            com.verimatrix.schemas.omitypes.FingerprintMessage _returnNetworkContentVal1FingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
            java.util.List<com.verimatrix.schemas.omitypes.MessageText> _returnNetworkContentVal1FingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
            _returnNetworkContentVal1FingerprintMessage.getText().addAll(_returnNetworkContentVal1FingerprintMessageText);
            _returnNetworkContentVal1.setFingerprintMessage(_returnNetworkContentVal1FingerprintMessage);
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes _returnNetworkContentVal1EncryptionAttributes = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes();
            com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setName("Name1103779349");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTag1("Tag1-520082552");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTag2("Tag2-313855457");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTag3("Tag31997470166");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setFileName("FileName2107932180");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setFileSize("FileSize868975126");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setFileType("FileType1013427947");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTargetPath("TargetPath-361319450");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcCGMSA(-1542318903);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcACP(280427179);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(false);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcHDCP(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setDescription("Description-569492521");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.RC_4;
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setPcrCorrection(false);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(-702917217);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(1857281073);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setVideoMark(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(1881771748);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(-420986384);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1EncryptionAttributes.setVodEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes);
            com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setApplianceName("ApplianceName951210786");
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setInputURL("InputURL-583612783");
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setOutputURL("OutputURL-296912689");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcCGMSA(938680677);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcACP(311975214);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(true);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcHDCP(false);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.OSDAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes = new com.verimatrix.schemas.iptvtypes.OSDAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdActive(true);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdDuration(-2096779769);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdType(1738794752);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdLocation(-635203880);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setOsdAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setDescription("Description458295061");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.AES;
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setPcrCorrection(true);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(1934118373);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(45792837);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setVideoMark(true);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(false);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(1296926974);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(-1300956159);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1EncryptionAttributes.setDtvEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes);
            _returnNetworkContentVal1.setEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributes);
            com.verimatrix.schemas.omitypes.EncryptionParameters _returnNetworkContentVal1EncryptionParameters = new com.verimatrix.schemas.omitypes.EncryptionParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnNetworkContentVal1EncryptionParametersEncryptionParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnNetworkContentVal1EncryptionParameters.getEncryptionParameter().addAll(_returnNetworkContentVal1EncryptionParametersEncryptionParameter);
            _returnNetworkContentVal1.setEncryptionParameters(_returnNetworkContentVal1EncryptionParameters);
            _returnNetworkContent.add(_returnNetworkContentVal1);
            _return.getNetworkContent().addAll(_returnNetworkContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#addSite(com.verimatrix.schemas.omitypes.Site  site ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result addSite(com.verimatrix.schemas.omitypes.Site site,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addSite");
        System.out.println(site);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-959981655");
            _return.setResultCode(564332380);
            _return.setResultText("ResultText-299912243");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1589893723");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getNetworkDeviceList(com.verimatrix.schemas.omitypes.NetworkDeviceListQuery  networkDeviceListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DeviceListResult getNetworkDeviceList(com.verimatrix.schemas.omitypes.NetworkDeviceListQuery networkDeviceListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getNetworkDeviceList");
        System.out.println(networkDeviceListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DeviceListResult _return = new com.verimatrix.schemas.omitypes.DeviceListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-721250837");
            _returnResult.setResultCode(1212158683);
            _returnResult.setResultText("ResultText-2043907864");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id236628350");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Device> _returnDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
            com.verimatrix.schemas.omitypes.Device _returnDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
            _returnDevicesVal1.setSmsDeviceId("SmsDeviceId463384497");
            _returnDevicesVal1.setSmsNetworkId("SmsNetworkId-1744785422");
            com.verimatrix.schemas.omitypes.DeviceType _returnDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.WEB_ANDROID;
            _returnDevicesVal1.setDeviceType(_returnDevicesVal1DeviceType);
            _returnDevicesVal1.setNetworkDeviceId("NetworkDeviceId-388885343");
            byte[] _returnDevicesVal1SmsAuthenticator = new byte[] {};
            _returnDevicesVal1.setSmsAuthenticator(_returnDevicesVal1SmsAuthenticator);
            _returnDevices.add(_returnDevicesVal1);
            _return.getDevices().addAll(_returnDevices);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getSite(com.verimatrix.schemas.omitypes.SiteQuery  siteQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.SiteResult getSite(com.verimatrix.schemas.omitypes.SiteQuery siteQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getSite");
        System.out.println(siteQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.SiteResult _return = new com.verimatrix.schemas.omitypes.SiteResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId435654773");
            _returnResult.setResultCode(-1695942749);
            _returnResult.setResultText("ResultText-1519480541");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1939918344");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.Site _returnSite = new com.verimatrix.schemas.omitypes.Site();
            _returnSite.setSmsSiteId("SmsSiteId-621139787");
            com.verimatrix.schemas.omitypes.SiteEntityType _returnSiteEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.RETAILER;
            _returnSite.setEntityType(_returnSiteEntityType);
            _returnSite.setName("Name567567645");
            _returnSite.setDescription("Description-860322147");
            _returnSite.setSiteId("SiteId1751340466");
            _returnSite.setAuthPassword("AuthPassword-592349614");
            _return.setSite(_returnSite);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#removeNetwork(com.verimatrix.schemas.omitypes.Network  network ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result removeNetwork(com.verimatrix.schemas.omitypes.Network network,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeNetwork");
        System.out.println(network);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-268882529");
            _return.setResultCode(-83378326);
            _return.setResultText("ResultText-1944682125");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-766594709");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getNetworkList(com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.NetworkListResult getNetworkList(com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getNetworkList");
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.NetworkListResult _return = new com.verimatrix.schemas.omitypes.NetworkListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId1517896325");
            _returnResult.setResultCode(513008592);
            _returnResult.setResultText("ResultText686800656");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1485604359");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Network> _returnNetworks = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Network>();
            com.verimatrix.schemas.omitypes.Network _returnNetworksVal1 = new com.verimatrix.schemas.omitypes.Network();
            _returnNetworksVal1.setSmsNetworkId("SmsNetworkId-1574908880");
            com.verimatrix.schemas.omitypes.NetworkType _returnNetworksVal1NetworkType = com.verimatrix.schemas.omitypes.NetworkType.PLAYREADY;
            _returnNetworksVal1.setNetworkType(_returnNetworksVal1NetworkType);
            com.verimatrix.schemas.omitypes.Connection _returnNetworksVal1Connection = new com.verimatrix.schemas.omitypes.Connection();
            _returnNetworksVal1Connection.setUri("Uri-1864046804");
            _returnNetworksVal1Connection.setAuthId("AuthId-142642417");
            _returnNetworksVal1Connection.setAuthPassword("AuthPassword505257386");
            _returnNetworksVal1Connection.setTimeout(Integer.valueOf(-1648736313));
            _returnNetworksVal1Connection.setRetryCount(Integer.valueOf(-914523966));
            _returnNetworksVal1Connection.setRetryInterval(Integer.valueOf(1399898908));
            _returnNetworksVal1Connection.setKeepAlive(Boolean.valueOf(false));
            _returnNetworksVal1.setConnection(_returnNetworksVal1Connection);
            _returnNetworks.add(_returnNetworksVal1);
            _return.getNetworks().addAll(_returnNetworks);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#removeSite(com.verimatrix.schemas.omitypes.Site  site ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result removeSite(com.verimatrix.schemas.omitypes.Site site,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeSite");
        System.out.println(site);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-1872085483");
            _return.setResultCode(1373717029);
            _return.setResultText("ResultText162243237");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-753766874");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#getEncryptionApplianceConfiguration(com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationQuery  encryptionApplianceConfigurationQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationResult getEncryptionApplianceConfiguration(com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationQuery encryptionApplianceConfigurationQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getEncryptionApplianceConfiguration");
        System.out.println(encryptionApplianceConfigurationQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationResult _return = new com.verimatrix.schemas.omitypes.EncryptionApplianceConfigurationResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId586094560");
            _returnResult.setResultCode(-1556474303);
            _returnResult.setResultText("ResultText-1423990220");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1064496299");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            _return.setRatingLevel(Integer.valueOf(-1965290579));
            com.verimatrix.schemas.omitypes.EncryptionApplianceConfiguration _returnApplianceConfiguration = new com.verimatrix.schemas.omitypes.EncryptionApplianceConfiguration();
            com.verimatrix.schemas.iptvtypes.VODEncryptionConfiguration _returnApplianceConfigurationVodEncryptionConfiguration = new com.verimatrix.schemas.iptvtypes.VODEncryptionConfiguration();
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setDescription("Description-1121643994");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.AES;
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setEncryptionMode(_returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributesEncryptionMode);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setPcrCorrection(false);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setKeyMutationInterval(109767120);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setKeyInsertionInterval(-793495865);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setVideoMark(true);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setControlWordPathProtection(false);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setVideoEncryptionLevel(-1264589827);
            _returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes.setAudioEncryptionLevel(-1119266050);
            _returnApplianceConfigurationVodEncryptionConfiguration.setEncryptionAttributes(_returnApplianceConfigurationVodEncryptionConfigurationEncryptionAttributes);
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnApplianceConfigurationVodEncryptionConfigurationCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnApplianceConfigurationVodEncryptionConfigurationCopyControlAttributes.setCcCGMSA(-1227127067);
            _returnApplianceConfigurationVodEncryptionConfigurationCopyControlAttributes.setCcACP(-480260161);
            _returnApplianceConfigurationVodEncryptionConfigurationCopyControlAttributes.setCcDwightCavendish(true);
            _returnApplianceConfigurationVodEncryptionConfigurationCopyControlAttributes.setCcHDCP(false);
            _returnApplianceConfigurationVodEncryptionConfiguration.setCopyControlAttributes(_returnApplianceConfigurationVodEncryptionConfigurationCopyControlAttributes);
            _returnApplianceConfiguration.setVodEncryptionConfiguration(_returnApplianceConfigurationVodEncryptionConfiguration);
            com.verimatrix.schemas.iptvtypes.DTVEncryptionConfiguration _returnApplianceConfigurationDtvEncryptionConfiguration = new com.verimatrix.schemas.iptvtypes.DTVEncryptionConfiguration();
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setDescription("Description184894184");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.RC_4;
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setEncryptionMode(_returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributesEncryptionMode);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setPcrCorrection(false);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setKeyMutationInterval(-1930845956);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setKeyInsertionInterval(1391156721);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setVideoMark(true);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setControlWordPathProtection(false);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setVideoEncryptionLevel(-834927705);
            _returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes.setAudioEncryptionLevel(-2092735558);
            _returnApplianceConfigurationDtvEncryptionConfiguration.setEncryptionAttributes(_returnApplianceConfigurationDtvEncryptionConfigurationEncryptionAttributes);
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnApplianceConfigurationDtvEncryptionConfigurationCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnApplianceConfigurationDtvEncryptionConfigurationCopyControlAttributes.setCcCGMSA(-443669608);
            _returnApplianceConfigurationDtvEncryptionConfigurationCopyControlAttributes.setCcACP(-778630947);
            _returnApplianceConfigurationDtvEncryptionConfigurationCopyControlAttributes.setCcDwightCavendish(true);
            _returnApplianceConfigurationDtvEncryptionConfigurationCopyControlAttributes.setCcHDCP(false);
            _returnApplianceConfigurationDtvEncryptionConfiguration.setCopyControlAttributes(_returnApplianceConfigurationDtvEncryptionConfigurationCopyControlAttributes);
            _returnApplianceConfiguration.setDtvEncryptionConfiguration(_returnApplianceConfigurationDtvEncryptionConfiguration);
            _return.setApplianceConfiguration(_returnApplianceConfiguration);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ConfigurationMgmt#addNetwork(com.verimatrix.schemas.omitypes.Network  network ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result addNetwork(com.verimatrix.schemas.omitypes.Network network,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addNetwork");
        System.out.println(network);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-495705104");
            _return.setResultCode(-847068906);
            _return.setResultText("ResultText-795979315");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-350683668");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
