
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.verimatrix.omi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.805+09:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "ContentMgmtService",
                      portName = "ContentMgmt",
                      targetNamespace = "http://www.verimatrix.com/omi",
                      wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                      endpointInterface = "com.verimatrix.omi.ContentMgmt")
                      
public class ContentMgmtImpl implements ContentMgmt {

    private static final Logger LOG = Logger.getLogger(ContentMgmtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#removeContent(com.verimatrix.schemas.omitypes.ContentList  contentList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeContent(com.verimatrix.schemas.omitypes.ContentList contentList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeContent");
        System.out.println(contentList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-1091670605");
            _returnResultVal1.setResultCode(310743023);
            _returnResultVal1.setResultText("ResultText-209477041");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#getContentOnNetwork(com.verimatrix.schemas.omitypes.ContentOnNetworkQuery  contentOnNetworkQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.NetworkContentResult getContentOnNetwork(com.verimatrix.schemas.omitypes.ContentOnNetworkQuery contentOnNetworkQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getContentOnNetwork");
        System.out.println(contentOnNetworkQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.NetworkContentResult _return = new com.verimatrix.schemas.omitypes.NetworkContentResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId2085393949");
            _returnResult.setResultCode(1593328342);
            _returnResult.setResultText("ResultText-555554438");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id2064744740");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.NetworkContent> _returnNetworkContent = new java.util.ArrayList<com.verimatrix.schemas.omitypes.NetworkContent>();
            com.verimatrix.schemas.omitypes.NetworkContent _returnNetworkContentVal1 = new com.verimatrix.schemas.omitypes.NetworkContent();
            _returnNetworkContentVal1.setSmsNetworkId("SmsNetworkId-944119476");
            _returnNetworkContentVal1.setSmsContentId("SmsContentId-2059483105");
            _returnNetworkContentVal1.setNetworkContentId("NetworkContentId461752991");
            com.verimatrix.schemas.omitypes.ContentType _returnNetworkContentVal1NetworkContentType = com.verimatrix.schemas.omitypes.ContentType.DTV;
            _returnNetworkContentVal1.setNetworkContentType(_returnNetworkContentVal1NetworkContentType);
            _returnNetworkContentVal1.setRatingLevel(Integer.valueOf(1172493279));
            com.verimatrix.schemas.omitypes.FingerprintMessage _returnNetworkContentVal1FingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
            java.util.List<com.verimatrix.schemas.omitypes.MessageText> _returnNetworkContentVal1FingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
            _returnNetworkContentVal1FingerprintMessage.getText().addAll(_returnNetworkContentVal1FingerprintMessageText);
            _returnNetworkContentVal1.setFingerprintMessage(_returnNetworkContentVal1FingerprintMessage);
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes _returnNetworkContentVal1EncryptionAttributes = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes();
            com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setName("Name1420952501");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTag1("Tag1666497736");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTag2("Tag21080526500");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTag3("Tag3-1022724634");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setFileName("FileName-1607074615");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setFileSize("FileSize-1617835977");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setFileType("FileType-2125359428");
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setTargetPath("TargetPath-546642771");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcCGMSA(667458043);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcACP(654565538);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcHDCP(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setDescription("Description1790738940");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.AES;
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setPcrCorrection(false);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(-497652881);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(1328472692);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setVideoMark(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(true);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(1148093143);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(551043365);
            _returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1EncryptionAttributes.setVodEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesVodEncryptionAttributes);
            com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setApplianceName("ApplianceName-766295125");
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setInputURL("InputURL-527559342");
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setOutputURL("OutputURL-1317469310");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcCGMSA(-1464419505);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcACP(-1876461516);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(false);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcHDCP(true);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.OSDAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes = new com.verimatrix.schemas.iptvtypes.OSDAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdActive(false);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdDuration(1853931428);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdType(385654419);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdLocation(1935366967);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setOsdAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesOsdAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setDescription("Description641879202");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.AES;
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setPcrCorrection(true);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(1031079751);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(-1918605882);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setVideoMark(false);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(false);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(1223106130);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(-1213865757);
            _returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1EncryptionAttributes.setDtvEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributesDtvEncryptionAttributes);
            _returnNetworkContentVal1.setEncryptionAttributes(_returnNetworkContentVal1EncryptionAttributes);
            com.verimatrix.schemas.omitypes.EncryptionParameters _returnNetworkContentVal1EncryptionParameters = new com.verimatrix.schemas.omitypes.EncryptionParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnNetworkContentVal1EncryptionParametersEncryptionParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnNetworkContentVal1EncryptionParameters.getEncryptionParameter().addAll(_returnNetworkContentVal1EncryptionParametersEncryptionParameter);
            _returnNetworkContentVal1.setEncryptionParameters(_returnNetworkContentVal1EncryptionParameters);
            _returnNetworkContent.add(_returnNetworkContentVal1);
            _return.getNetworkContent().addAll(_returnNetworkContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#getContentEvents(com.verimatrix.schemas.omitypes.ContentEventQuery  contentEventQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ContentEventResult getContentEvents(com.verimatrix.schemas.omitypes.ContentEventQuery contentEventQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getContentEvents");
        System.out.println(contentEventQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ContentEventResult _return = new com.verimatrix.schemas.omitypes.ContentEventResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1746620562");
            _returnResult.setResultCode(561358971);
            _returnResult.setResultText("ResultText161613442");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1748012466");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Event> _returnEvents = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
            com.verimatrix.schemas.omitypes.Event _returnEventsVal1 = new com.verimatrix.schemas.omitypes.Event();
            _returnEventsVal1.setSmsEventId("SmsEventId-1706909043");
            _returnEventsVal1.setSmsContentId("SmsContentId-1014396991");
            _returnEventsVal1.setSmsNetworkId("SmsNetworkId-2068467573");
            _returnEventsVal1.setExclusive(true);
            _returnEventsVal1.setPreStartDuration(1396983812);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEventsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEventsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.821+09:00"));
            _returnEventsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.821+09:00"));
            _returnEventsVal1.setTimePeriodRule(_returnEventsVal1TimePeriodRule);
            _returnEventsVal1.setRatingLevel(Integer.valueOf(-1842666844));
            com.verimatrix.schemas.omitypes.FingerprintMessage _returnEventsVal1FingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
            java.util.List<com.verimatrix.schemas.omitypes.MessageText> _returnEventsVal1FingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
            _returnEventsVal1FingerprintMessage.getText().addAll(_returnEventsVal1FingerprintMessageText);
            _returnEventsVal1.setFingerprintMessage(_returnEventsVal1FingerprintMessage);
            com.verimatrix.schemas.omitypes.EventParameters _returnEventsVal1EventParameters = new com.verimatrix.schemas.omitypes.EventParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEventsVal1EventParametersEventParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEventsVal1EventParameters.getEventParameter().addAll(_returnEventsVal1EventParametersEventParameter);
            _returnEventsVal1.setEventParameters(_returnEventsVal1EventParameters);
            _returnEvents.add(_returnEventsVal1);
            _return.getEvents().addAll(_returnEvents);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#removeEvents(com.verimatrix.schemas.omitypes.EventList  eventList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeEvents(com.verimatrix.schemas.omitypes.EventList eventList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeEvents");
        System.out.println(eventList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-2068746020");
            _returnResultVal1.setResultCode(-503425043);
            _returnResultVal1.setResultText("ResultText383979280");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#removeContentFromNetwork(com.verimatrix.schemas.omitypes.NetworkContent  networkContent ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result removeContentFromNetwork(com.verimatrix.schemas.omitypes.NetworkContent networkContent,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeContentFromNetwork");
        System.out.println(networkContent);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId168268511");
            _return.setResultCode(646690832);
            _return.setResultText("ResultText426765064");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-684405044");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#getContentList(com.verimatrix.schemas.omitypes.ContentListQuery  contentListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ContentListResult getContentList(com.verimatrix.schemas.omitypes.ContentListQuery contentListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getContentList");
        System.out.println(contentListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ContentListResult _return = new com.verimatrix.schemas.omitypes.ContentListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-664826730");
            _returnResult.setResultCode(-764911958);
            _returnResult.setResultText("ResultText1771423558");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-533341429");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Content> _returnContent = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Content>();
            com.verimatrix.schemas.omitypes.Content _returnContentVal1 = new com.verimatrix.schemas.omitypes.Content();
            _returnContentVal1.setSmsContentId("SmsContentId1782101142");
            _returnContentVal1.setDescription("Description97220610");
            _returnContentVal1.setTag("Tag-876994992");
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#addContent(com.verimatrix.schemas.omitypes.ContentList  contentList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addContent(com.verimatrix.schemas.omitypes.ContentList contentList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addContent");
        System.out.println(contentList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId1851724391");
            _returnResultVal1.setResultCode(760714977);
            _returnResultVal1.setResultText("ResultText1261559929");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#addEvents(com.verimatrix.schemas.omitypes.EventList  eventList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addEvents(com.verimatrix.schemas.omitypes.EventList eventList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addEvents");
        System.out.println(eventList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-1684809955");
            _returnResultVal1.setResultCode(356923801);
            _returnResultVal1.setResultText("ResultText1577320808");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#getNetworkContentTypeEncryptionStatus(com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionQuery  networkContentTypeEncryptionQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionResult getNetworkContentTypeEncryptionStatus(com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionQuery networkContentTypeEncryptionQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getNetworkContentTypeEncryptionStatus");
        System.out.println(networkContentTypeEncryptionQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionResult _return = new com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-454558989");
            _returnResult.setResultCode(-2116325296);
            _returnResult.setResultText("ResultText-795330549");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id1148307226");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionStatus> _returnNetworkContentTypeEncryptionStatus = new java.util.ArrayList<com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionStatus>();
            com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionStatus _returnNetworkContentTypeEncryptionStatusVal1 = new com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionStatus();
            _returnNetworkContentTypeEncryptionStatusVal1.setNetworkContentId("NetworkContentId1368019334");
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionStatus _returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatus = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionStatus();
            com.verimatrix.schemas.iptvtypes.VODEncryptionStatus _returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatusEncryptionStatus = new com.verimatrix.schemas.iptvtypes.VODEncryptionStatus();
            _returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatusEncryptionStatus.setStatusCode(-1386142498);
            _returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatusEncryptionStatus.setStatusText("StatusText916588971");
            _returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatusEncryptionStatus.setPercentComplete(-1983631587);
            _returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatus.setEncryptionStatus(_returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatusEncryptionStatus);
            _returnNetworkContentTypeEncryptionStatusVal1.setNetworkContentEncryptionStatus(_returnNetworkContentTypeEncryptionStatusVal1NetworkContentEncryptionStatus);
            com.verimatrix.schemas.omitypes.EncryptionStatus _returnNetworkContentTypeEncryptionStatusVal1EncryptionStatus = new com.verimatrix.schemas.omitypes.EncryptionStatus();
            _returnNetworkContentTypeEncryptionStatusVal1EncryptionStatus.setState("State522390894");
            _returnNetworkContentTypeEncryptionStatusVal1EncryptionStatus.setDescription("Description1565406963");
            _returnNetworkContentTypeEncryptionStatusVal1EncryptionStatus.setProgress(Integer.valueOf(-1047102974));
            _returnNetworkContentTypeEncryptionStatusVal1.setEncryptionStatus(_returnNetworkContentTypeEncryptionStatusVal1EncryptionStatus);
            _returnNetworkContentTypeEncryptionStatus.add(_returnNetworkContentTypeEncryptionStatusVal1);
            _return.getNetworkContentTypeEncryptionStatus().addAll(_returnNetworkContentTypeEncryptionStatus);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#modifyContentOnNetwork(com.verimatrix.schemas.omitypes.NetworkContent  networkContent ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result modifyContentOnNetwork(com.verimatrix.schemas.omitypes.NetworkContent networkContent,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifyContentOnNetwork");
        System.out.println(networkContent);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-549284774");
            _return.setResultCode(-376276412);
            _return.setResultText("ResultText628458774");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id17562756");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#getNetworkContentIdList(com.verimatrix.schemas.omitypes.NetworkContentIdQuery  networkContentIdQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.NetworkContentIdResult getNetworkContentIdList(com.verimatrix.schemas.omitypes.NetworkContentIdQuery networkContentIdQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getNetworkContentIdList");
        System.out.println(networkContentIdQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.NetworkContentIdResult _return = new com.verimatrix.schemas.omitypes.NetworkContentIdResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId1723398463");
            _returnResult.setResultCode(-1054865297);
            _returnResult.setResultText("ResultText-1120547446");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-787532247");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.NetworkContentIdData> _returnNetworkContent = new java.util.ArrayList<com.verimatrix.schemas.omitypes.NetworkContentIdData>();
            com.verimatrix.schemas.omitypes.NetworkContentIdData _returnNetworkContentVal1 = new com.verimatrix.schemas.omitypes.NetworkContentIdData();
            com.verimatrix.schemas.omitypes.NetworkContent _returnNetworkContentVal1NetworkContent = new com.verimatrix.schemas.omitypes.NetworkContent();
            _returnNetworkContentVal1NetworkContent.setSmsNetworkId("SmsNetworkId-110652481");
            _returnNetworkContentVal1NetworkContent.setSmsContentId("SmsContentId569672410");
            _returnNetworkContentVal1NetworkContent.setNetworkContentId("NetworkContentId-994950153");
            com.verimatrix.schemas.omitypes.ContentType _returnNetworkContentVal1NetworkContentNetworkContentType = com.verimatrix.schemas.omitypes.ContentType.DTV;
            _returnNetworkContentVal1NetworkContent.setNetworkContentType(_returnNetworkContentVal1NetworkContentNetworkContentType);
            _returnNetworkContentVal1NetworkContent.setRatingLevel(Integer.valueOf(-1349479011));
            com.verimatrix.schemas.omitypes.FingerprintMessage _returnNetworkContentVal1NetworkContentFingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
            java.util.List<com.verimatrix.schemas.omitypes.MessageText> _returnNetworkContentVal1NetworkContentFingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
            _returnNetworkContentVal1NetworkContentFingerprintMessage.getText().addAll(_returnNetworkContentVal1NetworkContentFingerprintMessageText);
            _returnNetworkContentVal1NetworkContent.setFingerprintMessage(_returnNetworkContentVal1NetworkContentFingerprintMessage);
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributes = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes();
            com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setName("Name-1542099993");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setTag1("Tag1-783524534");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setTag2("Tag21645759602");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setTag3("Tag3-2048674582");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setFileName("FileName1485092258");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setFileSize("FileSize2073294297");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setFileType("FileType-1819786691");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setTargetPath("TargetPath335231180");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcCGMSA(-1834530502);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcACP(-1265551927);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesCopyControlAttributes.setCcHDCP(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setDescription("Description-2008542804");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.RC_4;
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setPcrCorrection(true);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(-1535464799);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(-1783333440);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setVideoMark(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(-2103395671);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(432713017);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1NetworkContentEncryptionAttributes.setVodEncryptionAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesVodEncryptionAttributes);
            com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes.setApplianceName("ApplianceName-408895578");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes.setInputURL("InputURL-1673368975");
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes.setOutputURL("OutputURL-1679824200");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcCGMSA(1184939335);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcACP(1034338909);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesCopyControlAttributes.setCcHDCP(true);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.OSDAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesOsdAttributes = new com.verimatrix.schemas.iptvtypes.OSDAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdActive(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdDuration(197107059);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdType(-903997793);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesOsdAttributes.setOsdLocation(-1473714959);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes.setOsdAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesOsdAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setDescription("Description1810197647");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.RC_4;
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setPcrCorrection(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(-1356324879);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(-1767477524);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setVideoMark(true);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(false);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(-1733282323);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(871582669);
            _returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1NetworkContentEncryptionAttributes.setDtvEncryptionAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributesDtvEncryptionAttributes);
            _returnNetworkContentVal1NetworkContent.setEncryptionAttributes(_returnNetworkContentVal1NetworkContentEncryptionAttributes);
            com.verimatrix.schemas.omitypes.EncryptionParameters _returnNetworkContentVal1NetworkContentEncryptionParameters = new com.verimatrix.schemas.omitypes.EncryptionParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnNetworkContentVal1NetworkContentEncryptionParametersEncryptionParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnNetworkContentVal1NetworkContentEncryptionParameters.getEncryptionParameter().addAll(_returnNetworkContentVal1NetworkContentEncryptionParametersEncryptionParameter);
            _returnNetworkContentVal1NetworkContent.setEncryptionParameters(_returnNetworkContentVal1NetworkContentEncryptionParameters);
            _returnNetworkContentVal1.setNetworkContent(_returnNetworkContentVal1NetworkContent);
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes _returnNetworkContentVal1Attributes = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionAttributes();
            com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes _returnNetworkContentVal1AttributesVodEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.VODEncryptionAttributes();
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setName("Name-413367593");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setTag1("Tag1-1274784166");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setTag2("Tag2-1462648971");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setTag3("Tag3-1003877349");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setFileName("FileName252800214");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setFileSize("FileSize-1248961460");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setFileType("FileType1675689877");
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setTargetPath("TargetPath430895401");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1AttributesVodEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1AttributesVodEncryptionAttributesCopyControlAttributes.setCcCGMSA(1158267821);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesCopyControlAttributes.setCcACP(972201888);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(false);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesCopyControlAttributes.setCcHDCP(false);
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1AttributesVodEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setDescription("Description336798374");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.AES;
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setPcrCorrection(true);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(-586017985);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(871337224);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setVideoMark(false);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(true);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(1879371267);
            _returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(-626636865);
            _returnNetworkContentVal1AttributesVodEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1AttributesVodEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1Attributes.setVodEncryptionAttributes(_returnNetworkContentVal1AttributesVodEncryptionAttributes);
            com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes _returnNetworkContentVal1AttributesDtvEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.DTVEncryptionAttributes();
            _returnNetworkContentVal1AttributesDtvEncryptionAttributes.setApplianceName("ApplianceName1637126557");
            _returnNetworkContentVal1AttributesDtvEncryptionAttributes.setInputURL("InputURL2111932888");
            _returnNetworkContentVal1AttributesDtvEncryptionAttributes.setOutputURL("OutputURL29074338");
            com.verimatrix.schemas.iptvtypes.CopyControlAttributes _returnNetworkContentVal1AttributesDtvEncryptionAttributesCopyControlAttributes = new com.verimatrix.schemas.iptvtypes.CopyControlAttributes();
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesCopyControlAttributes.setCcCGMSA(-942266052);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesCopyControlAttributes.setCcACP(-1709773179);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesCopyControlAttributes.setCcDwightCavendish(true);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesCopyControlAttributes.setCcHDCP(true);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributes.setCopyControlAttributes(_returnNetworkContentVal1AttributesDtvEncryptionAttributesCopyControlAttributes);
            com.verimatrix.schemas.iptvtypes.OSDAttributes _returnNetworkContentVal1AttributesDtvEncryptionAttributesOsdAttributes = new com.verimatrix.schemas.iptvtypes.OSDAttributes();
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesOsdAttributes.setOsdActive(false);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesOsdAttributes.setOsdDuration(815914354);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesOsdAttributes.setOsdType(-2012380907);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesOsdAttributes.setOsdLocation(-193414828);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributes.setOsdAttributes(_returnNetworkContentVal1AttributesDtvEncryptionAttributesOsdAttributes);
            com.verimatrix.schemas.iptvtypes.EncryptionAttributes _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes = new com.verimatrix.schemas.iptvtypes.EncryptionAttributes();
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setDescription("Description-238940927");
            com.verimatrix.schemas.iptvtypes.EncryptionMode _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode = com.verimatrix.schemas.iptvtypes.EncryptionMode.AES;
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setEncryptionMode(_returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributesEncryptionMode);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setPcrCorrection(false);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setKeyMutationInterval(-2142193155);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setKeyInsertionInterval(189360719);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setVideoMark(false);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setControlWordPathProtection(true);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setVideoEncryptionLevel(1343245136);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes.setAudioEncryptionLevel(-1035911180);
            _returnNetworkContentVal1AttributesDtvEncryptionAttributes.setEncryptionAttributes(_returnNetworkContentVal1AttributesDtvEncryptionAttributesEncryptionAttributes);
            _returnNetworkContentVal1Attributes.setDtvEncryptionAttributes(_returnNetworkContentVal1AttributesDtvEncryptionAttributes);
            _returnNetworkContentVal1.setAttributes(_returnNetworkContentVal1Attributes);
            _returnNetworkContent.add(_returnNetworkContentVal1);
            _return.getNetworkContent().addAll(_returnNetworkContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#getNetworkContentEncryptionStatus(com.verimatrix.schemas.omitypes.NetworkContentEncryptionQuery  networkContentEncryptionQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.NetworkContentEncryptionResult getNetworkContentEncryptionStatus(com.verimatrix.schemas.omitypes.NetworkContentEncryptionQuery networkContentEncryptionQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getNetworkContentEncryptionStatus");
        System.out.println(networkContentEncryptionQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionResult _return = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId1067867920");
            _returnResult.setResultCode(-940707789);
            _returnResult.setResultText("ResultText-1415459739");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id879881501");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.NetworkContentEncryptionStatus _returnNetworkContentEncryptionStatus = new com.verimatrix.schemas.omitypes.NetworkContentEncryptionStatus();
            com.verimatrix.schemas.iptvtypes.VODEncryptionStatus _returnNetworkContentEncryptionStatusEncryptionStatus = new com.verimatrix.schemas.iptvtypes.VODEncryptionStatus();
            _returnNetworkContentEncryptionStatusEncryptionStatus.setStatusCode(-48765612);
            _returnNetworkContentEncryptionStatusEncryptionStatus.setStatusText("StatusText536398873");
            _returnNetworkContentEncryptionStatusEncryptionStatus.setPercentComplete(-1193559295);
            _returnNetworkContentEncryptionStatus.setEncryptionStatus(_returnNetworkContentEncryptionStatusEncryptionStatus);
            _return.setNetworkContentEncryptionStatus(_returnNetworkContentEncryptionStatus);
            com.verimatrix.schemas.omitypes.EncryptionStatus _returnEncryptionStatus = new com.verimatrix.schemas.omitypes.EncryptionStatus();
            _returnEncryptionStatus.setState("State-1546824428");
            _returnEncryptionStatus.setDescription("Description-755083792");
            _returnEncryptionStatus.setProgress(Integer.valueOf(-2018726817));
            _return.setEncryptionStatus(_returnEncryptionStatus);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.ContentMgmt#addContentToNetwork(com.verimatrix.schemas.omitypes.NetworkContent  networkContent ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result addContentToNetwork(com.verimatrix.schemas.omitypes.NetworkContent networkContent,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addContentToNetwork");
        System.out.println(networkContent);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId1988405068");
            _return.setResultCode(-1509860634);
            _return.setResultText("ResultText809494685");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1236815973");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
