package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.915+09:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://www.verimatrix.com/omi", name = "ContentMgmt")
@XmlSeeAlso({com.verimatrix.schemas.iptvtypes.ObjectFactory.class, com.verimatrix.schemas.omitypes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ContentMgmt {

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeContent")
    public com.verimatrix.schemas.omitypes.ResultList removeContent(
        @WebParam(partName = "contentList", name = "contentList")
        com.verimatrix.schemas.omitypes.ContentList contentList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getContentOnNetwork")
    public com.verimatrix.schemas.omitypes.NetworkContentResult getContentOnNetwork(
        @WebParam(partName = "contentOnNetworkQuery", name = "contentOnNetworkQuery")
        com.verimatrix.schemas.omitypes.ContentOnNetworkQuery contentOnNetworkQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getContentEvents")
    public com.verimatrix.schemas.omitypes.ContentEventResult getContentEvents(
        @WebParam(partName = "contentEventQuery", name = "contentEventQuery")
        com.verimatrix.schemas.omitypes.ContentEventQuery contentEventQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeEvents")
    public com.verimatrix.schemas.omitypes.ResultList removeEvents(
        @WebParam(partName = "eventList", name = "eventList")
        com.verimatrix.schemas.omitypes.EventList eventList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeContentFromNetwork")
    public com.verimatrix.schemas.omitypes.Result removeContentFromNetwork(
        @WebParam(partName = "networkContent", name = "networkContent")
        com.verimatrix.schemas.omitypes.NetworkContent networkContent,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getContentList")
    public com.verimatrix.schemas.omitypes.ContentListResult getContentList(
        @WebParam(partName = "contentListQuery", name = "contentListQuery")
        com.verimatrix.schemas.omitypes.ContentListQuery contentListQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/addContent")
    public com.verimatrix.schemas.omitypes.ResultList addContent(
        @WebParam(partName = "contentList", name = "contentList")
        com.verimatrix.schemas.omitypes.ContentList contentList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/addEvents")
    public com.verimatrix.schemas.omitypes.ResultList addEvents(
        @WebParam(partName = "eventList", name = "eventList")
        com.verimatrix.schemas.omitypes.EventList eventList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentTypeEncryptionStatus")
    public com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionResult getNetworkContentTypeEncryptionStatus(
        @WebParam(partName = "networkContentTypeEncryptionQuery", name = "networkContentTypeEncryptionQuery")
        com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionQuery networkContentTypeEncryptionQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyContentOnNetwork")
    public com.verimatrix.schemas.omitypes.Result modifyContentOnNetwork(
        @WebParam(partName = "networkContent", name = "networkContent")
        com.verimatrix.schemas.omitypes.NetworkContent networkContent,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentIdList")
    public com.verimatrix.schemas.omitypes.NetworkContentIdResult getNetworkContentIdList(
        @WebParam(partName = "networkContentIdQuery", name = "networkContentIdQuery")
        com.verimatrix.schemas.omitypes.NetworkContentIdQuery networkContentIdQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentEncryptionStatus")
    public com.verimatrix.schemas.omitypes.NetworkContentEncryptionResult getNetworkContentEncryptionStatus(
        @WebParam(partName = "networkContentEncryptionQuery", name = "networkContentEncryptionQuery")
        com.verimatrix.schemas.omitypes.NetworkContentEncryptionQuery networkContentEncryptionQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/addContentToNetwork")
    public com.verimatrix.schemas.omitypes.Result addContentToNetwork(
        @WebParam(partName = "networkContent", name = "networkContent")
        com.verimatrix.schemas.omitypes.NetworkContent networkContent,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );
}
