
package com.verimatrix.omi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.149+09:00
 * Generated source version: 2.7.13
 * 
 */
public final class DeviceMgmt_DeviceMgmt_Client {

    private static final QName SERVICE_NAME = new QName("http://www.verimatrix.com/omi", "DeviceMgmtService");

    private DeviceMgmt_DeviceMgmt_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DeviceMgmtService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DeviceMgmtService ss = new DeviceMgmtService(wsdlURL, SERVICE_NAME);
        DeviceMgmt port = ss.getDeviceMgmt();  
        
        {
        System.out.println("Invoking setDeviceRegion...");
        com.verimatrix.schemas.omitypes.Device _setDeviceRegion_device = new com.verimatrix.schemas.omitypes.Device();
        _setDeviceRegion_device.setSmsDeviceId("SmsDeviceId814433552");
        _setDeviceRegion_device.setSmsNetworkId("SmsNetworkId114295699");
        com.verimatrix.schemas.omitypes.DeviceType _setDeviceRegion_deviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.DESKTOP_PC;
        _setDeviceRegion_device.setDeviceType(_setDeviceRegion_deviceDeviceType);
        _setDeviceRegion_device.setNetworkDeviceId("NetworkDeviceId-546097775");
        byte[] _setDeviceRegion_deviceSmsAuthenticator = new byte[] {};
        _setDeviceRegion_device.setSmsAuthenticator(_setDeviceRegion_deviceSmsAuthenticator);
        com.verimatrix.schemas.omitypes.DeviceRegion _setDeviceRegion_deviceRegion = new com.verimatrix.schemas.omitypes.DeviceRegion();
        _setDeviceRegion_deviceRegion.setRegion("Region262558373");
        com.verimatrix.schemas.omitypes.SessionHandle _setDeviceRegion_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _setDeviceRegion_sessionHandle.setHandle("Handle1913951721");
        com.verimatrix.schemas.omitypes.Result _setDeviceRegion__return = port.setDeviceRegion(_setDeviceRegion_device, _setDeviceRegion_deviceRegion, _setDeviceRegion_sessionHandle);
        System.out.println("setDeviceRegion.result=" + _setDeviceRegion__return);


        }
        {
        System.out.println("Invoking setDevicePins...");
        com.verimatrix.schemas.omitypes.Device _setDevicePins_device = new com.verimatrix.schemas.omitypes.Device();
        _setDevicePins_device.setSmsDeviceId("SmsDeviceId-926774992");
        _setDevicePins_device.setSmsNetworkId("SmsNetworkId1955323176");
        com.verimatrix.schemas.omitypes.DeviceType _setDevicePins_deviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PLAYREADY_MAC;
        _setDevicePins_device.setDeviceType(_setDevicePins_deviceDeviceType);
        _setDevicePins_device.setNetworkDeviceId("NetworkDeviceId-284156334");
        byte[] _setDevicePins_deviceSmsAuthenticator = new byte[] {};
        _setDevicePins_device.setSmsAuthenticator(_setDevicePins_deviceSmsAuthenticator);
        com.verimatrix.schemas.omitypes.DevicePinList _setDevicePins_devicePinList = new com.verimatrix.schemas.omitypes.DevicePinList();
        java.util.List<com.verimatrix.schemas.omitypes.DevicePin> _setDevicePins_devicePinListPins = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DevicePin>();
        com.verimatrix.schemas.omitypes.DevicePin _setDevicePins_devicePinListPinsVal1 = new com.verimatrix.schemas.omitypes.DevicePin();
        _setDevicePins_devicePinListPinsVal1.setIndex(-258115823);
        _setDevicePins_devicePinListPinsVal1.setValue(-256982474);
        _setDevicePins_devicePinListPins.add(_setDevicePins_devicePinListPinsVal1);
        _setDevicePins_devicePinList.getPins().addAll(_setDevicePins_devicePinListPins);
        com.verimatrix.schemas.omitypes.SessionHandle _setDevicePins_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _setDevicePins_sessionHandle.setHandle("Handle-2035348747");
        com.verimatrix.schemas.omitypes.Result _setDevicePins__return = port.setDevicePins(_setDevicePins_device, _setDevicePins_devicePinList, _setDevicePins_sessionHandle);
        System.out.println("setDevicePins.result=" + _setDevicePins__return);


        }
        {
        System.out.println("Invoking joinDevices...");
        com.verimatrix.schemas.omitypes.Device _joinDevices_masterDevice = new com.verimatrix.schemas.omitypes.Device();
        _joinDevices_masterDevice.setSmsDeviceId("SmsDeviceId-586822617");
        _joinDevices_masterDevice.setSmsNetworkId("SmsNetworkId2083607748");
        com.verimatrix.schemas.omitypes.DeviceType _joinDevices_masterDeviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PROF_RECEIVER;
        _joinDevices_masterDevice.setDeviceType(_joinDevices_masterDeviceDeviceType);
        _joinDevices_masterDevice.setNetworkDeviceId("NetworkDeviceId900254772");
        byte[] _joinDevices_masterDeviceSmsAuthenticator = new byte[] {};
        _joinDevices_masterDevice.setSmsAuthenticator(_joinDevices_masterDeviceSmsAuthenticator);
        com.verimatrix.schemas.omitypes.DeviceList _joinDevices_slaveDeviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _joinDevices_slaveDeviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _joinDevices_slaveDeviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _joinDevices_slaveDeviceListDevicesVal1.setSmsDeviceId("SmsDeviceId626187231");
        _joinDevices_slaveDeviceListDevicesVal1.setSmsNetworkId("SmsNetworkId746705340");
        com.verimatrix.schemas.omitypes.DeviceType _joinDevices_slaveDeviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.STB_DVB_STB;
        _joinDevices_slaveDeviceListDevicesVal1.setDeviceType(_joinDevices_slaveDeviceListDevicesVal1DeviceType);
        _joinDevices_slaveDeviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId492980504");
        byte[] _joinDevices_slaveDeviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _joinDevices_slaveDeviceListDevicesVal1.setSmsAuthenticator(_joinDevices_slaveDeviceListDevicesVal1SmsAuthenticator);
        _joinDevices_slaveDeviceListDevices.add(_joinDevices_slaveDeviceListDevicesVal1);
        _joinDevices_slaveDeviceList.getDevices().addAll(_joinDevices_slaveDeviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _joinDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _joinDevices_sessionHandle.setHandle("Handle-1433934704");
        com.verimatrix.schemas.omitypes.Result _joinDevices__return = port.joinDevices(_joinDevices_masterDevice, _joinDevices_slaveDeviceList, _joinDevices_sessionHandle);
        System.out.println("joinDevices.result=" + _joinDevices__return);


        }
        {
        System.out.println("Invoking unjoinDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _unjoinDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _unjoinDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _unjoinDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _unjoinDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId-1005114073");
        _unjoinDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId-386949769");
        com.verimatrix.schemas.omitypes.DeviceType _unjoinDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.WEB_STB;
        _unjoinDevices_deviceListDevicesVal1.setDeviceType(_unjoinDevices_deviceListDevicesVal1DeviceType);
        _unjoinDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-1148520010");
        byte[] _unjoinDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _unjoinDevices_deviceListDevicesVal1.setSmsAuthenticator(_unjoinDevices_deviceListDevicesVal1SmsAuthenticator);
        _unjoinDevices_deviceListDevices.add(_unjoinDevices_deviceListDevicesVal1);
        _unjoinDevices_deviceList.getDevices().addAll(_unjoinDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _unjoinDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _unjoinDevices_sessionHandle.setHandle("Handle-812863902");
        com.verimatrix.schemas.omitypes.ResultList _unjoinDevices__return = port.unjoinDevices(_unjoinDevices_deviceList, _unjoinDevices_sessionHandle);
        System.out.println("unjoinDevices.result=" + _unjoinDevices__return);


        }
        {
        System.out.println("Invoking setDevicePurse...");
        com.verimatrix.schemas.omitypes.Device _setDevicePurse_device = new com.verimatrix.schemas.omitypes.Device();
        _setDevicePurse_device.setSmsDeviceId("SmsDeviceId-1504446990");
        _setDevicePurse_device.setSmsNetworkId("SmsNetworkId-1428059746");
        com.verimatrix.schemas.omitypes.DeviceType _setDevicePurse_deviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PLAYREADY_PC;
        _setDevicePurse_device.setDeviceType(_setDevicePurse_deviceDeviceType);
        _setDevicePurse_device.setNetworkDeviceId("NetworkDeviceId1974055087");
        byte[] _setDevicePurse_deviceSmsAuthenticator = new byte[] {};
        _setDevicePurse_device.setSmsAuthenticator(_setDevicePurse_deviceSmsAuthenticator);
        com.verimatrix.schemas.omitypes.DevicePurse _setDevicePurse_devicePurse = new com.verimatrix.schemas.omitypes.DevicePurse();
        _setDevicePurse_devicePurse.setTokens(-1584630325);
        com.verimatrix.schemas.omitypes.SessionHandle _setDevicePurse_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _setDevicePurse_sessionHandle.setHandle("Handle-303747667");
        com.verimatrix.schemas.omitypes.Result _setDevicePurse__return = port.setDevicePurse(_setDevicePurse_device, _setDevicePurse_devicePurse, _setDevicePurse_sessionHandle);
        System.out.println("setDevicePurse.result=" + _setDevicePurse__return);


        }
        {
        System.out.println("Invoking resetDevicePins...");
        com.verimatrix.schemas.omitypes.Device _resetDevicePins_device = new com.verimatrix.schemas.omitypes.Device();
        _resetDevicePins_device.setSmsDeviceId("SmsDeviceId-1587675756");
        _resetDevicePins_device.setSmsNetworkId("SmsNetworkId1129526821");
        com.verimatrix.schemas.omitypes.DeviceType _resetDevicePins_deviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PROF_RECEIVER;
        _resetDevicePins_device.setDeviceType(_resetDevicePins_deviceDeviceType);
        _resetDevicePins_device.setNetworkDeviceId("NetworkDeviceId-1380847322");
        byte[] _resetDevicePins_deviceSmsAuthenticator = new byte[] {};
        _resetDevicePins_device.setSmsAuthenticator(_resetDevicePins_deviceSmsAuthenticator);
        com.verimatrix.schemas.omitypes.SessionHandle _resetDevicePins_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _resetDevicePins_sessionHandle.setHandle("Handle1342332060");
        com.verimatrix.schemas.omitypes.Result _resetDevicePins__return = port.resetDevicePins(_resetDevicePins_device, _resetDevicePins_sessionHandle);
        System.out.println("resetDevicePins.result=" + _resetDevicePins__return);


        }
        {
        System.out.println("Invoking addDevicePair...");
        com.verimatrix.schemas.omitypes.DevicePair _addDevicePair_devicePair = new com.verimatrix.schemas.omitypes.DevicePair();
        com.verimatrix.schemas.omitypes.STBDevice _addDevicePair_devicePairStbDevice = new com.verimatrix.schemas.omitypes.STBDevice();
        _addDevicePair_devicePairStbDevice.setSmsSTBId("SmsSTBId168768999");
        _addDevicePair_devicePair.setStbDevice(_addDevicePair_devicePairStbDevice);
        com.verimatrix.schemas.omitypes.SmartCardDevice _addDevicePair_devicePairSmartCardDevice = new com.verimatrix.schemas.omitypes.SmartCardDevice();
        _addDevicePair_devicePairSmartCardDevice.setSmsSmartCardId("SmsSmartCardId-498417010");
        _addDevicePair_devicePair.setSmartCardDevice(_addDevicePair_devicePairSmartCardDevice);
        com.verimatrix.schemas.omitypes.SessionHandle _addDevicePair_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addDevicePair_sessionHandle.setHandle("Handle61149569");
        com.verimatrix.schemas.omitypes.Result _addDevicePair__return = port.addDevicePair(_addDevicePair_devicePair, _addDevicePair_sessionHandle);
        System.out.println("addDevicePair.result=" + _addDevicePair__return);


        }
        {
        System.out.println("Invoking clearDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _clearDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _clearDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _clearDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _clearDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId-1833731587");
        _clearDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId-38659688");
        com.verimatrix.schemas.omitypes.DeviceType _clearDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.PLAYREADY_ANDROID;
        _clearDevices_deviceListDevicesVal1.setDeviceType(_clearDevices_deviceListDevicesVal1DeviceType);
        _clearDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-730219800");
        byte[] _clearDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _clearDevices_deviceListDevicesVal1.setSmsAuthenticator(_clearDevices_deviceListDevicesVal1SmsAuthenticator);
        _clearDevices_deviceListDevices.add(_clearDevices_deviceListDevicesVal1);
        _clearDevices_deviceList.getDevices().addAll(_clearDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _clearDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _clearDevices_sessionHandle.setHandle("Handle-1619202459");
        com.verimatrix.schemas.omitypes.ResultList _clearDevices__return = port.clearDevices(_clearDevices_deviceList, _clearDevices_sessionHandle);
        System.out.println("clearDevices.result=" + _clearDevices__return);


        }
        {
        System.out.println("Invoking removeDevicePair...");
        com.verimatrix.schemas.omitypes.DevicePair _removeDevicePair_devicePair = new com.verimatrix.schemas.omitypes.DevicePair();
        com.verimatrix.schemas.omitypes.STBDevice _removeDevicePair_devicePairStbDevice = new com.verimatrix.schemas.omitypes.STBDevice();
        _removeDevicePair_devicePairStbDevice.setSmsSTBId("SmsSTBId-1973281266");
        _removeDevicePair_devicePair.setStbDevice(_removeDevicePair_devicePairStbDevice);
        com.verimatrix.schemas.omitypes.SmartCardDevice _removeDevicePair_devicePairSmartCardDevice = new com.verimatrix.schemas.omitypes.SmartCardDevice();
        _removeDevicePair_devicePairSmartCardDevice.setSmsSmartCardId("SmsSmartCardId1396682538");
        _removeDevicePair_devicePair.setSmartCardDevice(_removeDevicePair_devicePairSmartCardDevice);
        com.verimatrix.schemas.omitypes.SessionHandle _removeDevicePair_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeDevicePair_sessionHandle.setHandle("Handle-1930249719");
        com.verimatrix.schemas.omitypes.Result _removeDevicePair__return = port.removeDevicePair(_removeDevicePair_devicePair, _removeDevicePair_sessionHandle);
        System.out.println("removeDevicePair.result=" + _removeDevicePair__return);


        }
        {
        System.out.println("Invoking getDeviceList...");
        com.verimatrix.schemas.omitypes.DeviceListQuery _getDeviceList_deviceListQuery = new com.verimatrix.schemas.omitypes.DeviceListQuery();
        _getDeviceList_deviceListQuery.setSmsDeviceId("SmsDeviceId976773817");
        _getDeviceList_deviceListQuery.setDeviceCount(379816773);
        com.verimatrix.schemas.omitypes.SessionHandle _getDeviceList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDeviceList_sessionHandle.setHandle("Handle1063649351");
        com.verimatrix.schemas.omitypes.DeviceListResult _getDeviceList__return = port.getDeviceList(_getDeviceList_deviceListQuery, _getDeviceList_sessionHandle);
        System.out.println("getDeviceList.result=" + _getDeviceList__return);


        }
        {
        System.out.println("Invoking disableDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _disableDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _disableDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _disableDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _disableDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId-1098057940");
        _disableDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId-1785729115");
        com.verimatrix.schemas.omitypes.DeviceType _disableDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.WEB_IPHONE;
        _disableDevices_deviceListDevicesVal1.setDeviceType(_disableDevices_deviceListDevicesVal1DeviceType);
        _disableDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-179085778");
        byte[] _disableDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _disableDevices_deviceListDevicesVal1.setSmsAuthenticator(_disableDevices_deviceListDevicesVal1SmsAuthenticator);
        _disableDevices_deviceListDevices.add(_disableDevices_deviceListDevicesVal1);
        _disableDevices_deviceList.getDevices().addAll(_disableDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _disableDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _disableDevices_sessionHandle.setHandle("Handle913706631");
        com.verimatrix.schemas.omitypes.ResultList _disableDevices__return = port.disableDevices(_disableDevices_deviceList, _disableDevices_sessionHandle);
        System.out.println("disableDevices.result=" + _disableDevices__return);


        }
        {
        System.out.println("Invoking getSTBPairing...");
        com.verimatrix.schemas.omitypes.STBPairingQuery _getSTBPairing_stbPairingQuery = new com.verimatrix.schemas.omitypes.STBPairingQuery();
        _getSTBPairing_stbPairingQuery.setStbDeviceId("StbDeviceId-330796717");
        com.verimatrix.schemas.omitypes.SessionHandle _getSTBPairing_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getSTBPairing_sessionHandle.setHandle("Handle870976039");
        com.verimatrix.schemas.omitypes.STBPairingResult _getSTBPairing__return = port.getSTBPairing(_getSTBPairing_stbPairingQuery, _getSTBPairing_sessionHandle);
        System.out.println("getSTBPairing.result=" + _getSTBPairing__return);


        }
        {
        System.out.println("Invoking getNetworkDeviceIdList...");
        com.verimatrix.schemas.omitypes.NetworkDeviceIdQuery _getNetworkDeviceIdList_networkDeviceIdListQuery = new com.verimatrix.schemas.omitypes.NetworkDeviceIdQuery();
        _getNetworkDeviceIdList_networkDeviceIdListQuery.setSmsNetworkId("SmsNetworkId-889628958");
        _getNetworkDeviceIdList_networkDeviceIdListQuery.setNetworkDeviceId("NetworkDeviceId1088657873");
        _getNetworkDeviceIdList_networkDeviceIdListQuery.setDeviceCount(-973679751);
        com.verimatrix.schemas.omitypes.NetworkDeviceIdFilter _getNetworkDeviceIdList_networkDeviceIdListQueryFilter = new com.verimatrix.schemas.omitypes.NetworkDeviceIdFilter();
        com.verimatrix.schemas.omitypes.DeviceType _getNetworkDeviceIdList_networkDeviceIdListQueryFilterDeviceType = com.verimatrix.schemas.omitypes.DeviceType.STB_DVB_NSC_2;
        _getNetworkDeviceIdList_networkDeviceIdListQueryFilter.setDeviceType(_getNetworkDeviceIdList_networkDeviceIdListQueryFilterDeviceType);
        com.verimatrix.schemas.omitypes.NetworkDeviceIdAttributes _getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributes = new com.verimatrix.schemas.omitypes.NetworkDeviceIdAttributes();
        com.verimatrix.schemas.iptvtypes.DeviceAttributes _getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributesDeviceAttributes = new com.verimatrix.schemas.iptvtypes.DeviceAttributes();
        _getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributesDeviceAttributes.setStatus(Boolean.valueOf(false));
        _getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributesDeviceAttributes.setNotBefore(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.196+09:00"));
        _getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributesDeviceAttributes.setNotAfter(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.212+09:00"));
        _getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributes.setDeviceAttributes(_getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributesDeviceAttributes);
        _getNetworkDeviceIdList_networkDeviceIdListQueryFilter.setAttributes(_getNetworkDeviceIdList_networkDeviceIdListQueryFilterAttributes);
        _getNetworkDeviceIdList_networkDeviceIdListQuery.setFilter(_getNetworkDeviceIdList_networkDeviceIdListQueryFilter);
        com.verimatrix.schemas.omitypes.SessionHandle _getNetworkDeviceIdList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getNetworkDeviceIdList_sessionHandle.setHandle("Handle-140706028");
        com.verimatrix.schemas.omitypes.NetworkDeviceIdResult _getNetworkDeviceIdList__return = port.getNetworkDeviceIdList(_getNetworkDeviceIdList_networkDeviceIdListQuery, _getNetworkDeviceIdList_sessionHandle);
        System.out.println("getNetworkDeviceIdList.result=" + _getNetworkDeviceIdList__return);


        }
        {
        System.out.println("Invoking removeSmartCardDevicePairing...");
        com.verimatrix.schemas.omitypes.SmartCardDevice _removeSmartCardDevicePairing_smartCardDevice = new com.verimatrix.schemas.omitypes.SmartCardDevice();
        _removeSmartCardDevicePairing_smartCardDevice.setSmsSmartCardId("SmsSmartCardId-1158702695");
        com.verimatrix.schemas.omitypes.SessionHandle _removeSmartCardDevicePairing_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeSmartCardDevicePairing_sessionHandle.setHandle("Handle-1034290128");
        com.verimatrix.schemas.omitypes.Result _removeSmartCardDevicePairing__return = port.removeSmartCardDevicePairing(_removeSmartCardDevicePairing_smartCardDevice, _removeSmartCardDevicePairing_sessionHandle);
        System.out.println("removeSmartCardDevicePairing.result=" + _removeSmartCardDevicePairing__return);


        }
        {
        System.out.println("Invoking modifyDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _modifyDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _modifyDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _modifyDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _modifyDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId427250581");
        _modifyDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId-1252861753");
        com.verimatrix.schemas.omitypes.DeviceType _modifyDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.STB_DVB_NSC_2;
        _modifyDevices_deviceListDevicesVal1.setDeviceType(_modifyDevices_deviceListDevicesVal1DeviceType);
        _modifyDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-563078761");
        byte[] _modifyDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _modifyDevices_deviceListDevicesVal1.setSmsAuthenticator(_modifyDevices_deviceListDevicesVal1SmsAuthenticator);
        _modifyDevices_deviceListDevices.add(_modifyDevices_deviceListDevicesVal1);
        _modifyDevices_deviceList.getDevices().addAll(_modifyDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _modifyDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifyDevices_sessionHandle.setHandle("Handle-1143245737");
        com.verimatrix.schemas.omitypes.ResultList _modifyDevices__return = port.modifyDevices(_modifyDevices_deviceList, _modifyDevices_sessionHandle);
        System.out.println("modifyDevices.result=" + _modifyDevices__return);


        }
        {
        System.out.println("Invoking removeSTBDevicePairing...");
        com.verimatrix.schemas.omitypes.STBDevice _removeSTBDevicePairing_stbDevice = new com.verimatrix.schemas.omitypes.STBDevice();
        _removeSTBDevicePairing_stbDevice.setSmsSTBId("SmsSTBId1568426779");
        com.verimatrix.schemas.omitypes.SessionHandle _removeSTBDevicePairing_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeSTBDevicePairing_sessionHandle.setHandle("Handle1207275039");
        com.verimatrix.schemas.omitypes.Result _removeSTBDevicePairing__return = port.removeSTBDevicePairing(_removeSTBDevicePairing_stbDevice, _removeSTBDevicePairing_sessionHandle);
        System.out.println("removeSTBDevicePairing.result=" + _removeSTBDevicePairing__return);


        }
        {
        System.out.println("Invoking getSmartCardPairing...");
        com.verimatrix.schemas.omitypes.SmartCardPairingQuery _getSmartCardPairing_smartCardPairingQuery = new com.verimatrix.schemas.omitypes.SmartCardPairingQuery();
        _getSmartCardPairing_smartCardPairingQuery.setSmartCardDeviceId("SmartCardDeviceId-473163580");
        com.verimatrix.schemas.omitypes.SessionHandle _getSmartCardPairing_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getSmartCardPairing_sessionHandle.setHandle("Handle-1133644808");
        com.verimatrix.schemas.omitypes.SmartCardPairingResult _getSmartCardPairing__return = port.getSmartCardPairing(_getSmartCardPairing_smartCardPairingQuery, _getSmartCardPairing_sessionHandle);
        System.out.println("getSmartCardPairing.result=" + _getSmartCardPairing__return);


        }
        {
        System.out.println("Invoking refreshDeviceKeys...");
        com.verimatrix.schemas.omitypes.Device _refreshDeviceKeys_device = new com.verimatrix.schemas.omitypes.Device();
        _refreshDeviceKeys_device.setSmsDeviceId("SmsDeviceId-81536363");
        _refreshDeviceKeys_device.setSmsNetworkId("SmsNetworkId-1179852695");
        com.verimatrix.schemas.omitypes.DeviceType _refreshDeviceKeys_deviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.WEB_STB;
        _refreshDeviceKeys_device.setDeviceType(_refreshDeviceKeys_deviceDeviceType);
        _refreshDeviceKeys_device.setNetworkDeviceId("NetworkDeviceId679151822");
        byte[] _refreshDeviceKeys_deviceSmsAuthenticator = new byte[] {};
        _refreshDeviceKeys_device.setSmsAuthenticator(_refreshDeviceKeys_deviceSmsAuthenticator);
        com.verimatrix.schemas.omitypes.SessionHandle _refreshDeviceKeys_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _refreshDeviceKeys_sessionHandle.setHandle("Handle-40724516");
        com.verimatrix.schemas.omitypes.Result _refreshDeviceKeys__return = port.refreshDeviceKeys(_refreshDeviceKeys_device, _refreshDeviceKeys_sessionHandle);
        System.out.println("refreshDeviceKeys.result=" + _refreshDeviceKeys__return);


        }
        {
        System.out.println("Invoking enableDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _enableDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _enableDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _enableDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _enableDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId-1507502916");
        _enableDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId-1878875332");
        com.verimatrix.schemas.omitypes.DeviceType _enableDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.STB_IPTV;
        _enableDevices_deviceListDevicesVal1.setDeviceType(_enableDevices_deviceListDevicesVal1DeviceType);
        _enableDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-647908140");
        byte[] _enableDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _enableDevices_deviceListDevicesVal1.setSmsAuthenticator(_enableDevices_deviceListDevicesVal1SmsAuthenticator);
        _enableDevices_deviceListDevices.add(_enableDevices_deviceListDevicesVal1);
        _enableDevices_deviceList.getDevices().addAll(_enableDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _enableDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _enableDevices_sessionHandle.setHandle("Handle-1020479918");
        com.verimatrix.schemas.omitypes.ResultList _enableDevices__return = port.enableDevices(_enableDevices_deviceList, _enableDevices_sessionHandle);
        System.out.println("enableDevices.result=" + _enableDevices__return);


        }
        {
        System.out.println("Invoking removeDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _removeDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _removeDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _removeDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _removeDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId612034192");
        _removeDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId414321484");
        com.verimatrix.schemas.omitypes.DeviceType _removeDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.RKE;
        _removeDevices_deviceListDevicesVal1.setDeviceType(_removeDevices_deviceListDevicesVal1DeviceType);
        _removeDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-817698038");
        byte[] _removeDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _removeDevices_deviceListDevicesVal1.setSmsAuthenticator(_removeDevices_deviceListDevicesVal1SmsAuthenticator);
        _removeDevices_deviceListDevices.add(_removeDevices_deviceListDevicesVal1);
        _removeDevices_deviceList.getDevices().addAll(_removeDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _removeDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeDevices_sessionHandle.setHandle("Handle638285157");
        com.verimatrix.schemas.omitypes.ResultList _removeDevices__return = port.removeDevices(_removeDevices_deviceList, _removeDevices_sessionHandle);
        System.out.println("removeDevices.result=" + _removeDevices__return);


        }
        {
        System.out.println("Invoking addDevices...");
        com.verimatrix.schemas.omitypes.DeviceList _addDevices_deviceList = new com.verimatrix.schemas.omitypes.DeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.Device> _addDevices_deviceListDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Device>();
        com.verimatrix.schemas.omitypes.Device _addDevices_deviceListDevicesVal1 = new com.verimatrix.schemas.omitypes.Device();
        _addDevices_deviceListDevicesVal1.setSmsDeviceId("SmsDeviceId-1983932125");
        _addDevices_deviceListDevicesVal1.setSmsNetworkId("SmsNetworkId1685633713");
        com.verimatrix.schemas.omitypes.DeviceType _addDevices_deviceListDevicesVal1DeviceType = com.verimatrix.schemas.omitypes.DeviceType.PLAYREADY_MAC;
        _addDevices_deviceListDevicesVal1.setDeviceType(_addDevices_deviceListDevicesVal1DeviceType);
        _addDevices_deviceListDevicesVal1.setNetworkDeviceId("NetworkDeviceId-1003369264");
        byte[] _addDevices_deviceListDevicesVal1SmsAuthenticator = new byte[] {};
        _addDevices_deviceListDevicesVal1.setSmsAuthenticator(_addDevices_deviceListDevicesVal1SmsAuthenticator);
        _addDevices_deviceListDevices.add(_addDevices_deviceListDevicesVal1);
        _addDevices_deviceList.getDevices().addAll(_addDevices_deviceListDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _addDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addDevices_sessionHandle.setHandle("Handle-609322604");
        com.verimatrix.schemas.omitypes.ResultList _addDevices__return = port.addDevices(_addDevices_deviceList, _addDevices_sessionHandle);
        System.out.println("addDevices.result=" + _addDevices__return);


        }
        {
        System.out.println("Invoking checkDevicePair...");
        com.verimatrix.schemas.omitypes.DevicePair _checkDevicePair_devicePair = new com.verimatrix.schemas.omitypes.DevicePair();
        com.verimatrix.schemas.omitypes.STBDevice _checkDevicePair_devicePairStbDevice = new com.verimatrix.schemas.omitypes.STBDevice();
        _checkDevicePair_devicePairStbDevice.setSmsSTBId("SmsSTBId-649921362");
        _checkDevicePair_devicePair.setStbDevice(_checkDevicePair_devicePairStbDevice);
        com.verimatrix.schemas.omitypes.SmartCardDevice _checkDevicePair_devicePairSmartCardDevice = new com.verimatrix.schemas.omitypes.SmartCardDevice();
        _checkDevicePair_devicePairSmartCardDevice.setSmsSmartCardId("SmsSmartCardId-1335821590");
        _checkDevicePair_devicePair.setSmartCardDevice(_checkDevicePair_devicePairSmartCardDevice);
        com.verimatrix.schemas.omitypes.SessionHandle _checkDevicePair_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _checkDevicePair_sessionHandle.setHandle("Handle317250046");
        com.verimatrix.schemas.omitypes.Result _checkDevicePair__return = port.checkDevicePair(_checkDevicePair_devicePair, _checkDevicePair_sessionHandle);
        System.out.println("checkDevicePair.result=" + _checkDevicePair__return);


        }

        System.exit(0);
    }

}
