package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.884+09:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://www.verimatrix.com/omi", name = "DeviceMgmt")
@XmlSeeAlso({com.verimatrix.schemas.iptvtypes.ObjectFactory.class, com.verimatrix.schemas.omitypes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DeviceMgmt {

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/setDeviceRegion")
    public com.verimatrix.schemas.omitypes.Result setDeviceRegion(
        @WebParam(partName = "device", name = "device")
        com.verimatrix.schemas.omitypes.Device device,
        @WebParam(partName = "deviceRegion", name = "deviceRegion")
        com.verimatrix.schemas.omitypes.DeviceRegion deviceRegion,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/setDevicePins")
    public com.verimatrix.schemas.omitypes.Result setDevicePins(
        @WebParam(partName = "device", name = "device")
        com.verimatrix.schemas.omitypes.Device device,
        @WebParam(partName = "devicePinList", name = "devicePinList")
        com.verimatrix.schemas.omitypes.DevicePinList devicePinList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/joinDevices")
    public com.verimatrix.schemas.omitypes.Result joinDevices(
        @WebParam(partName = "masterDevice", name = "masterDevice")
        com.verimatrix.schemas.omitypes.Device masterDevice,
        @WebParam(partName = "slaveDeviceList", name = "slaveDeviceList")
        com.verimatrix.schemas.omitypes.DeviceList slaveDeviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/unjoinDevices")
    public com.verimatrix.schemas.omitypes.ResultList unjoinDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/setDevicePurse")
    public com.verimatrix.schemas.omitypes.Result setDevicePurse(
        @WebParam(partName = "device", name = "device")
        com.verimatrix.schemas.omitypes.Device device,
        @WebParam(partName = "devicePurse", name = "devicePurse")
        com.verimatrix.schemas.omitypes.DevicePurse devicePurse,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/resetDevicePins")
    public com.verimatrix.schemas.omitypes.Result resetDevicePins(
        @WebParam(partName = "device", name = "device")
        com.verimatrix.schemas.omitypes.Device device,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/addDevicePair")
    public com.verimatrix.schemas.omitypes.Result addDevicePair(
        @WebParam(partName = "devicePair", name = "devicePair")
        com.verimatrix.schemas.omitypes.DevicePair devicePair,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/clearDevices")
    public com.verimatrix.schemas.omitypes.ResultList clearDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeDevicePair")
    public com.verimatrix.schemas.omitypes.Result removeDevicePair(
        @WebParam(partName = "devicePair", name = "devicePair")
        com.verimatrix.schemas.omitypes.DevicePair devicePair,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getDeviceList")
    public com.verimatrix.schemas.omitypes.DeviceListResult getDeviceList(
        @WebParam(partName = "deviceListQuery", name = "deviceListQuery")
        com.verimatrix.schemas.omitypes.DeviceListQuery deviceListQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/disableDevices")
    public com.verimatrix.schemas.omitypes.ResultList disableDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getSTBPairing")
    public com.verimatrix.schemas.omitypes.STBPairingResult getSTBPairing(
        @WebParam(partName = "stbPairingQuery", name = "stbPairingQuery")
        com.verimatrix.schemas.omitypes.STBPairingQuery stbPairingQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkDeviceIdList")
    public com.verimatrix.schemas.omitypes.NetworkDeviceIdResult getNetworkDeviceIdList(
        @WebParam(partName = "networkDeviceIdListQuery", name = "networkDeviceIdListQuery")
        com.verimatrix.schemas.omitypes.NetworkDeviceIdQuery networkDeviceIdListQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeSmartCardDevicePairing")
    public com.verimatrix.schemas.omitypes.Result removeSmartCardDevicePairing(
        @WebParam(partName = "smartCardDevice", name = "smartCardDevice")
        com.verimatrix.schemas.omitypes.SmartCardDevice smartCardDevice,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyDevices")
    public com.verimatrix.schemas.omitypes.ResultList modifyDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeSTBDevicePairing")
    public com.verimatrix.schemas.omitypes.Result removeSTBDevicePairing(
        @WebParam(partName = "stbDevice", name = "stbDevice")
        com.verimatrix.schemas.omitypes.STBDevice stbDevice,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "queryResult", targetNamespace = "http://www.verimatrix.com/omi", partName = "queryResult")
    @WebMethod(action = "http://www.verimatrix.com/omi/getSmartCardPairing")
    public com.verimatrix.schemas.omitypes.SmartCardPairingResult getSmartCardPairing(
        @WebParam(partName = "smartCardPairingQuery", name = "smartCardPairingQuery")
        com.verimatrix.schemas.omitypes.SmartCardPairingQuery smartCardPairingQuery,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/refreshDeviceKeys")
    public com.verimatrix.schemas.omitypes.Result refreshDeviceKeys(
        @WebParam(partName = "device", name = "device")
        com.verimatrix.schemas.omitypes.Device device,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/enableDevices")
    public com.verimatrix.schemas.omitypes.ResultList enableDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/removeDevices")
    public com.verimatrix.schemas.omitypes.ResultList removeDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "resultList", targetNamespace = "http://www.verimatrix.com/omi", partName = "resultList")
    @WebMethod(action = "http://www.verimatrix.com/omi/addDevices")
    public com.verimatrix.schemas.omitypes.ResultList addDevices(
        @WebParam(partName = "deviceList", name = "deviceList")
        com.verimatrix.schemas.omitypes.DeviceList deviceList,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );

    @WebResult(name = "result", targetNamespace = "http://www.verimatrix.com/omi", partName = "result")
    @WebMethod(action = "http://www.verimatrix.com/omi/checkDevicePair")
    public com.verimatrix.schemas.omitypes.Result checkDevicePair(
        @WebParam(partName = "devicePair", name = "devicePair")
        com.verimatrix.schemas.omitypes.DevicePair devicePair,
        @WebParam(partName = "sessionHandle", name = "sessionHandle")
        com.verimatrix.schemas.omitypes.SessionHandle sessionHandle
    );
}
