
package com.verimatrix.omi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.212+09:00
 * Generated source version: 2.7.13
 * 
 */
public final class DomainMgmt_DomainMgmt_Client {

    private static final QName SERVICE_NAME = new QName("http://www.verimatrix.com/omi", "DomainMgmtService");

    private DomainMgmt_DomainMgmt_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DomainMgmtService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DomainMgmtService ss = new DomainMgmtService(wsdlURL, SERVICE_NAME);
        DomainMgmt port = ss.getDomainMgmt();  
        
        {
        System.out.println("Invoking getDomainDeviceList...");
        com.verimatrix.schemas.omitypes.DomainDeviceListQuery _getDomainDeviceList_domainDeviceListQuery = new com.verimatrix.schemas.omitypes.DomainDeviceListQuery();
        _getDomainDeviceList_domainDeviceListQuery.setSmsDomainId("SmsDomainId-2021124721");
        _getDomainDeviceList_domainDeviceListQuery.setSmsDeviceId("SmsDeviceId-503243921");
        _getDomainDeviceList_domainDeviceListQuery.setDeviceCount(225707624);
        com.verimatrix.schemas.omitypes.SessionHandle _getDomainDeviceList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDomainDeviceList_sessionHandle.setHandle("Handle-1311269786");
        com.verimatrix.schemas.omitypes.DomainDeviceListResult _getDomainDeviceList__return = port.getDomainDeviceList(_getDomainDeviceList_domainDeviceListQuery, _getDomainDeviceList_sessionHandle);
        System.out.println("getDomainDeviceList.result=" + _getDomainDeviceList__return);


        }
        {
        System.out.println("Invoking removeDomains...");
        com.verimatrix.schemas.omitypes.DomainList _removeDomains_domainList = new com.verimatrix.schemas.omitypes.DomainList();
        java.util.List<com.verimatrix.schemas.omitypes.Domain> _removeDomains_domainListDomains = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Domain>();
        com.verimatrix.schemas.omitypes.Domain _removeDomains_domainListDomainsVal1 = new com.verimatrix.schemas.omitypes.Domain();
        _removeDomains_domainListDomainsVal1.setSmsDomainId("SmsDomainId1978153868");
        _removeDomains_domainListDomainsVal1.setMaxDevices(-1653602590);
        com.verimatrix.schemas.omitypes.TimePeriodRule _removeDomains_domainListDomainsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _removeDomains_domainListDomainsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _removeDomains_domainListDomainsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _removeDomains_domainListDomainsVal1.setTimePeriodRule(_removeDomains_domainListDomainsVal1TimePeriodRule);
        _removeDomains_domainListDomainsVal1.setDomainAddress(Integer.valueOf(-1836540162));
        _removeDomains_domainListDomains.add(_removeDomains_domainListDomainsVal1);
        _removeDomains_domainList.getDomains().addAll(_removeDomains_domainListDomains);
        com.verimatrix.schemas.omitypes.SessionHandle _removeDomains_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeDomains_sessionHandle.setHandle("Handle1099642686");
        com.verimatrix.schemas.omitypes.ResultList _removeDomains__return = port.removeDomains(_removeDomains_domainList, _removeDomains_sessionHandle);
        System.out.println("removeDomains.result=" + _removeDomains__return);


        }
        {
        System.out.println("Invoking getDomainList...");
        com.verimatrix.schemas.omitypes.DomainListQuery _getDomainList_domainListQuery = new com.verimatrix.schemas.omitypes.DomainListQuery();
        _getDomainList_domainListQuery.setSmsDomainId("SmsDomainId-1017854477");
        _getDomainList_domainListQuery.setDomainCount(1724829923);
        com.verimatrix.schemas.omitypes.SessionHandle _getDomainList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDomainList_sessionHandle.setHandle("Handle1176691452");
        com.verimatrix.schemas.omitypes.DomainListResult _getDomainList__return = port.getDomainList(_getDomainList_domainListQuery, _getDomainList_sessionHandle);
        System.out.println("getDomainList.result=" + _getDomainList__return);


        }
        {
        System.out.println("Invoking modifyDomainDevices...");
        com.verimatrix.schemas.omitypes.Domain _modifyDomainDevices_domain = new com.verimatrix.schemas.omitypes.Domain();
        _modifyDomainDevices_domain.setSmsDomainId("SmsDomainId-1531173329");
        _modifyDomainDevices_domain.setMaxDevices(1711195071);
        com.verimatrix.schemas.omitypes.TimePeriodRule _modifyDomainDevices_domainTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _modifyDomainDevices_domainTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _modifyDomainDevices_domainTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _modifyDomainDevices_domain.setTimePeriodRule(_modifyDomainDevices_domainTimePeriodRule);
        _modifyDomainDevices_domain.setDomainAddress(Integer.valueOf(-1563405546));
        com.verimatrix.schemas.omitypes.DomainDeviceList _modifyDomainDevices_deviceList = new com.verimatrix.schemas.omitypes.DomainDeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.DomainDevice> _modifyDomainDevices_deviceListDomainDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DomainDevice>();
        com.verimatrix.schemas.omitypes.DomainDevice _modifyDomainDevices_deviceListDomainDevicesVal1 = new com.verimatrix.schemas.omitypes.DomainDevice();
        com.verimatrix.schemas.omitypes.Device _modifyDomainDevices_deviceListDomainDevicesVal1Device = new com.verimatrix.schemas.omitypes.Device();
        _modifyDomainDevices_deviceListDomainDevicesVal1Device.setSmsDeviceId("SmsDeviceId-1310378194");
        _modifyDomainDevices_deviceListDomainDevicesVal1Device.setSmsNetworkId("SmsNetworkId-1083864757");
        com.verimatrix.schemas.omitypes.DeviceType _modifyDomainDevices_deviceListDomainDevicesVal1DeviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.LEGACY;
        _modifyDomainDevices_deviceListDomainDevicesVal1Device.setDeviceType(_modifyDomainDevices_deviceListDomainDevicesVal1DeviceDeviceType);
        _modifyDomainDevices_deviceListDomainDevicesVal1Device.setNetworkDeviceId("NetworkDeviceId346086902");
        byte[] _modifyDomainDevices_deviceListDomainDevicesVal1DeviceSmsAuthenticator = new byte[] {};
        _modifyDomainDevices_deviceListDomainDevicesVal1Device.setSmsAuthenticator(_modifyDomainDevices_deviceListDomainDevicesVal1DeviceSmsAuthenticator);
        _modifyDomainDevices_deviceListDomainDevicesVal1.setDevice(_modifyDomainDevices_deviceListDomainDevicesVal1Device);
        com.verimatrix.schemas.omitypes.TimePeriodRule _modifyDomainDevices_deviceListDomainDevicesVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _modifyDomainDevices_deviceListDomainDevicesVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _modifyDomainDevices_deviceListDomainDevicesVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _modifyDomainDevices_deviceListDomainDevicesVal1.setTimePeriodRule(_modifyDomainDevices_deviceListDomainDevicesVal1TimePeriodRule);
        _modifyDomainDevices_deviceListDomainDevices.add(_modifyDomainDevices_deviceListDomainDevicesVal1);
        _modifyDomainDevices_deviceList.getDomainDevices().addAll(_modifyDomainDevices_deviceListDomainDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _modifyDomainDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifyDomainDevices_sessionHandle.setHandle("Handle-273167776");
        com.verimatrix.schemas.omitypes.ResultList _modifyDomainDevices__return = port.modifyDomainDevices(_modifyDomainDevices_domain, _modifyDomainDevices_deviceList, _modifyDomainDevices_sessionHandle);
        System.out.println("modifyDomainDevices.result=" + _modifyDomainDevices__return);


        }
        {
        System.out.println("Invoking removeDomainDevices...");
        com.verimatrix.schemas.omitypes.Domain _removeDomainDevices_domain = new com.verimatrix.schemas.omitypes.Domain();
        _removeDomainDevices_domain.setSmsDomainId("SmsDomainId1181793342");
        _removeDomainDevices_domain.setMaxDevices(1585070041);
        com.verimatrix.schemas.omitypes.TimePeriodRule _removeDomainDevices_domainTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _removeDomainDevices_domainTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _removeDomainDevices_domainTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _removeDomainDevices_domain.setTimePeriodRule(_removeDomainDevices_domainTimePeriodRule);
        _removeDomainDevices_domain.setDomainAddress(Integer.valueOf(45040942));
        com.verimatrix.schemas.omitypes.DomainDeviceList _removeDomainDevices_deviceList = new com.verimatrix.schemas.omitypes.DomainDeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.DomainDevice> _removeDomainDevices_deviceListDomainDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DomainDevice>();
        com.verimatrix.schemas.omitypes.DomainDevice _removeDomainDevices_deviceListDomainDevicesVal1 = new com.verimatrix.schemas.omitypes.DomainDevice();
        com.verimatrix.schemas.omitypes.Device _removeDomainDevices_deviceListDomainDevicesVal1Device = new com.verimatrix.schemas.omitypes.Device();
        _removeDomainDevices_deviceListDomainDevicesVal1Device.setSmsDeviceId("SmsDeviceId702958884");
        _removeDomainDevices_deviceListDomainDevicesVal1Device.setSmsNetworkId("SmsNetworkId1613147331");
        com.verimatrix.schemas.omitypes.DeviceType _removeDomainDevices_deviceListDomainDevicesVal1DeviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.DESKTOP_PC;
        _removeDomainDevices_deviceListDomainDevicesVal1Device.setDeviceType(_removeDomainDevices_deviceListDomainDevicesVal1DeviceDeviceType);
        _removeDomainDevices_deviceListDomainDevicesVal1Device.setNetworkDeviceId("NetworkDeviceId1846140199");
        byte[] _removeDomainDevices_deviceListDomainDevicesVal1DeviceSmsAuthenticator = new byte[] {};
        _removeDomainDevices_deviceListDomainDevicesVal1Device.setSmsAuthenticator(_removeDomainDevices_deviceListDomainDevicesVal1DeviceSmsAuthenticator);
        _removeDomainDevices_deviceListDomainDevicesVal1.setDevice(_removeDomainDevices_deviceListDomainDevicesVal1Device);
        com.verimatrix.schemas.omitypes.TimePeriodRule _removeDomainDevices_deviceListDomainDevicesVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _removeDomainDevices_deviceListDomainDevicesVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _removeDomainDevices_deviceListDomainDevicesVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.227+09:00"));
        _removeDomainDevices_deviceListDomainDevicesVal1.setTimePeriodRule(_removeDomainDevices_deviceListDomainDevicesVal1TimePeriodRule);
        _removeDomainDevices_deviceListDomainDevices.add(_removeDomainDevices_deviceListDomainDevicesVal1);
        _removeDomainDevices_deviceList.getDomainDevices().addAll(_removeDomainDevices_deviceListDomainDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _removeDomainDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeDomainDevices_sessionHandle.setHandle("Handle-704978478");
        com.verimatrix.schemas.omitypes.ResultList _removeDomainDevices__return = port.removeDomainDevices(_removeDomainDevices_domain, _removeDomainDevices_deviceList, _removeDomainDevices_sessionHandle);
        System.out.println("removeDomainDevices.result=" + _removeDomainDevices__return);


        }
        {
        System.out.println("Invoking getDeviceDomainList...");
        com.verimatrix.schemas.omitypes.DeviceDomainListQuery _getDeviceDomainList_deviceDomainListQuery = new com.verimatrix.schemas.omitypes.DeviceDomainListQuery();
        _getDeviceDomainList_deviceDomainListQuery.setSmsDeviceId("SmsDeviceId582722650");
        _getDeviceDomainList_deviceDomainListQuery.setSmsDomainId("SmsDomainId-1219339985");
        _getDeviceDomainList_deviceDomainListQuery.setDomainCount(-1558888991);
        com.verimatrix.schemas.omitypes.SessionHandle _getDeviceDomainList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDeviceDomainList_sessionHandle.setHandle("Handle-116815665");
        com.verimatrix.schemas.omitypes.DomainListResult _getDeviceDomainList__return = port.getDeviceDomainList(_getDeviceDomainList_deviceDomainListQuery, _getDeviceDomainList_sessionHandle);
        System.out.println("getDeviceDomainList.result=" + _getDeviceDomainList__return);


        }
        {
        System.out.println("Invoking addDomains...");
        com.verimatrix.schemas.omitypes.DomainList _addDomains_domainList = new com.verimatrix.schemas.omitypes.DomainList();
        java.util.List<com.verimatrix.schemas.omitypes.Domain> _addDomains_domainListDomains = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Domain>();
        com.verimatrix.schemas.omitypes.Domain _addDomains_domainListDomainsVal1 = new com.verimatrix.schemas.omitypes.Domain();
        _addDomains_domainListDomainsVal1.setSmsDomainId("SmsDomainId845248823");
        _addDomains_domainListDomainsVal1.setMaxDevices(297658595);
        com.verimatrix.schemas.omitypes.TimePeriodRule _addDomains_domainListDomainsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _addDomains_domainListDomainsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _addDomains_domainListDomainsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _addDomains_domainListDomainsVal1.setTimePeriodRule(_addDomains_domainListDomainsVal1TimePeriodRule);
        _addDomains_domainListDomainsVal1.setDomainAddress(Integer.valueOf(-1335107834));
        _addDomains_domainListDomains.add(_addDomains_domainListDomainsVal1);
        _addDomains_domainList.getDomains().addAll(_addDomains_domainListDomains);
        com.verimatrix.schemas.omitypes.SessionHandle _addDomains_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addDomains_sessionHandle.setHandle("Handle-443577070");
        com.verimatrix.schemas.omitypes.ResultList _addDomains__return = port.addDomains(_addDomains_domainList, _addDomains_sessionHandle);
        System.out.println("addDomains.result=" + _addDomains__return);


        }
        {
        System.out.println("Invoking addDomainDevices...");
        com.verimatrix.schemas.omitypes.Domain _addDomainDevices_domain = new com.verimatrix.schemas.omitypes.Domain();
        _addDomainDevices_domain.setSmsDomainId("SmsDomainId-694723971");
        _addDomainDevices_domain.setMaxDevices(341607732);
        com.verimatrix.schemas.omitypes.TimePeriodRule _addDomainDevices_domainTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _addDomainDevices_domainTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _addDomainDevices_domainTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _addDomainDevices_domain.setTimePeriodRule(_addDomainDevices_domainTimePeriodRule);
        _addDomainDevices_domain.setDomainAddress(Integer.valueOf(1712513340));
        com.verimatrix.schemas.omitypes.DomainDeviceList _addDomainDevices_deviceList = new com.verimatrix.schemas.omitypes.DomainDeviceList();
        java.util.List<com.verimatrix.schemas.omitypes.DomainDevice> _addDomainDevices_deviceListDomainDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DomainDevice>();
        com.verimatrix.schemas.omitypes.DomainDevice _addDomainDevices_deviceListDomainDevicesVal1 = new com.verimatrix.schemas.omitypes.DomainDevice();
        com.verimatrix.schemas.omitypes.Device _addDomainDevices_deviceListDomainDevicesVal1Device = new com.verimatrix.schemas.omitypes.Device();
        _addDomainDevices_deviceListDomainDevicesVal1Device.setSmsDeviceId("SmsDeviceId-1019300636");
        _addDomainDevices_deviceListDomainDevicesVal1Device.setSmsNetworkId("SmsNetworkId1177398187");
        com.verimatrix.schemas.omitypes.DeviceType _addDomainDevices_deviceListDomainDevicesVal1DeviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PLAYREADY_ANDROID;
        _addDomainDevices_deviceListDomainDevicesVal1Device.setDeviceType(_addDomainDevices_deviceListDomainDevicesVal1DeviceDeviceType);
        _addDomainDevices_deviceListDomainDevicesVal1Device.setNetworkDeviceId("NetworkDeviceId-2061395782");
        byte[] _addDomainDevices_deviceListDomainDevicesVal1DeviceSmsAuthenticator = new byte[] {};
        _addDomainDevices_deviceListDomainDevicesVal1Device.setSmsAuthenticator(_addDomainDevices_deviceListDomainDevicesVal1DeviceSmsAuthenticator);
        _addDomainDevices_deviceListDomainDevicesVal1.setDevice(_addDomainDevices_deviceListDomainDevicesVal1Device);
        com.verimatrix.schemas.omitypes.TimePeriodRule _addDomainDevices_deviceListDomainDevicesVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _addDomainDevices_deviceListDomainDevicesVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _addDomainDevices_deviceListDomainDevicesVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _addDomainDevices_deviceListDomainDevicesVal1.setTimePeriodRule(_addDomainDevices_deviceListDomainDevicesVal1TimePeriodRule);
        _addDomainDevices_deviceListDomainDevices.add(_addDomainDevices_deviceListDomainDevicesVal1);
        _addDomainDevices_deviceList.getDomainDevices().addAll(_addDomainDevices_deviceListDomainDevices);
        com.verimatrix.schemas.omitypes.SessionHandle _addDomainDevices_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addDomainDevices_sessionHandle.setHandle("Handle2017737446");
        com.verimatrix.schemas.omitypes.ResultList _addDomainDevices__return = port.addDomainDevices(_addDomainDevices_domain, _addDomainDevices_deviceList, _addDomainDevices_sessionHandle);
        System.out.println("addDomainDevices.result=" + _addDomainDevices__return);


        }
        {
        System.out.println("Invoking modifyDomains...");
        com.verimatrix.schemas.omitypes.DomainList _modifyDomains_domainList = new com.verimatrix.schemas.omitypes.DomainList();
        java.util.List<com.verimatrix.schemas.omitypes.Domain> _modifyDomains_domainListDomains = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Domain>();
        com.verimatrix.schemas.omitypes.Domain _modifyDomains_domainListDomainsVal1 = new com.verimatrix.schemas.omitypes.Domain();
        _modifyDomains_domainListDomainsVal1.setSmsDomainId("SmsDomainId-974675114");
        _modifyDomains_domainListDomainsVal1.setMaxDevices(-2147228155);
        com.verimatrix.schemas.omitypes.TimePeriodRule _modifyDomains_domainListDomainsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _modifyDomains_domainListDomainsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _modifyDomains_domainListDomainsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.243+09:00"));
        _modifyDomains_domainListDomainsVal1.setTimePeriodRule(_modifyDomains_domainListDomainsVal1TimePeriodRule);
        _modifyDomains_domainListDomainsVal1.setDomainAddress(Integer.valueOf(-1279349474));
        _modifyDomains_domainListDomains.add(_modifyDomains_domainListDomainsVal1);
        _modifyDomains_domainList.getDomains().addAll(_modifyDomains_domainListDomains);
        com.verimatrix.schemas.omitypes.SessionHandle _modifyDomains_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifyDomains_sessionHandle.setHandle("Handle639095640");
        com.verimatrix.schemas.omitypes.ResultList _modifyDomains__return = port.modifyDomains(_modifyDomains_domainList, _modifyDomains_sessionHandle);
        System.out.println("modifyDomains.result=" + _modifyDomains__return);


        }

        System.exit(0);
    }

}
