
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.verimatrix.omi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.727+09:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "DomainMgmtService",
                      portName = "DomainMgmt",
                      targetNamespace = "http://www.verimatrix.com/omi",
                      wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                      endpointInterface = "com.verimatrix.omi.DomainMgmt")
                      
public class DomainMgmtImpl implements DomainMgmt {

    private static final Logger LOG = Logger.getLogger(DomainMgmtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#getDomainDeviceList(com.verimatrix.schemas.omitypes.DomainDeviceListQuery  domainDeviceListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DomainDeviceListResult getDomainDeviceList(com.verimatrix.schemas.omitypes.DomainDeviceListQuery domainDeviceListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getDomainDeviceList");
        System.out.println(domainDeviceListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DomainDeviceListResult _return = new com.verimatrix.schemas.omitypes.DomainDeviceListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId1643425017");
            _returnResult.setResultCode(-1803944993);
            _returnResult.setResultText("ResultText-487127567");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id413221988");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.DomainDevice> _returnDomainDevices = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DomainDevice>();
            com.verimatrix.schemas.omitypes.DomainDevice _returnDomainDevicesVal1 = new com.verimatrix.schemas.omitypes.DomainDevice();
            com.verimatrix.schemas.omitypes.Device _returnDomainDevicesVal1Device = new com.verimatrix.schemas.omitypes.Device();
            _returnDomainDevicesVal1Device.setSmsDeviceId("SmsDeviceId-1527567867");
            _returnDomainDevicesVal1Device.setSmsNetworkId("SmsNetworkId390220246");
            com.verimatrix.schemas.omitypes.DeviceType _returnDomainDevicesVal1DeviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PROF_RECEIVER;
            _returnDomainDevicesVal1Device.setDeviceType(_returnDomainDevicesVal1DeviceDeviceType);
            _returnDomainDevicesVal1Device.setNetworkDeviceId("NetworkDeviceId-1048531772");
            byte[] _returnDomainDevicesVal1DeviceSmsAuthenticator = new byte[] {};
            _returnDomainDevicesVal1Device.setSmsAuthenticator(_returnDomainDevicesVal1DeviceSmsAuthenticator);
            _returnDomainDevicesVal1.setDevice(_returnDomainDevicesVal1Device);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnDomainDevicesVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnDomainDevicesVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.743+09:00"));
            _returnDomainDevicesVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.743+09:00"));
            _returnDomainDevicesVal1.setTimePeriodRule(_returnDomainDevicesVal1TimePeriodRule);
            _returnDomainDevices.add(_returnDomainDevicesVal1);
            _return.getDomainDevices().addAll(_returnDomainDevices);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#removeDomains(com.verimatrix.schemas.omitypes.DomainList  domainList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeDomains(com.verimatrix.schemas.omitypes.DomainList domainList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeDomains");
        System.out.println(domainList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-973432945");
            _returnResultVal1.setResultCode(-1163934009);
            _returnResultVal1.setResultText("ResultText2017812103");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#getDomainList(com.verimatrix.schemas.omitypes.DomainListQuery  domainListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DomainListResult getDomainList(com.verimatrix.schemas.omitypes.DomainListQuery domainListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getDomainList");
        System.out.println(domainListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DomainListResult _return = new com.verimatrix.schemas.omitypes.DomainListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-85868560");
            _returnResult.setResultCode(276660270);
            _returnResult.setResultText("ResultText-1317428994");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1850697392");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Domain> _returnDomains = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Domain>();
            com.verimatrix.schemas.omitypes.Domain _returnDomainsVal1 = new com.verimatrix.schemas.omitypes.Domain();
            _returnDomainsVal1.setSmsDomainId("SmsDomainId-1568215543");
            _returnDomainsVal1.setMaxDevices(1892194392);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnDomainsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnDomainsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.743+09:00"));
            _returnDomainsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.743+09:00"));
            _returnDomainsVal1.setTimePeriodRule(_returnDomainsVal1TimePeriodRule);
            _returnDomainsVal1.setDomainAddress(Integer.valueOf(1655611772));
            _returnDomains.add(_returnDomainsVal1);
            _return.getDomains().addAll(_returnDomains);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#modifyDomainDevices(com.verimatrix.schemas.omitypes.Domain  domain ,)com.verimatrix.schemas.omitypes.DomainDeviceList  deviceList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList modifyDomainDevices(com.verimatrix.schemas.omitypes.Domain domain,com.verimatrix.schemas.omitypes.DomainDeviceList deviceList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifyDomainDevices");
        System.out.println(domain);
        System.out.println(deviceList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId1971629141");
            _returnResultVal1.setResultCode(1399072158);
            _returnResultVal1.setResultText("ResultText1106605808");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#removeDomainDevices(com.verimatrix.schemas.omitypes.Domain  domain ,)com.verimatrix.schemas.omitypes.DomainDeviceList  deviceList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeDomainDevices(com.verimatrix.schemas.omitypes.Domain domain,com.verimatrix.schemas.omitypes.DomainDeviceList deviceList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeDomainDevices");
        System.out.println(domain);
        System.out.println(deviceList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-1414350088");
            _returnResultVal1.setResultCode(55374729);
            _returnResultVal1.setResultText("ResultText1364501586");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#getDeviceDomainList(com.verimatrix.schemas.omitypes.DeviceDomainListQuery  deviceDomainListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DomainListResult getDeviceDomainList(com.verimatrix.schemas.omitypes.DeviceDomainListQuery deviceDomainListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getDeviceDomainList");
        System.out.println(deviceDomainListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DomainListResult _return = new com.verimatrix.schemas.omitypes.DomainListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1829256414");
            _returnResult.setResultCode(902300967);
            _returnResult.setResultText("ResultText782248900");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1060459076");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Domain> _returnDomains = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Domain>();
            com.verimatrix.schemas.omitypes.Domain _returnDomainsVal1 = new com.verimatrix.schemas.omitypes.Domain();
            _returnDomainsVal1.setSmsDomainId("SmsDomainId216984435");
            _returnDomainsVal1.setMaxDevices(263563325);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnDomainsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnDomainsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.743+09:00"));
            _returnDomainsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.743+09:00"));
            _returnDomainsVal1.setTimePeriodRule(_returnDomainsVal1TimePeriodRule);
            _returnDomainsVal1.setDomainAddress(Integer.valueOf(1598771706));
            _returnDomains.add(_returnDomainsVal1);
            _return.getDomains().addAll(_returnDomains);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#addDomains(com.verimatrix.schemas.omitypes.DomainList  domainList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addDomains(com.verimatrix.schemas.omitypes.DomainList domainList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addDomains");
        System.out.println(domainList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-108442482");
            _returnResultVal1.setResultCode(1425259027);
            _returnResultVal1.setResultText("ResultText-1694270286");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#addDomainDevices(com.verimatrix.schemas.omitypes.Domain  domain ,)com.verimatrix.schemas.omitypes.DomainDeviceList  deviceList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addDomainDevices(com.verimatrix.schemas.omitypes.Domain domain,com.verimatrix.schemas.omitypes.DomainDeviceList deviceList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addDomainDevices");
        System.out.println(domain);
        System.out.println(deviceList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId1173275055");
            _returnResultVal1.setResultCode(-506035720);
            _returnResultVal1.setResultText("ResultText1597659765");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.DomainMgmt#modifyDomains(com.verimatrix.schemas.omitypes.DomainList  domainList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList modifyDomains(com.verimatrix.schemas.omitypes.DomainList domainList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifyDomains");
        System.out.println(domainList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-18259127");
            _returnResultVal1.setResultCode(1890207402);
            _returnResultVal1.setResultText("ResultText1033275214");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
