
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.verimatrix.omi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.837+09:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "EntitlementMgmtService",
                      portName = "EntitlementMgmt",
                      targetNamespace = "http://www.verimatrix.com/omi",
                      wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                      endpointInterface = "com.verimatrix.omi.EntitlementMgmt")
                      
public class EntitlementMgmtImpl implements EntitlementMgmt {

    private static final Logger LOG = Logger.getLogger(EntitlementMgmtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#removeEntitlements(com.verimatrix.schemas.omitypes.EntitlementList  entitlementList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeEntitlements(com.verimatrix.schemas.omitypes.EntitlementList entitlementList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeEntitlements");
        System.out.println(entitlementList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId1844850376");
            _returnResultVal1.setResultCode(625210181);
            _returnResultVal1.setResultText("ResultText1917892190");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#removeAllEntitlements(com.verimatrix.schemas.omitypes.EntitledEntityList  entitledEntityList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeAllEntitlements(com.verimatrix.schemas.omitypes.EntitledEntityList entitledEntityList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeAllEntitlements");
        System.out.println(entitledEntityList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-488656874");
            _returnResultVal1.setResultCode(-2013252994);
            _returnResultVal1.setResultText("ResultText934539440");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getRetailerEntitlements(com.verimatrix.schemas.omitypes.RetailerEntitlementQuery  entitlementQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.RetailerEntitlementResult getRetailerEntitlements(com.verimatrix.schemas.omitypes.RetailerEntitlementQuery entitlementQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getRetailerEntitlements");
        System.out.println(entitlementQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.RetailerEntitlementResult _return = new com.verimatrix.schemas.omitypes.RetailerEntitlementResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-100533037");
            _returnResult.setResultCode(-1064343926);
            _returnResult.setResultText("ResultText-32719751");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id716697040");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.Site _returnRetailer = new com.verimatrix.schemas.omitypes.Site();
            _returnRetailer.setSmsSiteId("SmsSiteId363971278");
            com.verimatrix.schemas.omitypes.SiteEntityType _returnRetailerEntityType = com.verimatrix.schemas.omitypes.SiteEntityType.RETAILER;
            _returnRetailer.setEntityType(_returnRetailerEntityType);
            _returnRetailer.setName("Name194529400");
            _returnRetailer.setDescription("Description1115093541");
            _returnRetailer.setSiteId("SiteId1375187494");
            _returnRetailer.setAuthPassword("AuthPassword-77291794");
            _return.setRetailer(_returnRetailer);
            java.util.List<com.verimatrix.schemas.omitypes.DeviceData> _returnEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DeviceData>();
            com.verimatrix.schemas.omitypes.DeviceData _returnEntitlementsVal1 = new com.verimatrix.schemas.omitypes.DeviceData();
            com.verimatrix.schemas.omitypes.Entitlement _returnEntitlementsVal1Entitlement = new com.verimatrix.schemas.omitypes.Entitlement();
            _returnEntitlementsVal1Entitlement.setSmsEntitlementId("SmsEntitlementId-2061933602");
            com.verimatrix.schemas.omitypes.Package _returnEntitlementsVal1EntitlementPackage = new com.verimatrix.schemas.omitypes.Package();
            _returnEntitlementsVal1EntitlementPackage.setSmsPackageId("SmsPackageId555543777");
            _returnEntitlementsVal1EntitlementPackage.setDescription("Description-161137973");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnEntitlementsVal1EntitlementPackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setOperatorId("OperatorId1673572093");
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-1146234643");
            _returnEntitlementsVal1EntitlementPackage.setPackageAttributes(_returnEntitlementsVal1EntitlementPackagePackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnEntitlementsVal1EntitlementPackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEntitlementsVal1EntitlementPackagePackageParameters.getPackageParameter().addAll(_returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter);
            _returnEntitlementsVal1EntitlementPackage.setPackageParameters(_returnEntitlementsVal1EntitlementPackagePackageParameters);
            _returnEntitlementsVal1Entitlement.setPackage(_returnEntitlementsVal1EntitlementPackage);
            com.verimatrix.schemas.omitypes.EntitledEntity _returnEntitlementsVal1EntitlementEntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
            com.verimatrix.schemas.omitypes.EntityType _returnEntitlementsVal1EntitlementEntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DOMAIN;
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityType(_returnEntitlementsVal1EntitlementEntitledEntityEntityType);
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityId("EntityId-289647846");
            _returnEntitlementsVal1Entitlement.setEntitledEntity(_returnEntitlementsVal1EntitlementEntitledEntity);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEntitlementsVal1EntitlementTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEntitlementsVal1EntitlementTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEntitlementsVal1EntitlementTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEntitlementsVal1Entitlement.setTimePeriodRule(_returnEntitlementsVal1EntitlementTimePeriodRule);
            _returnEntitlementsVal1.setEntitlement(_returnEntitlementsVal1Entitlement);
            java.util.List<com.verimatrix.schemas.omitypes.Event> _returnEntitlementsVal1Events = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
            _returnEntitlementsVal1.getEvents().addAll(_returnEntitlementsVal1Events);
            _returnEntitlements.add(_returnEntitlementsVal1);
            _return.getEntitlements().addAll(_returnEntitlements);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getEventPackages(com.verimatrix.schemas.omitypes.EventPackageQuery  eventPackageQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.EventPackageResult getEventPackages(com.verimatrix.schemas.omitypes.EventPackageQuery eventPackageQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getEventPackages");
        System.out.println(eventPackageQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.EventPackageResult _return = new com.verimatrix.schemas.omitypes.EventPackageResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1578117999");
            _returnResult.setResultCode(2006112563);
            _returnResult.setResultText("ResultText529507848");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-1285461645");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.Event _returnEvent = new com.verimatrix.schemas.omitypes.Event();
            _returnEvent.setSmsEventId("SmsEventId-614041883");
            _returnEvent.setSmsContentId("SmsContentId1775295299");
            _returnEvent.setSmsNetworkId("SmsNetworkId-582970642");
            _returnEvent.setExclusive(false);
            _returnEvent.setPreStartDuration(-2037922430);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEventTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEventTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEventTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEvent.setTimePeriodRule(_returnEventTimePeriodRule);
            _returnEvent.setRatingLevel(Integer.valueOf(1188765608));
            com.verimatrix.schemas.omitypes.FingerprintMessage _returnEventFingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
            java.util.List<com.verimatrix.schemas.omitypes.MessageText> _returnEventFingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
            _returnEventFingerprintMessage.getText().addAll(_returnEventFingerprintMessageText);
            _returnEvent.setFingerprintMessage(_returnEventFingerprintMessage);
            com.verimatrix.schemas.omitypes.EventParameters _returnEventEventParameters = new com.verimatrix.schemas.omitypes.EventParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEventEventParametersEventParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEventEventParameters.getEventParameter().addAll(_returnEventEventParametersEventParameter);
            _returnEvent.setEventParameters(_returnEventEventParameters);
            _return.setEvent(_returnEvent);
            java.util.List<com.verimatrix.schemas.omitypes.Package> _returnPackages = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Package>();
            com.verimatrix.schemas.omitypes.Package _returnPackagesVal1 = new com.verimatrix.schemas.omitypes.Package();
            _returnPackagesVal1.setSmsPackageId("SmsPackageId-1220762439");
            _returnPackagesVal1.setDescription("Description79004662");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnPackagesVal1PackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnPackagesVal1PackageAttributes.setOperatorId("OperatorId-1262384956");
            _returnPackagesVal1PackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId57544982");
            _returnPackagesVal1.setPackageAttributes(_returnPackagesVal1PackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnPackagesVal1PackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnPackagesVal1PackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnPackagesVal1PackageParameters.getPackageParameter().addAll(_returnPackagesVal1PackageParametersPackageParameter);
            _returnPackagesVal1.setPackageParameters(_returnPackagesVal1PackageParameters);
            _returnPackages.add(_returnPackagesVal1);
            _return.getPackages().addAll(_returnPackages);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getPackageList(com.verimatrix.schemas.omitypes.PackageListQuery  packageListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.PackageListResult getPackageList(com.verimatrix.schemas.omitypes.PackageListQuery packageListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getPackageList");
        System.out.println(packageListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.PackageListResult _return = new com.verimatrix.schemas.omitypes.PackageListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1346369719");
            _returnResult.setResultCode(1920023704);
            _returnResult.setResultText("ResultText-2089421162");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id435614691");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.Package> _returnPackages = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Package>();
            com.verimatrix.schemas.omitypes.Package _returnPackagesVal1 = new com.verimatrix.schemas.omitypes.Package();
            _returnPackagesVal1.setSmsPackageId("SmsPackageId-1859673396");
            _returnPackagesVal1.setDescription("Description-1729275878");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnPackagesVal1PackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnPackagesVal1PackageAttributes.setOperatorId("OperatorId254250879");
            _returnPackagesVal1PackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-1266509643");
            _returnPackagesVal1.setPackageAttributes(_returnPackagesVal1PackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnPackagesVal1PackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnPackagesVal1PackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnPackagesVal1PackageParameters.getPackageParameter().addAll(_returnPackagesVal1PackageParametersPackageParameter);
            _returnPackagesVal1.setPackageParameters(_returnPackagesVal1PackageParameters);
            _returnPackages.add(_returnPackagesVal1);
            _return.getPackages().addAll(_returnPackages);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#modifyEntitlements(com.verimatrix.schemas.omitypes.EntitlementList  entitlementList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList modifyEntitlements(com.verimatrix.schemas.omitypes.EntitlementList entitlementList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifyEntitlements");
        System.out.println(entitlementList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId319875681");
            _returnResultVal1.setResultCode(-519735219);
            _returnResultVal1.setResultText("ResultText-1189656606");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#stopPreEntitlements(com.verimatrix.schemas.omitypes.EntitledEntity  entitledEntity ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result stopPreEntitlements(com.verimatrix.schemas.omitypes.EntitledEntity entitledEntity,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation stopPreEntitlements");
        System.out.println(entitledEntity);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId1826096763");
            _return.setResultCode(-548048643);
            _return.setResultText("ResultText1087130298");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id734364033");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#modifyPackages(com.verimatrix.schemas.omitypes.PackageList  packageList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList modifyPackages(com.verimatrix.schemas.omitypes.PackageList packageList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation modifyPackages");
        System.out.println(packageList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-1791012960");
            _returnResultVal1.setResultCode(-701470574);
            _returnResultVal1.setResultText("ResultText1559036665");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#addEntitlements(com.verimatrix.schemas.omitypes.EntitlementList  entitlementList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addEntitlements(com.verimatrix.schemas.omitypes.EntitlementList entitlementList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addEntitlements");
        System.out.println(entitlementList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-1026909886");
            _returnResultVal1.setResultCode(-1480325506);
            _returnResultVal1.setResultText("ResultText354053997");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getPackageEvents(com.verimatrix.schemas.omitypes.PackageEventQuery  packageEventQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.PackageEventResult getPackageEvents(com.verimatrix.schemas.omitypes.PackageEventQuery packageEventQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getPackageEvents");
        System.out.println(packageEventQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.PackageEventResult _return = new com.verimatrix.schemas.omitypes.PackageEventResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-17193406");
            _returnResult.setResultCode(1183059254);
            _returnResult.setResultText("ResultText1120273680");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id-976597025");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.Package _returnPackage = new com.verimatrix.schemas.omitypes.Package();
            _returnPackage.setSmsPackageId("SmsPackageId-937821116");
            _returnPackage.setDescription("Description140476118");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnPackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnPackagePackageAttributes.setOperatorId("OperatorId-1482523668");
            _returnPackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId1351587359");
            _returnPackage.setPackageAttributes(_returnPackagePackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnPackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnPackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnPackagePackageParameters.getPackageParameter().addAll(_returnPackagePackageParametersPackageParameter);
            _returnPackage.setPackageParameters(_returnPackagePackageParameters);
            _return.setPackage(_returnPackage);
            java.util.List<com.verimatrix.schemas.omitypes.Event> _returnEvents = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
            com.verimatrix.schemas.omitypes.Event _returnEventsVal1 = new com.verimatrix.schemas.omitypes.Event();
            _returnEventsVal1.setSmsEventId("SmsEventId-361219787");
            _returnEventsVal1.setSmsContentId("SmsContentId-1721952881");
            _returnEventsVal1.setSmsNetworkId("SmsNetworkId-563446673");
            _returnEventsVal1.setExclusive(false);
            _returnEventsVal1.setPreStartDuration(1409660202);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEventsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEventsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEventsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEventsVal1.setTimePeriodRule(_returnEventsVal1TimePeriodRule);
            _returnEventsVal1.setRatingLevel(Integer.valueOf(-1778973313));
            com.verimatrix.schemas.omitypes.FingerprintMessage _returnEventsVal1FingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
            java.util.List<com.verimatrix.schemas.omitypes.MessageText> _returnEventsVal1FingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
            _returnEventsVal1FingerprintMessage.getText().addAll(_returnEventsVal1FingerprintMessageText);
            _returnEventsVal1.setFingerprintMessage(_returnEventsVal1FingerprintMessage);
            com.verimatrix.schemas.omitypes.EventParameters _returnEventsVal1EventParameters = new com.verimatrix.schemas.omitypes.EventParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEventsVal1EventParametersEventParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEventsVal1EventParameters.getEventParameter().addAll(_returnEventsVal1EventParametersEventParameter);
            _returnEventsVal1.setEventParameters(_returnEventsVal1EventParameters);
            _returnEvents.add(_returnEventsVal1);
            _return.getEvents().addAll(_returnEvents);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#removeEventsFromPackage(com.verimatrix.schemas.omitypes.Package  _package ,)com.verimatrix.schemas.omitypes.EventList  eventList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removeEventsFromPackage(com.verimatrix.schemas.omitypes.Package _package,com.verimatrix.schemas.omitypes.EventList eventList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removeEventsFromPackage");
        System.out.println(_package);
        System.out.println(eventList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId-1086623175");
            _returnResultVal1.setResultCode(1567624572);
            _returnResultVal1.setResultText("ResultText335758503");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#addEventsToPackage(com.verimatrix.schemas.omitypes.Package  _package ,)com.verimatrix.schemas.omitypes.EventList  eventList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addEventsToPackage(com.verimatrix.schemas.omitypes.Package _package,com.verimatrix.schemas.omitypes.EventList eventList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addEventsToPackage");
        System.out.println(_package);
        System.out.println(eventList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId1630813825");
            _returnResultVal1.setResultCode(841039835);
            _returnResultVal1.setResultText("ResultText1819651338");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getEntitlementList(com.verimatrix.schemas.omitypes.EntitlementListQuery  entitlementListQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.EntitlementListResult getEntitlementList(com.verimatrix.schemas.omitypes.EntitlementListQuery entitlementListQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getEntitlementList");
        System.out.println(entitlementListQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.EntitlementListResult _return = new com.verimatrix.schemas.omitypes.EntitlementListResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1218574726");
            _returnResult.setResultCode(1887995751);
            _returnResult.setResultText("ResultText-256838961");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id1071732432");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            java.util.List<com.verimatrix.schemas.omitypes.DeviceData> _returnEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DeviceData>();
            com.verimatrix.schemas.omitypes.DeviceData _returnEntitlementsVal1 = new com.verimatrix.schemas.omitypes.DeviceData();
            com.verimatrix.schemas.omitypes.Entitlement _returnEntitlementsVal1Entitlement = new com.verimatrix.schemas.omitypes.Entitlement();
            _returnEntitlementsVal1Entitlement.setSmsEntitlementId("SmsEntitlementId-945112380");
            com.verimatrix.schemas.omitypes.Package _returnEntitlementsVal1EntitlementPackage = new com.verimatrix.schemas.omitypes.Package();
            _returnEntitlementsVal1EntitlementPackage.setSmsPackageId("SmsPackageId-880506491");
            _returnEntitlementsVal1EntitlementPackage.setDescription("Description604390056");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnEntitlementsVal1EntitlementPackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setOperatorId("OperatorId86461344");
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-1030293673");
            _returnEntitlementsVal1EntitlementPackage.setPackageAttributes(_returnEntitlementsVal1EntitlementPackagePackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnEntitlementsVal1EntitlementPackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEntitlementsVal1EntitlementPackagePackageParameters.getPackageParameter().addAll(_returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter);
            _returnEntitlementsVal1EntitlementPackage.setPackageParameters(_returnEntitlementsVal1EntitlementPackagePackageParameters);
            _returnEntitlementsVal1Entitlement.setPackage(_returnEntitlementsVal1EntitlementPackage);
            com.verimatrix.schemas.omitypes.EntitledEntity _returnEntitlementsVal1EntitlementEntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
            com.verimatrix.schemas.omitypes.EntityType _returnEntitlementsVal1EntitlementEntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DEVICE;
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityType(_returnEntitlementsVal1EntitlementEntitledEntityEntityType);
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityId("EntityId-37924983");
            _returnEntitlementsVal1Entitlement.setEntitledEntity(_returnEntitlementsVal1EntitlementEntitledEntity);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEntitlementsVal1EntitlementTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEntitlementsVal1EntitlementTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEntitlementsVal1EntitlementTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEntitlementsVal1Entitlement.setTimePeriodRule(_returnEntitlementsVal1EntitlementTimePeriodRule);
            _returnEntitlementsVal1.setEntitlement(_returnEntitlementsVal1Entitlement);
            java.util.List<com.verimatrix.schemas.omitypes.Event> _returnEntitlementsVal1Events = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
            _returnEntitlementsVal1.getEvents().addAll(_returnEntitlementsVal1Events);
            _returnEntitlements.add(_returnEntitlementsVal1);
            _return.getEntitlements().addAll(_returnEntitlements);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getDeviceEntitlements(com.verimatrix.schemas.omitypes.DeviceEntitlementQuery  entitlementQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DeviceEntitlementResult getDeviceEntitlements(com.verimatrix.schemas.omitypes.DeviceEntitlementQuery entitlementQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getDeviceEntitlements");
        System.out.println(entitlementQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DeviceEntitlementResult _return = new com.verimatrix.schemas.omitypes.DeviceEntitlementResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId-1008204598");
            _returnResult.setResultCode(-1790390969);
            _returnResult.setResultText("ResultText-1938488806");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id908415963");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.Device _returnDevice = new com.verimatrix.schemas.omitypes.Device();
            _returnDevice.setSmsDeviceId("SmsDeviceId-1893886526");
            _returnDevice.setSmsNetworkId("SmsNetworkId-1919241285");
            com.verimatrix.schemas.omitypes.DeviceType _returnDeviceDeviceType = com.verimatrix.schemas.omitypes.DeviceType.PROF_RECEIVER;
            _returnDevice.setDeviceType(_returnDeviceDeviceType);
            _returnDevice.setNetworkDeviceId("NetworkDeviceId1954561338");
            byte[] _returnDeviceSmsAuthenticator = new byte[] {};
            _returnDevice.setSmsAuthenticator(_returnDeviceSmsAuthenticator);
            _return.setDevice(_returnDevice);
            java.util.List<com.verimatrix.schemas.omitypes.DeviceData> _returnEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DeviceData>();
            com.verimatrix.schemas.omitypes.DeviceData _returnEntitlementsVal1 = new com.verimatrix.schemas.omitypes.DeviceData();
            com.verimatrix.schemas.omitypes.Entitlement _returnEntitlementsVal1Entitlement = new com.verimatrix.schemas.omitypes.Entitlement();
            _returnEntitlementsVal1Entitlement.setSmsEntitlementId("SmsEntitlementId-1534393344");
            com.verimatrix.schemas.omitypes.Package _returnEntitlementsVal1EntitlementPackage = new com.verimatrix.schemas.omitypes.Package();
            _returnEntitlementsVal1EntitlementPackage.setSmsPackageId("SmsPackageId-2085958653");
            _returnEntitlementsVal1EntitlementPackage.setDescription("Description2099673663");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnEntitlementsVal1EntitlementPackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setOperatorId("OperatorId-1964089169");
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-336676569");
            _returnEntitlementsVal1EntitlementPackage.setPackageAttributes(_returnEntitlementsVal1EntitlementPackagePackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnEntitlementsVal1EntitlementPackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEntitlementsVal1EntitlementPackagePackageParameters.getPackageParameter().addAll(_returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter);
            _returnEntitlementsVal1EntitlementPackage.setPackageParameters(_returnEntitlementsVal1EntitlementPackagePackageParameters);
            _returnEntitlementsVal1Entitlement.setPackage(_returnEntitlementsVal1EntitlementPackage);
            com.verimatrix.schemas.omitypes.EntitledEntity _returnEntitlementsVal1EntitlementEntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
            com.verimatrix.schemas.omitypes.EntityType _returnEntitlementsVal1EntitlementEntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DEVICE;
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityType(_returnEntitlementsVal1EntitlementEntitledEntityEntityType);
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityId("EntityId-479188081");
            _returnEntitlementsVal1Entitlement.setEntitledEntity(_returnEntitlementsVal1EntitlementEntitledEntity);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEntitlementsVal1EntitlementTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEntitlementsVal1EntitlementTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.852+09:00"));
            _returnEntitlementsVal1EntitlementTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.868+09:00"));
            _returnEntitlementsVal1Entitlement.setTimePeriodRule(_returnEntitlementsVal1EntitlementTimePeriodRule);
            _returnEntitlementsVal1.setEntitlement(_returnEntitlementsVal1Entitlement);
            java.util.List<com.verimatrix.schemas.omitypes.Event> _returnEntitlementsVal1Events = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
            _returnEntitlementsVal1.getEvents().addAll(_returnEntitlementsVal1Events);
            _returnEntitlements.add(_returnEntitlementsVal1);
            _return.getEntitlements().addAll(_returnEntitlements);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#removePackages(com.verimatrix.schemas.omitypes.PackageList  packageList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList removePackages(com.verimatrix.schemas.omitypes.PackageList packageList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removePackages");
        System.out.println(packageList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId233094692");
            _returnResultVal1.setResultCode(2078765929);
            _returnResultVal1.setResultText("ResultText-1282976930");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#getDomainEntitlements(com.verimatrix.schemas.omitypes.DomainEntitlementQuery  entitlementQuery ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.DomainEntitlementResult getDomainEntitlements(com.verimatrix.schemas.omitypes.DomainEntitlementQuery entitlementQuery,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation getDomainEntitlements");
        System.out.println(entitlementQuery);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.DomainEntitlementResult _return = new com.verimatrix.schemas.omitypes.DomainEntitlementResult();
            com.verimatrix.schemas.omitypes.Result _returnResult = new com.verimatrix.schemas.omitypes.Result();
            _returnResult.setResultId("ResultId172775161");
            _returnResult.setResultCode(-906000620);
            _returnResult.setResultText("ResultText797792297");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultResultDataVal1.setId("Id1526590997");
            byte[] _returnResultResultDataVal1Data = new byte[] {};
            _returnResultResultDataVal1.setData(_returnResultResultDataVal1Data);
            _returnResultResultData.add(_returnResultResultDataVal1);
            _returnResult.getResultData().addAll(_returnResultResultData);
            _return.setResult(_returnResult);
            com.verimatrix.schemas.omitypes.Domain _returnDomain = new com.verimatrix.schemas.omitypes.Domain();
            _returnDomain.setSmsDomainId("SmsDomainId1422243523");
            _returnDomain.setMaxDevices(-1981162367);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnDomainTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnDomainTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.868+09:00"));
            _returnDomainTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.868+09:00"));
            _returnDomain.setTimePeriodRule(_returnDomainTimePeriodRule);
            _returnDomain.setDomainAddress(Integer.valueOf(-742978335));
            _return.setDomain(_returnDomain);
            java.util.List<com.verimatrix.schemas.omitypes.DeviceData> _returnEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.DeviceData>();
            com.verimatrix.schemas.omitypes.DeviceData _returnEntitlementsVal1 = new com.verimatrix.schemas.omitypes.DeviceData();
            com.verimatrix.schemas.omitypes.Entitlement _returnEntitlementsVal1Entitlement = new com.verimatrix.schemas.omitypes.Entitlement();
            _returnEntitlementsVal1Entitlement.setSmsEntitlementId("SmsEntitlementId-2137273647");
            com.verimatrix.schemas.omitypes.Package _returnEntitlementsVal1EntitlementPackage = new com.verimatrix.schemas.omitypes.Package();
            _returnEntitlementsVal1EntitlementPackage.setSmsPackageId("SmsPackageId1801612499");
            _returnEntitlementsVal1EntitlementPackage.setDescription("Description1278146603");
            com.verimatrix.schemas.omitypes.PackageAttributes _returnEntitlementsVal1EntitlementPackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setOperatorId("OperatorId268237381");
            _returnEntitlementsVal1EntitlementPackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-543127906");
            _returnEntitlementsVal1EntitlementPackage.setPackageAttributes(_returnEntitlementsVal1EntitlementPackagePackageAttributes);
            com.verimatrix.schemas.omitypes.PackageParameters _returnEntitlementsVal1EntitlementPackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
            java.util.List<com.verimatrix.schemas.omitypes.Parameter> _returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
            _returnEntitlementsVal1EntitlementPackagePackageParameters.getPackageParameter().addAll(_returnEntitlementsVal1EntitlementPackagePackageParametersPackageParameter);
            _returnEntitlementsVal1EntitlementPackage.setPackageParameters(_returnEntitlementsVal1EntitlementPackagePackageParameters);
            _returnEntitlementsVal1Entitlement.setPackage(_returnEntitlementsVal1EntitlementPackage);
            com.verimatrix.schemas.omitypes.EntitledEntity _returnEntitlementsVal1EntitlementEntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
            com.verimatrix.schemas.omitypes.EntityType _returnEntitlementsVal1EntitlementEntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DEVICE;
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityType(_returnEntitlementsVal1EntitlementEntitledEntityEntityType);
            _returnEntitlementsVal1EntitlementEntitledEntity.setEntityId("EntityId-1252510466");
            _returnEntitlementsVal1Entitlement.setEntitledEntity(_returnEntitlementsVal1EntitlementEntitledEntity);
            com.verimatrix.schemas.omitypes.TimePeriodRule _returnEntitlementsVal1EntitlementTimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
            _returnEntitlementsVal1EntitlementTimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.868+09:00"));
            _returnEntitlementsVal1EntitlementTimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.868+09:00"));
            _returnEntitlementsVal1Entitlement.setTimePeriodRule(_returnEntitlementsVal1EntitlementTimePeriodRule);
            _returnEntitlementsVal1.setEntitlement(_returnEntitlementsVal1Entitlement);
            java.util.List<com.verimatrix.schemas.omitypes.Event> _returnEntitlementsVal1Events = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
            _returnEntitlementsVal1.getEvents().addAll(_returnEntitlementsVal1Events);
            _returnEntitlements.add(_returnEntitlementsVal1);
            _return.getEntitlements().addAll(_returnEntitlements);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.EntitlementMgmt#addPackages(com.verimatrix.schemas.omitypes.PackageList  packageList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.ResultList addPackages(com.verimatrix.schemas.omitypes.PackageList packageList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation addPackages");
        System.out.println(packageList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.ResultList _return = new com.verimatrix.schemas.omitypes.ResultList();
            java.util.List<com.verimatrix.schemas.omitypes.Result> _returnResult = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Result>();
            com.verimatrix.schemas.omitypes.Result _returnResultVal1 = new com.verimatrix.schemas.omitypes.Result();
            _returnResultVal1.setResultId("ResultId1544232360");
            _returnResultVal1.setResultCode(-527748247);
            _returnResultVal1.setResultText("ResultText-1827541927");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultVal1ResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            _returnResultVal1.getResultData().addAll(_returnResultVal1ResultData);
            _returnResult.add(_returnResultVal1);
            _return.getResult().addAll(_returnResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
