package com.verimatrix.omi;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.993+09:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "EntitlementMgmtService", 
                  wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                  targetNamespace = "http://www.verimatrix.com/omi") 
public class EntitlementMgmtService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.verimatrix.com/omi", "EntitlementMgmtService");
    public final static QName EntitlementMgmt = new QName("http://www.verimatrix.com/omi", "EntitlementMgmt");
    static {
    	URL url = EntitlementMgmtService.class.getClassLoader().getResource("com/verimatrix/omi/wsdl/OMI.wsdl");
        if (url == null) {
          java.util.logging.Logger.getLogger(EntitlementMgmtService.class.getName())
              .log(java.util.logging.Level.INFO,
                   "Can not initialize the default wsdl from {0}", "classpath:com/verimatrix/omi/wsdl/OMI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EntitlementMgmtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EntitlementMgmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntitlementMgmtService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EntitlementMgmtService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EntitlementMgmtService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EntitlementMgmtService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EntitlementMgmt
     */
    @WebEndpoint(name = "EntitlementMgmt")
    public EntitlementMgmt getEntitlementMgmt() {
        return super.getPort(EntitlementMgmt, EntitlementMgmt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntitlementMgmt
     */
    @WebEndpoint(name = "EntitlementMgmt")
    public EntitlementMgmt getEntitlementMgmt(WebServiceFeature... features) {
        return super.getPort(EntitlementMgmt, EntitlementMgmt.class, features);
    }

}
