
package com.verimatrix.omi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.649+09:00
 * Generated source version: 2.7.13
 * 
 */
public final class EntitlementMgmt_EntitlementMgmt_Client {

    private static final QName SERVICE_NAME = new QName("http://www.verimatrix.com/omi", "EntitlementMgmtService");

    private EntitlementMgmt_EntitlementMgmt_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EntitlementMgmtService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EntitlementMgmtService ss = new EntitlementMgmtService(wsdlURL, SERVICE_NAME);
        EntitlementMgmt port = ss.getEntitlementMgmt();  
        
        {
        System.out.println("Invoking removeEntitlements...");
        com.verimatrix.schemas.omitypes.EntitlementList _removeEntitlements_entitlementList = new com.verimatrix.schemas.omitypes.EntitlementList();
        java.util.List<com.verimatrix.schemas.omitypes.Entitlement> _removeEntitlements_entitlementListEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Entitlement>();
        com.verimatrix.schemas.omitypes.Entitlement _removeEntitlements_entitlementListEntitlementsVal1 = new com.verimatrix.schemas.omitypes.Entitlement();
        _removeEntitlements_entitlementListEntitlementsVal1.setSmsEntitlementId("SmsEntitlementId409763264");
        com.verimatrix.schemas.omitypes.Package _removeEntitlements_entitlementListEntitlementsVal1Package = new com.verimatrix.schemas.omitypes.Package();
        _removeEntitlements_entitlementListEntitlementsVal1Package.setSmsPackageId("SmsPackageId-576626892");
        _removeEntitlements_entitlementListEntitlementsVal1Package.setDescription("Description-394422515");
        com.verimatrix.schemas.omitypes.PackageAttributes _removeEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _removeEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes.setOperatorId("OperatorId2126547371");
        _removeEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId2084103447");
        _removeEntitlements_entitlementListEntitlementsVal1Package.setPackageAttributes(_removeEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _removeEntitlements_entitlementListEntitlementsVal1PackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _removeEntitlements_entitlementListEntitlementsVal1PackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _removeEntitlements_entitlementListEntitlementsVal1PackagePackageParameters.getPackageParameter().addAll(_removeEntitlements_entitlementListEntitlementsVal1PackagePackageParametersPackageParameter);
        _removeEntitlements_entitlementListEntitlementsVal1Package.setPackageParameters(_removeEntitlements_entitlementListEntitlementsVal1PackagePackageParameters);
        _removeEntitlements_entitlementListEntitlementsVal1.setPackage(_removeEntitlements_entitlementListEntitlementsVal1Package);
        com.verimatrix.schemas.omitypes.EntitledEntity _removeEntitlements_entitlementListEntitlementsVal1EntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
        com.verimatrix.schemas.omitypes.EntityType _removeEntitlements_entitlementListEntitlementsVal1EntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DOMAIN;
        _removeEntitlements_entitlementListEntitlementsVal1EntitledEntity.setEntityType(_removeEntitlements_entitlementListEntitlementsVal1EntitledEntityEntityType);
        _removeEntitlements_entitlementListEntitlementsVal1EntitledEntity.setEntityId("EntityId1612848950");
        _removeEntitlements_entitlementListEntitlementsVal1.setEntitledEntity(_removeEntitlements_entitlementListEntitlementsVal1EntitledEntity);
        com.verimatrix.schemas.omitypes.TimePeriodRule _removeEntitlements_entitlementListEntitlementsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _removeEntitlements_entitlementListEntitlementsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _removeEntitlements_entitlementListEntitlementsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _removeEntitlements_entitlementListEntitlementsVal1.setTimePeriodRule(_removeEntitlements_entitlementListEntitlementsVal1TimePeriodRule);
        _removeEntitlements_entitlementListEntitlements.add(_removeEntitlements_entitlementListEntitlementsVal1);
        _removeEntitlements_entitlementList.getEntitlements().addAll(_removeEntitlements_entitlementListEntitlements);
        com.verimatrix.schemas.omitypes.SessionHandle _removeEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeEntitlements_sessionHandle.setHandle("Handle1137397576");
        com.verimatrix.schemas.omitypes.ResultList _removeEntitlements__return = port.removeEntitlements(_removeEntitlements_entitlementList, _removeEntitlements_sessionHandle);
        System.out.println("removeEntitlements.result=" + _removeEntitlements__return);


        }
        {
        System.out.println("Invoking removeAllEntitlements...");
        com.verimatrix.schemas.omitypes.EntitledEntityList _removeAllEntitlements_entitledEntityList = new com.verimatrix.schemas.omitypes.EntitledEntityList();
        java.util.List<com.verimatrix.schemas.omitypes.EntitledEntity> _removeAllEntitlements_entitledEntityListEntitledEntities = new java.util.ArrayList<com.verimatrix.schemas.omitypes.EntitledEntity>();
        com.verimatrix.schemas.omitypes.EntitledEntity _removeAllEntitlements_entitledEntityListEntitledEntitiesVal1 = new com.verimatrix.schemas.omitypes.EntitledEntity();
        com.verimatrix.schemas.omitypes.EntityType _removeAllEntitlements_entitledEntityListEntitledEntitiesVal1EntityType = com.verimatrix.schemas.omitypes.EntityType.DEVICE;
        _removeAllEntitlements_entitledEntityListEntitledEntitiesVal1.setEntityType(_removeAllEntitlements_entitledEntityListEntitledEntitiesVal1EntityType);
        _removeAllEntitlements_entitledEntityListEntitledEntitiesVal1.setEntityId("EntityId-207027355");
        _removeAllEntitlements_entitledEntityListEntitledEntities.add(_removeAllEntitlements_entitledEntityListEntitledEntitiesVal1);
        _removeAllEntitlements_entitledEntityList.getEntitledEntities().addAll(_removeAllEntitlements_entitledEntityListEntitledEntities);
        com.verimatrix.schemas.omitypes.SessionHandle _removeAllEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeAllEntitlements_sessionHandle.setHandle("Handle-492125525");
        com.verimatrix.schemas.omitypes.ResultList _removeAllEntitlements__return = port.removeAllEntitlements(_removeAllEntitlements_entitledEntityList, _removeAllEntitlements_sessionHandle);
        System.out.println("removeAllEntitlements.result=" + _removeAllEntitlements__return);


        }
        {
        System.out.println("Invoking getRetailerEntitlements...");
        com.verimatrix.schemas.omitypes.RetailerEntitlementQuery _getRetailerEntitlements_entitlementQuery = new com.verimatrix.schemas.omitypes.RetailerEntitlementQuery();
        _getRetailerEntitlements_entitlementQuery.setRetailerId("RetailerId-670500898");
        com.verimatrix.schemas.omitypes.SessionHandle _getRetailerEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getRetailerEntitlements_sessionHandle.setHandle("Handle1922731560");
        com.verimatrix.schemas.omitypes.RetailerEntitlementResult _getRetailerEntitlements__return = port.getRetailerEntitlements(_getRetailerEntitlements_entitlementQuery, _getRetailerEntitlements_sessionHandle);
        System.out.println("getRetailerEntitlements.result=" + _getRetailerEntitlements__return);


        }
        {
        System.out.println("Invoking getEventPackages...");
        com.verimatrix.schemas.omitypes.EventPackageQuery _getEventPackages_eventPackageQuery = new com.verimatrix.schemas.omitypes.EventPackageQuery();
        _getEventPackages_eventPackageQuery.setSmsEventId("SmsEventId1172659410");
        com.verimatrix.schemas.omitypes.SessionHandle _getEventPackages_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getEventPackages_sessionHandle.setHandle("Handle1991161655");
        com.verimatrix.schemas.omitypes.EventPackageResult _getEventPackages__return = port.getEventPackages(_getEventPackages_eventPackageQuery, _getEventPackages_sessionHandle);
        System.out.println("getEventPackages.result=" + _getEventPackages__return);


        }
        {
        System.out.println("Invoking getPackageList...");
        com.verimatrix.schemas.omitypes.PackageListQuery _getPackageList_packageListQuery = new com.verimatrix.schemas.omitypes.PackageListQuery();
        _getPackageList_packageListQuery.setSmsPackageId("SmsPackageId2075944674");
        _getPackageList_packageListQuery.setPackageCount(639764284);
        com.verimatrix.schemas.omitypes.SessionHandle _getPackageList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getPackageList_sessionHandle.setHandle("Handle-823483726");
        com.verimatrix.schemas.omitypes.PackageListResult _getPackageList__return = port.getPackageList(_getPackageList_packageListQuery, _getPackageList_sessionHandle);
        System.out.println("getPackageList.result=" + _getPackageList__return);


        }
        {
        System.out.println("Invoking modifyEntitlements...");
        com.verimatrix.schemas.omitypes.EntitlementList _modifyEntitlements_entitlementList = new com.verimatrix.schemas.omitypes.EntitlementList();
        java.util.List<com.verimatrix.schemas.omitypes.Entitlement> _modifyEntitlements_entitlementListEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Entitlement>();
        com.verimatrix.schemas.omitypes.Entitlement _modifyEntitlements_entitlementListEntitlementsVal1 = new com.verimatrix.schemas.omitypes.Entitlement();
        _modifyEntitlements_entitlementListEntitlementsVal1.setSmsEntitlementId("SmsEntitlementId1780217059");
        com.verimatrix.schemas.omitypes.Package _modifyEntitlements_entitlementListEntitlementsVal1Package = new com.verimatrix.schemas.omitypes.Package();
        _modifyEntitlements_entitlementListEntitlementsVal1Package.setSmsPackageId("SmsPackageId1353078002");
        _modifyEntitlements_entitlementListEntitlementsVal1Package.setDescription("Description675107925");
        com.verimatrix.schemas.omitypes.PackageAttributes _modifyEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _modifyEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes.setOperatorId("OperatorId73805551");
        _modifyEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId500348279");
        _modifyEntitlements_entitlementListEntitlementsVal1Package.setPackageAttributes(_modifyEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _modifyEntitlements_entitlementListEntitlementsVal1PackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _modifyEntitlements_entitlementListEntitlementsVal1PackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _modifyEntitlements_entitlementListEntitlementsVal1PackagePackageParameters.getPackageParameter().addAll(_modifyEntitlements_entitlementListEntitlementsVal1PackagePackageParametersPackageParameter);
        _modifyEntitlements_entitlementListEntitlementsVal1Package.setPackageParameters(_modifyEntitlements_entitlementListEntitlementsVal1PackagePackageParameters);
        _modifyEntitlements_entitlementListEntitlementsVal1.setPackage(_modifyEntitlements_entitlementListEntitlementsVal1Package);
        com.verimatrix.schemas.omitypes.EntitledEntity _modifyEntitlements_entitlementListEntitlementsVal1EntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
        com.verimatrix.schemas.omitypes.EntityType _modifyEntitlements_entitlementListEntitlementsVal1EntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DEVICE;
        _modifyEntitlements_entitlementListEntitlementsVal1EntitledEntity.setEntityType(_modifyEntitlements_entitlementListEntitlementsVal1EntitledEntityEntityType);
        _modifyEntitlements_entitlementListEntitlementsVal1EntitledEntity.setEntityId("EntityId522681818");
        _modifyEntitlements_entitlementListEntitlementsVal1.setEntitledEntity(_modifyEntitlements_entitlementListEntitlementsVal1EntitledEntity);
        com.verimatrix.schemas.omitypes.TimePeriodRule _modifyEntitlements_entitlementListEntitlementsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _modifyEntitlements_entitlementListEntitlementsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _modifyEntitlements_entitlementListEntitlementsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _modifyEntitlements_entitlementListEntitlementsVal1.setTimePeriodRule(_modifyEntitlements_entitlementListEntitlementsVal1TimePeriodRule);
        _modifyEntitlements_entitlementListEntitlements.add(_modifyEntitlements_entitlementListEntitlementsVal1);
        _modifyEntitlements_entitlementList.getEntitlements().addAll(_modifyEntitlements_entitlementListEntitlements);
        com.verimatrix.schemas.omitypes.SessionHandle _modifyEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifyEntitlements_sessionHandle.setHandle("Handle-1134065314");
        com.verimatrix.schemas.omitypes.ResultList _modifyEntitlements__return = port.modifyEntitlements(_modifyEntitlements_entitlementList, _modifyEntitlements_sessionHandle);
        System.out.println("modifyEntitlements.result=" + _modifyEntitlements__return);


        }
        {
        System.out.println("Invoking stopPreEntitlements...");
        com.verimatrix.schemas.omitypes.EntitledEntity _stopPreEntitlements_entitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
        com.verimatrix.schemas.omitypes.EntityType _stopPreEntitlements_entitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.RETAILER;
        _stopPreEntitlements_entitledEntity.setEntityType(_stopPreEntitlements_entitledEntityEntityType);
        _stopPreEntitlements_entitledEntity.setEntityId("EntityId-1325953821");
        com.verimatrix.schemas.omitypes.SessionHandle _stopPreEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _stopPreEntitlements_sessionHandle.setHandle("Handle-181130770");
        com.verimatrix.schemas.omitypes.Result _stopPreEntitlements__return = port.stopPreEntitlements(_stopPreEntitlements_entitledEntity, _stopPreEntitlements_sessionHandle);
        System.out.println("stopPreEntitlements.result=" + _stopPreEntitlements__return);


        }
        {
        System.out.println("Invoking modifyPackages...");
        com.verimatrix.schemas.omitypes.PackageList _modifyPackages_packageList = new com.verimatrix.schemas.omitypes.PackageList();
        java.util.List<com.verimatrix.schemas.omitypes.Package> _modifyPackages_packageListPackages = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Package>();
        com.verimatrix.schemas.omitypes.Package _modifyPackages_packageListPackagesVal1 = new com.verimatrix.schemas.omitypes.Package();
        _modifyPackages_packageListPackagesVal1.setSmsPackageId("SmsPackageId-1877651115");
        _modifyPackages_packageListPackagesVal1.setDescription("Description1733729812");
        com.verimatrix.schemas.omitypes.PackageAttributes _modifyPackages_packageListPackagesVal1PackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _modifyPackages_packageListPackagesVal1PackageAttributes.setOperatorId("OperatorId-2035048744");
        _modifyPackages_packageListPackagesVal1PackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-1990847975");
        _modifyPackages_packageListPackagesVal1.setPackageAttributes(_modifyPackages_packageListPackagesVal1PackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _modifyPackages_packageListPackagesVal1PackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _modifyPackages_packageListPackagesVal1PackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _modifyPackages_packageListPackagesVal1PackageParameters.getPackageParameter().addAll(_modifyPackages_packageListPackagesVal1PackageParametersPackageParameter);
        _modifyPackages_packageListPackagesVal1.setPackageParameters(_modifyPackages_packageListPackagesVal1PackageParameters);
        _modifyPackages_packageListPackages.add(_modifyPackages_packageListPackagesVal1);
        _modifyPackages_packageList.getPackages().addAll(_modifyPackages_packageListPackages);
        com.verimatrix.schemas.omitypes.SessionHandle _modifyPackages_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _modifyPackages_sessionHandle.setHandle("Handle2110696576");
        com.verimatrix.schemas.omitypes.ResultList _modifyPackages__return = port.modifyPackages(_modifyPackages_packageList, _modifyPackages_sessionHandle);
        System.out.println("modifyPackages.result=" + _modifyPackages__return);


        }
        {
        System.out.println("Invoking addEntitlements...");
        com.verimatrix.schemas.omitypes.EntitlementList _addEntitlements_entitlementList = new com.verimatrix.schemas.omitypes.EntitlementList();
        java.util.List<com.verimatrix.schemas.omitypes.Entitlement> _addEntitlements_entitlementListEntitlements = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Entitlement>();
        com.verimatrix.schemas.omitypes.Entitlement _addEntitlements_entitlementListEntitlementsVal1 = new com.verimatrix.schemas.omitypes.Entitlement();
        _addEntitlements_entitlementListEntitlementsVal1.setSmsEntitlementId("SmsEntitlementId1820373395");
        com.verimatrix.schemas.omitypes.Package _addEntitlements_entitlementListEntitlementsVal1Package = new com.verimatrix.schemas.omitypes.Package();
        _addEntitlements_entitlementListEntitlementsVal1Package.setSmsPackageId("SmsPackageId-995224924");
        _addEntitlements_entitlementListEntitlementsVal1Package.setDescription("Description-1041977561");
        com.verimatrix.schemas.omitypes.PackageAttributes _addEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _addEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes.setOperatorId("OperatorId-1376497932");
        _addEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId1463234479");
        _addEntitlements_entitlementListEntitlementsVal1Package.setPackageAttributes(_addEntitlements_entitlementListEntitlementsVal1PackagePackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _addEntitlements_entitlementListEntitlementsVal1PackagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _addEntitlements_entitlementListEntitlementsVal1PackagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _addEntitlements_entitlementListEntitlementsVal1PackagePackageParameters.getPackageParameter().addAll(_addEntitlements_entitlementListEntitlementsVal1PackagePackageParametersPackageParameter);
        _addEntitlements_entitlementListEntitlementsVal1Package.setPackageParameters(_addEntitlements_entitlementListEntitlementsVal1PackagePackageParameters);
        _addEntitlements_entitlementListEntitlementsVal1.setPackage(_addEntitlements_entitlementListEntitlementsVal1Package);
        com.verimatrix.schemas.omitypes.EntitledEntity _addEntitlements_entitlementListEntitlementsVal1EntitledEntity = new com.verimatrix.schemas.omitypes.EntitledEntity();
        com.verimatrix.schemas.omitypes.EntityType _addEntitlements_entitlementListEntitlementsVal1EntitledEntityEntityType = com.verimatrix.schemas.omitypes.EntityType.DOMAIN;
        _addEntitlements_entitlementListEntitlementsVal1EntitledEntity.setEntityType(_addEntitlements_entitlementListEntitlementsVal1EntitledEntityEntityType);
        _addEntitlements_entitlementListEntitlementsVal1EntitledEntity.setEntityId("EntityId-1380565168");
        _addEntitlements_entitlementListEntitlementsVal1.setEntitledEntity(_addEntitlements_entitlementListEntitlementsVal1EntitledEntity);
        com.verimatrix.schemas.omitypes.TimePeriodRule _addEntitlements_entitlementListEntitlementsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _addEntitlements_entitlementListEntitlementsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _addEntitlements_entitlementListEntitlementsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _addEntitlements_entitlementListEntitlementsVal1.setTimePeriodRule(_addEntitlements_entitlementListEntitlementsVal1TimePeriodRule);
        _addEntitlements_entitlementListEntitlements.add(_addEntitlements_entitlementListEntitlementsVal1);
        _addEntitlements_entitlementList.getEntitlements().addAll(_addEntitlements_entitlementListEntitlements);
        com.verimatrix.schemas.omitypes.SessionHandle _addEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addEntitlements_sessionHandle.setHandle("Handle-844009340");
        com.verimatrix.schemas.omitypes.ResultList _addEntitlements__return = port.addEntitlements(_addEntitlements_entitlementList, _addEntitlements_sessionHandle);
        System.out.println("addEntitlements.result=" + _addEntitlements__return);


        }
        {
        System.out.println("Invoking getPackageEvents...");
        com.verimatrix.schemas.omitypes.PackageEventQuery _getPackageEvents_packageEventQuery = new com.verimatrix.schemas.omitypes.PackageEventQuery();
        _getPackageEvents_packageEventQuery.setSmsPackageId("SmsPackageId902120557");
        com.verimatrix.schemas.omitypes.SessionHandle _getPackageEvents_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getPackageEvents_sessionHandle.setHandle("Handle338971287");
        com.verimatrix.schemas.omitypes.PackageEventResult _getPackageEvents__return = port.getPackageEvents(_getPackageEvents_packageEventQuery, _getPackageEvents_sessionHandle);
        System.out.println("getPackageEvents.result=" + _getPackageEvents__return);


        }
        {
        System.out.println("Invoking removeEventsFromPackage...");
        com.verimatrix.schemas.omitypes.Package _removeEventsFromPackage__package = new com.verimatrix.schemas.omitypes.Package();
        _removeEventsFromPackage__package.setSmsPackageId("SmsPackageId693209752");
        _removeEventsFromPackage__package.setDescription("Description-540130477");
        com.verimatrix.schemas.omitypes.PackageAttributes _removeEventsFromPackage__packagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _removeEventsFromPackage__packagePackageAttributes.setOperatorId("OperatorId194555884");
        _removeEventsFromPackage__packagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId1980833707");
        _removeEventsFromPackage__package.setPackageAttributes(_removeEventsFromPackage__packagePackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _removeEventsFromPackage__packagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _removeEventsFromPackage__packagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        com.verimatrix.schemas.omitypes.Parameter _removeEventsFromPackage__packagePackageParametersPackageParameterVal1 = new com.verimatrix.schemas.omitypes.Parameter();
        _removeEventsFromPackage__packagePackageParametersPackageParameterVal1.setKey("Key-1941108360");
        com.verimatrix.schemas.omitypes.ParameterValue _removeEventsFromPackage__packagePackageParametersPackageParameterVal1Value = new com.verimatrix.schemas.omitypes.ParameterValue();
        _removeEventsFromPackage__packagePackageParametersPackageParameterVal1Value.setValue("Value1645920170");
        com.verimatrix.schemas.omitypes.ValueType _removeEventsFromPackage__packagePackageParametersPackageParameterVal1ValueValueType = com.verimatrix.schemas.omitypes.ValueType.DATETIME;
        _removeEventsFromPackage__packagePackageParametersPackageParameterVal1Value.setValueType(_removeEventsFromPackage__packagePackageParametersPackageParameterVal1ValueValueType);
        _removeEventsFromPackage__packagePackageParametersPackageParameterVal1.setValue(_removeEventsFromPackage__packagePackageParametersPackageParameterVal1Value);
        _removeEventsFromPackage__packagePackageParametersPackageParameter.add(_removeEventsFromPackage__packagePackageParametersPackageParameterVal1);
        _removeEventsFromPackage__packagePackageParameters.getPackageParameter().addAll(_removeEventsFromPackage__packagePackageParametersPackageParameter);
        _removeEventsFromPackage__package.setPackageParameters(_removeEventsFromPackage__packagePackageParameters);
        com.verimatrix.schemas.omitypes.EventList _removeEventsFromPackage_eventList = new com.verimatrix.schemas.omitypes.EventList();
        java.util.List<com.verimatrix.schemas.omitypes.Event> _removeEventsFromPackage_eventListEvents = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
        com.verimatrix.schemas.omitypes.Event _removeEventsFromPackage_eventListEventsVal1 = new com.verimatrix.schemas.omitypes.Event();
        _removeEventsFromPackage_eventListEventsVal1.setSmsEventId("SmsEventId1267123478");
        _removeEventsFromPackage_eventListEventsVal1.setSmsContentId("SmsContentId1546080702");
        _removeEventsFromPackage_eventListEventsVal1.setSmsNetworkId("SmsNetworkId-6694644");
        _removeEventsFromPackage_eventListEventsVal1.setExclusive(true);
        _removeEventsFromPackage_eventListEventsVal1.setPreStartDuration(489009148);
        com.verimatrix.schemas.omitypes.TimePeriodRule _removeEventsFromPackage_eventListEventsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _removeEventsFromPackage_eventListEventsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _removeEventsFromPackage_eventListEventsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _removeEventsFromPackage_eventListEventsVal1.setTimePeriodRule(_removeEventsFromPackage_eventListEventsVal1TimePeriodRule);
        _removeEventsFromPackage_eventListEventsVal1.setRatingLevel(Integer.valueOf(809430449));
        com.verimatrix.schemas.omitypes.FingerprintMessage _removeEventsFromPackage_eventListEventsVal1FingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
        java.util.List<com.verimatrix.schemas.omitypes.MessageText> _removeEventsFromPackage_eventListEventsVal1FingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
        _removeEventsFromPackage_eventListEventsVal1FingerprintMessage.getText().addAll(_removeEventsFromPackage_eventListEventsVal1FingerprintMessageText);
        _removeEventsFromPackage_eventListEventsVal1.setFingerprintMessage(_removeEventsFromPackage_eventListEventsVal1FingerprintMessage);
        com.verimatrix.schemas.omitypes.EventParameters _removeEventsFromPackage_eventListEventsVal1EventParameters = new com.verimatrix.schemas.omitypes.EventParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _removeEventsFromPackage_eventListEventsVal1EventParametersEventParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _removeEventsFromPackage_eventListEventsVal1EventParameters.getEventParameter().addAll(_removeEventsFromPackage_eventListEventsVal1EventParametersEventParameter);
        _removeEventsFromPackage_eventListEventsVal1.setEventParameters(_removeEventsFromPackage_eventListEventsVal1EventParameters);
        _removeEventsFromPackage_eventListEvents.add(_removeEventsFromPackage_eventListEventsVal1);
        _removeEventsFromPackage_eventList.getEvents().addAll(_removeEventsFromPackage_eventListEvents);
        com.verimatrix.schemas.omitypes.SessionHandle _removeEventsFromPackage_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removeEventsFromPackage_sessionHandle.setHandle("Handle-645762938");
        com.verimatrix.schemas.omitypes.ResultList _removeEventsFromPackage__return = port.removeEventsFromPackage(_removeEventsFromPackage__package, _removeEventsFromPackage_eventList, _removeEventsFromPackage_sessionHandle);
        System.out.println("removeEventsFromPackage.result=" + _removeEventsFromPackage__return);


        }
        {
        System.out.println("Invoking addEventsToPackage...");
        com.verimatrix.schemas.omitypes.Package _addEventsToPackage__package = new com.verimatrix.schemas.omitypes.Package();
        _addEventsToPackage__package.setSmsPackageId("SmsPackageId985168345");
        _addEventsToPackage__package.setDescription("Description1544177902");
        com.verimatrix.schemas.omitypes.PackageAttributes _addEventsToPackage__packagePackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _addEventsToPackage__packagePackageAttributes.setOperatorId("OperatorId-2075262600");
        _addEventsToPackage__packagePackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId1823250506");
        _addEventsToPackage__package.setPackageAttributes(_addEventsToPackage__packagePackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _addEventsToPackage__packagePackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _addEventsToPackage__packagePackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        com.verimatrix.schemas.omitypes.Parameter _addEventsToPackage__packagePackageParametersPackageParameterVal1 = new com.verimatrix.schemas.omitypes.Parameter();
        _addEventsToPackage__packagePackageParametersPackageParameterVal1.setKey("Key-1988726536");
        com.verimatrix.schemas.omitypes.ParameterValue _addEventsToPackage__packagePackageParametersPackageParameterVal1Value = new com.verimatrix.schemas.omitypes.ParameterValue();
        _addEventsToPackage__packagePackageParametersPackageParameterVal1Value.setValue("Value668036000");
        com.verimatrix.schemas.omitypes.ValueType _addEventsToPackage__packagePackageParametersPackageParameterVal1ValueValueType = com.verimatrix.schemas.omitypes.ValueType.DATETIME;
        _addEventsToPackage__packagePackageParametersPackageParameterVal1Value.setValueType(_addEventsToPackage__packagePackageParametersPackageParameterVal1ValueValueType);
        _addEventsToPackage__packagePackageParametersPackageParameterVal1.setValue(_addEventsToPackage__packagePackageParametersPackageParameterVal1Value);
        _addEventsToPackage__packagePackageParametersPackageParameter.add(_addEventsToPackage__packagePackageParametersPackageParameterVal1);
        _addEventsToPackage__packagePackageParameters.getPackageParameter().addAll(_addEventsToPackage__packagePackageParametersPackageParameter);
        _addEventsToPackage__package.setPackageParameters(_addEventsToPackage__packagePackageParameters);
        com.verimatrix.schemas.omitypes.EventList _addEventsToPackage_eventList = new com.verimatrix.schemas.omitypes.EventList();
        java.util.List<com.verimatrix.schemas.omitypes.Event> _addEventsToPackage_eventListEvents = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Event>();
        com.verimatrix.schemas.omitypes.Event _addEventsToPackage_eventListEventsVal1 = new com.verimatrix.schemas.omitypes.Event();
        _addEventsToPackage_eventListEventsVal1.setSmsEventId("SmsEventId-1017709442");
        _addEventsToPackage_eventListEventsVal1.setSmsContentId("SmsContentId-898505243");
        _addEventsToPackage_eventListEventsVal1.setSmsNetworkId("SmsNetworkId-836194849");
        _addEventsToPackage_eventListEventsVal1.setExclusive(true);
        _addEventsToPackage_eventListEventsVal1.setPreStartDuration(-1785100975);
        com.verimatrix.schemas.omitypes.TimePeriodRule _addEventsToPackage_eventListEventsVal1TimePeriodRule = new com.verimatrix.schemas.omitypes.TimePeriodRule();
        _addEventsToPackage_eventListEventsVal1TimePeriodRule.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _addEventsToPackage_eventListEventsVal1TimePeriodRule.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-11-20T18:42:57.665+09:00"));
        _addEventsToPackage_eventListEventsVal1.setTimePeriodRule(_addEventsToPackage_eventListEventsVal1TimePeriodRule);
        _addEventsToPackage_eventListEventsVal1.setRatingLevel(Integer.valueOf(489779365));
        com.verimatrix.schemas.omitypes.FingerprintMessage _addEventsToPackage_eventListEventsVal1FingerprintMessage = new com.verimatrix.schemas.omitypes.FingerprintMessage();
        java.util.List<com.verimatrix.schemas.omitypes.MessageText> _addEventsToPackage_eventListEventsVal1FingerprintMessageText = new java.util.ArrayList<com.verimatrix.schemas.omitypes.MessageText>();
        _addEventsToPackage_eventListEventsVal1FingerprintMessage.getText().addAll(_addEventsToPackage_eventListEventsVal1FingerprintMessageText);
        _addEventsToPackage_eventListEventsVal1.setFingerprintMessage(_addEventsToPackage_eventListEventsVal1FingerprintMessage);
        com.verimatrix.schemas.omitypes.EventParameters _addEventsToPackage_eventListEventsVal1EventParameters = new com.verimatrix.schemas.omitypes.EventParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _addEventsToPackage_eventListEventsVal1EventParametersEventParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _addEventsToPackage_eventListEventsVal1EventParameters.getEventParameter().addAll(_addEventsToPackage_eventListEventsVal1EventParametersEventParameter);
        _addEventsToPackage_eventListEventsVal1.setEventParameters(_addEventsToPackage_eventListEventsVal1EventParameters);
        _addEventsToPackage_eventListEvents.add(_addEventsToPackage_eventListEventsVal1);
        _addEventsToPackage_eventList.getEvents().addAll(_addEventsToPackage_eventListEvents);
        com.verimatrix.schemas.omitypes.SessionHandle _addEventsToPackage_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addEventsToPackage_sessionHandle.setHandle("Handle1806148033");
        com.verimatrix.schemas.omitypes.ResultList _addEventsToPackage__return = port.addEventsToPackage(_addEventsToPackage__package, _addEventsToPackage_eventList, _addEventsToPackage_sessionHandle);
        System.out.println("addEventsToPackage.result=" + _addEventsToPackage__return);


        }
        {
        System.out.println("Invoking getEntitlementList...");
        com.verimatrix.schemas.omitypes.EntitlementListQuery _getEntitlementList_entitlementListQuery = new com.verimatrix.schemas.omitypes.EntitlementListQuery();
        _getEntitlementList_entitlementListQuery.setSmsEntitlementId("SmsEntitlementId-788141698");
        com.verimatrix.schemas.omitypes.EntityType _getEntitlementList_entitlementListQueryEntityType = com.verimatrix.schemas.omitypes.EntityType.DEVICE;
        _getEntitlementList_entitlementListQuery.setEntityType(_getEntitlementList_entitlementListQueryEntityType);
        _getEntitlementList_entitlementListQuery.setEntitlementCount(2063935342);
        com.verimatrix.schemas.omitypes.SessionHandle _getEntitlementList_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getEntitlementList_sessionHandle.setHandle("Handle-960592099");
        com.verimatrix.schemas.omitypes.EntitlementListResult _getEntitlementList__return = port.getEntitlementList(_getEntitlementList_entitlementListQuery, _getEntitlementList_sessionHandle);
        System.out.println("getEntitlementList.result=" + _getEntitlementList__return);


        }
        {
        System.out.println("Invoking getDeviceEntitlements...");
        com.verimatrix.schemas.omitypes.DeviceEntitlementQuery _getDeviceEntitlements_entitlementQuery = new com.verimatrix.schemas.omitypes.DeviceEntitlementQuery();
        _getDeviceEntitlements_entitlementQuery.setSmsDeviceId("SmsDeviceId-1045440995");
        com.verimatrix.schemas.omitypes.SessionHandle _getDeviceEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDeviceEntitlements_sessionHandle.setHandle("Handle1792347894");
        com.verimatrix.schemas.omitypes.DeviceEntitlementResult _getDeviceEntitlements__return = port.getDeviceEntitlements(_getDeviceEntitlements_entitlementQuery, _getDeviceEntitlements_sessionHandle);
        System.out.println("getDeviceEntitlements.result=" + _getDeviceEntitlements__return);


        }
        {
        System.out.println("Invoking removePackages...");
        com.verimatrix.schemas.omitypes.PackageList _removePackages_packageList = new com.verimatrix.schemas.omitypes.PackageList();
        java.util.List<com.verimatrix.schemas.omitypes.Package> _removePackages_packageListPackages = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Package>();
        com.verimatrix.schemas.omitypes.Package _removePackages_packageListPackagesVal1 = new com.verimatrix.schemas.omitypes.Package();
        _removePackages_packageListPackagesVal1.setSmsPackageId("SmsPackageId-735124047");
        _removePackages_packageListPackagesVal1.setDescription("Description-648404931");
        com.verimatrix.schemas.omitypes.PackageAttributes _removePackages_packageListPackagesVal1PackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _removePackages_packageListPackagesVal1PackageAttributes.setOperatorId("OperatorId1533390210");
        _removePackages_packageListPackagesVal1PackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId1580740745");
        _removePackages_packageListPackagesVal1.setPackageAttributes(_removePackages_packageListPackagesVal1PackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _removePackages_packageListPackagesVal1PackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _removePackages_packageListPackagesVal1PackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _removePackages_packageListPackagesVal1PackageParameters.getPackageParameter().addAll(_removePackages_packageListPackagesVal1PackageParametersPackageParameter);
        _removePackages_packageListPackagesVal1.setPackageParameters(_removePackages_packageListPackagesVal1PackageParameters);
        _removePackages_packageListPackages.add(_removePackages_packageListPackagesVal1);
        _removePackages_packageList.getPackages().addAll(_removePackages_packageListPackages);
        com.verimatrix.schemas.omitypes.SessionHandle _removePackages_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _removePackages_sessionHandle.setHandle("Handle43614041");
        com.verimatrix.schemas.omitypes.ResultList _removePackages__return = port.removePackages(_removePackages_packageList, _removePackages_sessionHandle);
        System.out.println("removePackages.result=" + _removePackages__return);


        }
        {
        System.out.println("Invoking getDomainEntitlements...");
        com.verimatrix.schemas.omitypes.DomainEntitlementQuery _getDomainEntitlements_entitlementQuery = new com.verimatrix.schemas.omitypes.DomainEntitlementQuery();
        _getDomainEntitlements_entitlementQuery.setDomainId("DomainId-73163310");
        com.verimatrix.schemas.omitypes.SessionHandle _getDomainEntitlements_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _getDomainEntitlements_sessionHandle.setHandle("Handle1143543357");
        com.verimatrix.schemas.omitypes.DomainEntitlementResult _getDomainEntitlements__return = port.getDomainEntitlements(_getDomainEntitlements_entitlementQuery, _getDomainEntitlements_sessionHandle);
        System.out.println("getDomainEntitlements.result=" + _getDomainEntitlements__return);


        }
        {
        System.out.println("Invoking addPackages...");
        com.verimatrix.schemas.omitypes.PackageList _addPackages_packageList = new com.verimatrix.schemas.omitypes.PackageList();
        java.util.List<com.verimatrix.schemas.omitypes.Package> _addPackages_packageListPackages = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Package>();
        com.verimatrix.schemas.omitypes.Package _addPackages_packageListPackagesVal1 = new com.verimatrix.schemas.omitypes.Package();
        _addPackages_packageListPackagesVal1.setSmsPackageId("SmsPackageId-277328605");
        _addPackages_packageListPackagesVal1.setDescription("Description1337549909");
        com.verimatrix.schemas.omitypes.PackageAttributes _addPackages_packageListPackagesVal1PackageAttributes = new com.verimatrix.schemas.omitypes.PackageAttributes();
        _addPackages_packageListPackagesVal1PackageAttributes.setOperatorId("OperatorId-314649049");
        _addPackages_packageListPackagesVal1PackageAttributes.setExtendedAccessClassId("ExtendedAccessClassId-291719817");
        _addPackages_packageListPackagesVal1.setPackageAttributes(_addPackages_packageListPackagesVal1PackageAttributes);
        com.verimatrix.schemas.omitypes.PackageParameters _addPackages_packageListPackagesVal1PackageParameters = new com.verimatrix.schemas.omitypes.PackageParameters();
        java.util.List<com.verimatrix.schemas.omitypes.Parameter> _addPackages_packageListPackagesVal1PackageParametersPackageParameter = new java.util.ArrayList<com.verimatrix.schemas.omitypes.Parameter>();
        _addPackages_packageListPackagesVal1PackageParameters.getPackageParameter().addAll(_addPackages_packageListPackagesVal1PackageParametersPackageParameter);
        _addPackages_packageListPackagesVal1.setPackageParameters(_addPackages_packageListPackagesVal1PackageParameters);
        _addPackages_packageListPackages.add(_addPackages_packageListPackagesVal1);
        _addPackages_packageList.getPackages().addAll(_addPackages_packageListPackages);
        com.verimatrix.schemas.omitypes.SessionHandle _addPackages_sessionHandle = new com.verimatrix.schemas.omitypes.SessionHandle();
        _addPackages_sessionHandle.setHandle("Handle-1874148338");
        com.verimatrix.schemas.omitypes.ResultList _addPackages__return = port.addPackages(_addPackages_packageList, _addPackages_sessionHandle);
        System.out.println("addPackages.result=" + _addPackages__return);


        }

        System.exit(0);
    }

}
