
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.verimatrix.omi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-20T18:42:57.790+09:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "MessagingService",
                      portName = "Messaging",
                      targetNamespace = "http://www.verimatrix.com/omi",
                      wsdlLocation = "classpath:com/verimatrix/omi/wsdl/OMI.wsdl",
                      endpointInterface = "com.verimatrix.omi.Messaging")
                      
public class MessagingImpl implements Messaging {

    private static final Logger LOG = Logger.getLogger(MessagingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#generateDeviceCommand(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.DeviceCommand  command ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result generateDeviceCommand(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.DeviceCommand command,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation generateDeviceCommand");
        System.out.println(messageEntity);
        System.out.println(command);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId189702638");
            _return.setResultCode(2119570030);
            _return.setResultText("ResultText1264718664");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id1916126297");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#generatePreloadedOSM(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.PreloadedOnScreenMessage  message ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result generatePreloadedOSM(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.PreloadedOnScreenMessage message,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation generatePreloadedOSM");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId1972907665");
            _return.setResultCode(-385467021);
            _return.setResultText("ResultText1843535758");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1385132231");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#preloadMessage(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.PreloadedMessage  message ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result preloadMessage(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.PreloadedMessage message,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation preloadMessage");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId615311894");
            _return.setResultCode(1260875188);
            _return.setResultText("ResultText1057983307");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1110815282");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#deleteOSM(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.MessageHandle  message ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result deleteOSM(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.MessageHandle message,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation deleteOSM");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-360803942");
            _return.setResultCode(1460134037);
            _return.setResultText("ResultText1128372857");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1975544749");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#generateOSM(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.OnScreenMessage  message ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result generateOSM(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.OnScreenMessage message,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation generateOSM");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-1194769660");
            _return.setResultCode(2102797667);
            _return.setResultText("ResultText-1611595550");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1963348949");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#diagnoseOSM(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.OnScreenMessage  message ,)com.verimatrix.schemas.omitypes.PackageList  packageList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result diagnoseOSM(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.OnScreenMessage message,com.verimatrix.schemas.omitypes.PackageList packageList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation diagnoseOSM");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(packageList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId1098259233");
            _return.setResultCode(-765277528);
            _return.setResultText("ResultText1540892387");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id1904472925");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#generatePackageOSM(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.OnScreenMessage  message ,)com.verimatrix.schemas.omitypes.PackageList  packageList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result generatePackageOSM(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.OnScreenMessage message,com.verimatrix.schemas.omitypes.PackageList packageList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation generatePackageOSM");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(packageList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId537334287");
            _return.setResultCode(2101284031);
            _return.setResultText("ResultText-2008254863");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id1991458624");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#removePreloadedMessage(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.PreloadedMessage  message ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result removePreloadedMessage(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.PreloadedMessage message,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation removePreloadedMessage");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-38159905");
            _return.setResultCode(1224694186);
            _return.setResultText("ResultText1014035553");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id127153778");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.verimatrix.omi.Messaging#generatePreloadedPackageOSM(com.verimatrix.schemas.omitypes.MessageEntity  messageEntity ,)com.verimatrix.schemas.omitypes.PreloadedOnScreenMessage  message ,)com.verimatrix.schemas.omitypes.PackageList  packageList ,)com.verimatrix.schemas.omitypes.SessionHandle  sessionHandle )*
     */
    public com.verimatrix.schemas.omitypes.Result generatePreloadedPackageOSM(com.verimatrix.schemas.omitypes.MessageEntity messageEntity,com.verimatrix.schemas.omitypes.PreloadedOnScreenMessage message,com.verimatrix.schemas.omitypes.PackageList packageList,com.verimatrix.schemas.omitypes.SessionHandle sessionHandle) { 
        LOG.info("Executing operation generatePreloadedPackageOSM");
        System.out.println(messageEntity);
        System.out.println(message);
        System.out.println(packageList);
        System.out.println(sessionHandle);
        try {
            com.verimatrix.schemas.omitypes.Result _return = new com.verimatrix.schemas.omitypes.Result();
            _return.setResultId("ResultId-591084682");
            _return.setResultCode(763477538);
            _return.setResultText("ResultText-31282717");
            java.util.List<com.verimatrix.schemas.omitypes.ResultData> _returnResultData = new java.util.ArrayList<com.verimatrix.schemas.omitypes.ResultData>();
            com.verimatrix.schemas.omitypes.ResultData _returnResultDataVal1 = new com.verimatrix.schemas.omitypes.ResultData();
            _returnResultDataVal1.setId("Id-1768892914");
            byte[] _returnResultDataVal1Data = new byte[] {};
            _returnResultDataVal1.setData(_returnResultDataVal1Data);
            _returnResultData.add(_returnResultDataVal1);
            _return.getResultData().addAll(_returnResultData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
